### ISSUE TITLE
FrameIDFactory- unreachable code

### ISSUE THREAD

**Issue by tzachshabtay** [filoe/cscore#102]
I'm guessing that the following code:

case FrameID.InvolvedPeopleList:
                    if (version == ID3Version.ID3v2_4)
                        id = "TIPL"; break;
                    id = "IPLS"; break;

should actually be written as:

case FrameID.InvolvedPeopleList:
                    if (version == ID3Version.ID3v2_4)
                        { id = "TIPL"; break; }
                    id = "IPLS"; break;

**Comment by filoe** [comment]
Could you be a little bit more detailed? Which file/class, method, line?
