### ISSUE TITLE
WaveForm zoomed in scrolling

### ISSUE THREAD

**Issue by Digot** [filoe/cscore#104]
Hi!

I'd like to know how to modify the WaveForm example to make the WaveForm zoom in and have it scrolling with a fixed point where the current wave of the audio is played.

Here is an example: http://puu.sh/pjNWn/c4fc0c2aee.png

How can I do this?

**Comment by postacik** [comment]
I am working on a waveform editor which uses cscore to read and play audio files.

Here is the link to the GitHub project:

https://github.com/postacik/SoundFactory

Currently it converts stereo files to mono and displays and plays single channel.

You can use the mouse wheel + ctrl key to zoom in and out.

I hope this might be a starting point for you and I would be glad if you can contribute.

My plan is to make it a full featured wave editor like Audacity.

**Comment by Digot** [comment]
But I actually want the waveform to move not a cusor

**Comment by postacik** [comment]
The editor in SoundFactory works just like the editor in Audacity.

When you open a file, it is zoomed enough to fit in the window. If you zoom in more, then you can move the waveform using the scroll bar or the mouse wheel.

Just give it a try.

**Comment by filoe** [comment]
Just out your editor. Works very nice. Also with big files (bigger than 1h). Keep it up :).

**Comment by postacik** [comment]
Thanks. Your library helped me a lot.
