### ISSUE TITLE
post-build stop does not fail if required tools are missing

### ISSUE THREAD

**Issue by Ziriax** [filoe/cscore#107]
It seems in the CSPROJ you commented out the EXIT statements. By design?

**Comment by filoe** [comment]
Is there any problem with it?

**Comment by Ziriax** [comment]
Well, instead of using the NUGET package, I forked your CSCORE repo, fixing the code I reported. 

Then I used just the CSCORE project in my solution, not being aware that the post-build step also required the projects in your TOOLS directory. 

I did not get any error, but of course certain parts of my code didn't work anymore because the native stubs where not patched. So if the post-build step would actually fail, this would have saved me some trouble. And since you already wrote all the checks and nice messages, in the post-build, just removing the REM statement before the EXIT would be enough to get this behavior :-)

**Comment by filoe** [comment]
Should be fixed :).
