### ISSUE TITLE
help where I can download the offline documentation

### ISSUE THREAD

**Issue by EAxp3** [filoe/cscore#108]
I need documentation.
I have no internet at home

Can anybody help me
I cannot download the html here

[CSCore](http://filoe.github.io/cscore/sharpDox/1.1.0-release/index.html#article/home)

**Comment by opcon** [comment]
The github documentation is hosted here: https://github.com/filoe/cscore/tree/gh-pages/sharpDox

**Comment by filoe** [comment]
As already mentioned by @opcon, you can download the documentation from the gh-pages branch. 
The documentation is also available in form of the `CSCore.xml` file when building cscore.
