### ISSUE TITLE
WasapiOut not working with Windows 10 final

### ISSUE THREAD

**Issue by DanielGilbert** [filoe/cscore#11]
Maybe I'm missing something, but I cannot Initialize the WasapiOut, because I receive an "OutOfRangeException" for the parameter "value":

   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)

It occurs, because in the InitializeInternal Method, the "Latency" parameter gets set to 0. That is because of the _audioClient.StreamLatency being 0. This only happens on the Release Version of Windows 10. I haven't had the Problem on Windows 7, 8, 8.1 and Windows 10 Insider Preview .

The error even occurs on a clean install of Windows 10. Any idea what could be the reason for this behaviour?

I'm initializing the WasapiOut with a WriteableBufferingSource, based on a WasapiLoopbackCapture on another device.

**Comment by filoe** [comment]
Could you please provide some more details? I would need to know all relevant parameters of the soundout class.

**Comment by DanielGilbert** [comment]
Hi - I'm not quite sure what you mean by "parameters", so I wrote a small sample application. :) 

![wasapi_sample](https://cloud.githubusercontent.com/assets/3011428/9002641/d5719d78-3766-11e5-8f1b-4babc062ea91.PNG)

This application simple takes the output on the default audio device, and loops it to the audio device, given by the id that is entered in the above textbox. (So you need at least two Audioendpoints for this sample, and you should find the right id.)
Now, when running this app on Windows 7 (by pressing "Start"), everything works as expected. Running it on Windows 10, it catches the "Latency"-Exception.

You can try the example, if you have Windows 10 at hand: 

http://danielgilbert.de/SimpleWasapiLoopback.zip

(it's built using Visual Studio 2015 and .NET 4.5.2, using NuGet to get the CSCore Pre-Release)

**Comment by filoe** [comment]
Thanks, i am going to take a look at it.

**Comment by DanielGilbert** [comment]
Thanks for the fast workaround - just had the chance to check it, and it's working perfect with Windows 10 now. However, strange from Microsoft.
