### ISSUE TITLE
Strange behavior when reading a sound file as samples

### ISSUE THREAD

**Issue by lukasz-matylla** [filoe/cscore#110]
I encountered a confusing error when I open a sound file as a sample source and try to read it. For some reason, the total number of samples I can read is not equal to the length of the source - the position in the source moves forward a bit faster than the real number of samples read.

This can be seen in this code, for many different *.wav files.

    using (var waveSource = CodecFactory.Instance.GetCodec(source))
            {
                using (var mono = waveSource.ToMono().ChangeSampleRate(AudioSource.SampleRate).ToSampleSource())
                {
                    buffer = new float[mono.Length];
                    var position = 0;
                    format = mono.WaveFormat;

                    while (!cancel && position < buffer.Length)
                    {
                        var toRead = Math.Min(AudioSource.SampleRate, buffer.Length - position);
                        var read = mono.Read(buffer, position, toRead);

                        if (read == 0)
                        {
                            //Log.Debug(nameof(this.ToWaveFormat), $"{source} cannot be read; format not recognized");
                            return;
                        }

                        if (read < toRead)
                        {
                            //Log.Debug(nameof(this.ToWaveFormat), $"Error when reading audio file for conversion, at position {position} of {buffer.Length}. Wanted to read {toRead} samples, got {read}");
                            return;
                        }

                        position += read;
                        //UpdateProgress(position / buffer.Length);
                    }
                }
            }

What can cause this kind of behavior?

**Comment by filoe** [comment]
It seems like this is caused by the DmoResampler. I'm currently not sure how to solve it. Maybe I'm gonna find some kind of solution for it.

**Comment by filoe** [comment]
There is no perfect solution for this problem. But it should do the job.
