### ISSUE TITLE
Same sound playing several times at once.

### ISSUE THREAD

**Issue by joey45654** [filoe/cscore#111]
Hi, I would like to use CSCore for a game in which I play the same sound (mp3) at the same time (up to 10 times) with an offset.

What I've tried so far is to store the FileStream in a MemoryStream and then each time the sound is played its copied to a new MemoryStream which is then provided to a new WaveSource and a WaveOut.

This principally works, but it doesnt sound correctly. it feels like random parts of the start are cut off. and the whole sound then has a lot of noise to it.

is my approach the correct one to play the same sound several times?

**Comment by filoe** [comment]
For games I would recommend using XAudio2 (on Windows systems).
