### ISSUE TITLE
Latest version not yet on Nuget?

### ISSUE THREAD

**Issue by Ziriax** [filoe/cscore#112]
It seems nuget does not yet contain the latest version, any idea when this will be released?

**Comment by filoe** [comment]
The latest release is on nuget. See https://github.com/filoe/cscore/releases

**Comment by Ziriax** [comment]
Thanks for fast response.

It seems that the code on GitHUB contains some fixes I proposed that did not make in into 1.1.

For example, in `WaveFileReader.cs`, the `if (tmp is DataChunk)` is not removed in 1.1:

GitHUB master version

```
       private List<WaveFileChunk> ReadChunks(Stream stream)
        {
            var chunks = new List<WaveFileChunk>(2);
            do
            {
                var tmp = WaveFileChunk.FromStream(stream);
                chunks.Add(tmp);

                var fmtChunk = tmp as FmtChunk;
                if (fmtChunk != null)
                {
                    _waveFormat = fmtChunk.WaveFormat;
                }
                else
                {
                    stream.Position += tmp.ChunkDataSize;
                }

            } while (stream.Length - stream.Position > 8); //8 bytes = size of chunk header

            return chunks;
        }
```

NuGet 1.1 release

```
 private List<WaveFileChunk> ReadChunks(Stream stream)
        {
            var chunks = new List<WaveFileChunk>(2);
            do
            {
                var tmp = WaveFileChunk.FromStream(stream);
                chunks.Add(tmp);

                var fmtChunk = tmp as FmtChunk;
                if (fmtChunk != null)
                {
                    _waveFormat = fmtChunk.WaveFormat;
                }
                else if (tmp is DataChunk)
                {
                    stream.Position += tmp.ChunkDataSize;
                }

            } while (stream.Length - stream.Position > 8); //8 bytes = size of chunk header

            return chunks;
        }

```

**Comment by filoe** [comment]
You're right. Not every fix is available on nuget. Version 1.2 containing these fixes will be available in August. If you're looking for specific fixes, you can also take a look at the Milestone assigned to the issue. For example issue #105 got the milestone 1.2. That means it will be available with version 1.2. 
I'm trying to maintain these milestones.

**Comment by Ziriax** [comment]
Got it, my bad! Keep up the great work. PS: Can we donate for your work?

**Comment by filoe** [comment]
Glad to hear that. No there is actually no way to donate for the project. A star on github in order to make this project a bit popular is donation enough :). I'm doing this project just for fun. But anyway ... thanks!

**Comment by filoe** [comment]
Actually ... since there were a couple of requests regarding donations ... there is a donation button on the readme page of the repo now.
But my attitude regarding donations is still the same. I'm doing it for fun and the purpose of this project is not to make money. If someone would like to donate, it is really great gesture and I appreciate it. But no one has to.

**Comment by Ziriax** [comment]
I just donated 50 Euro, since your project saved me a lot of time. Thanks!

**Comment by filoe** [comment]
Wow, that is a lot! Thank you very much :-) :+1:
