### ISSUE TITLE
A PCL library maybe?

### ISSUE THREAD

**Issue by theweavrs** [filoe/cscore#113]
Support for UWP (Universal Windows Platform) would be nice to have. Is it possible?

**Comment by filoe** [comment]
Support for Mono is currently in development. Support for UWP is currently not planed. It would be very time consuming. If there would be support for mobile platforms, I would bring it to all xamarin platforms.

**Comment by JunielKatarn** [comment]
Suport for UWP, Android and iOS via Xamarin.Forms (aside from the actual low-level audio implementation) can be achieved by making the library target either of the following:
1. .NET Standard 1.0
2. .NET Portable, Profile 259.
(See https://portablelibraryprofiles.stephencleary.com/).

I'd like to help out tweaking the project file to make it compliant.

@filoe, are there any guidelines to build the project? I get tons of build errors when trying to compile a fresh git checkout.

**Comment by filoe** [comment]
Well the problem will be the actual low-level audio implementation :(.

**Comment by JunielKatarn** [comment]
Yeah, it's going to be a huge task, but we need the .NET code to run in other platforms without Mono in order to start researching.

How do you build it? Just opening in Visual Studio?

**Comment by filoe** [comment]
We'll try to target netstandard in the future. See #288.
