### ISSUE TITLE
PostCompilation steps did not run

### ISSUE THREAD

**Issue by slaner** [filoe/cscore#118]
I tried to test Visualization sample, but CalliMethodPtr method in InteropCalls class has keep throwing NotImplementedException and it's body coded like this:

    [CSCalli]
    internal static unsafe int CalliMethodPtr(void* _basePtr, int streamIndex, NativeBool selected, void* p)
    {
        throw new NotImplementedException();
    }

I downloaded CSCore 1.1.0-release.
And also it does not contains Mono.Cecil libraries so I added it by myself.

**Comment by slaner** [comment]
There's no solution for this issue?..
Anyone?

**Comment by filoe** [comment]
I'm sorry. My answer somehow got lost. Thought I've already answered this issue.
The problem is, that it seems like the PostCompilation-Steps did not run. During the PostCompilation, the CSCli Tool replaces these methods with some special il instructions.

Make sure to build the CSCli Tool. There are some dependencies on Mono.Cecil. Just restore the nuget packages. Afterwards it should build correctly. Just rebuild the whole solution and it should work.

**Comment by slaner** [comment]
Thanks for your answer @filoe.
But it does not works for me. I just checked about Nuget package, there's already Cecil 0.9.5.4 version package installed to CSCli project. Tried to restore package - - there's no package to restore cause already all packages set-up.

Also tried to clean and rebuild, it throw same exception. I'm sorry for my bad english, but I don't get what is the problem on this.. I'm so confused. :O

**Comment by filoe** [comment]
Ok, so take a look at the output window of visual studio while building CSCore. 
Are there any errors? Are you building the latest version of the master branch?

**Comment by slaner** [comment]
Is there's anything I have to do to run this samples or CSCore works properly?

I just downloaded last release again, restore packages and rebuild it. But it still CSCli does not work...

**Comment by huylenguyen** [comment]
I'm getting this issue as well :( 

I'm attempting to run the samples to get a feel of the functionalities, but every time I try to load an mp3 file into the WinformsVisualisation sample, the class CSCore.MediaFoundation comes up with the error "NotImplementedException was unhandled", saying System.NotImplementedException is not implemented in CSCore.dll.

I've tried rebuilding the solutions, Mono.Cecil is up to date at 0.9.6.1 and NVorbis at 0.8.4

**Comment by slaner** [comment]
Well I changed post build event script.

    @echo off

    if $(ConfigurationName) == Debug set ilasm_args=/DLL /DEBUG=IMPL
    if $(ConfigurationName) == Release set ilasm_args=/DLL /OPTIMIZE

    call "$(SolutionDir)Tools\InlineILCompiler\InlineILCompiler\bin\$(ConfigurationName)\InlineILCompiler.exe"

    call "$(SolutionDir)Tools\CSCli\bin\$(ConfigurationName)\CSCli.exe" -file:"$(TargetPath)" -r:"RemoveObjAttribute" -c:"CSCalliAttribute"

    exit /b 0

Because there's an error with fetching environment variables in MSBuild (MSBuild uses % as reserved keyword, and MSDN says use %25 instead % but it also not works for me)

I changed post build event and re-build is successfully done. But samples still throw NotImplementedException

**Comment by slaner** [comment]
@huylenguyen Finally I solved this problem with my own. Try this:

CSCore -> Property -> Build Events -> Post Build Events
will filled a lot of codes. Replace original code to below:

    set target=$(TargetPath)
    set project=$(ProjectPath)
    set sdk=%PROGRAMFILES(x86)%\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools
    set framework=%WINDIR%\Microsoft.NET\Framework\v2.0.50727

    if $(ConfigurationName) == Debug set ilasm_args=/DLL /DEBUG=IMPL
    if $(ConfigurationName) == Release set ilasm_args=/DLL /OPTIMIZE

    call "$(SolutionDir)Tools\InlineILCompiler\InlineILCompiler\bin\$(ConfigurationName)\InlineILCompiler.exe"

    call "$(SolutionDir)Tools\CSCli\bin\$(ConfigurationName)\CSCli.exe" -file:"$(TargetPath)" -r:"RemoveObjAttribute" -c:"CSCalliAttribute"

    exit /b 0

And rebuild CSCore project, when re-build is completed, you can see this 4 lines at bottom on Output.

    3>  CSCli processed 469 types.
    3>  CSCli replaced 297 method-calls by Calli-instruction.
    3>  Cleaning up assembly. 7 types to remove from assembly.
    3>  CSCli patched assembly "CSCore.dll" successfully.

**Comment by huylenguyen** [comment]
That resolved it. Thank you very much :)

**Comment by filoe** [comment]
So the code posted [here](https://github.com/filoe/cscore/issues/118#issuecomment-233698026), solves the problem?

**Comment by slaner** [comment]
@filoe yes, problem solved :D

**Comment by filoe** [comment]
I'm sorry, but I still don't understand why there were any problems with the original code.
I would like to update the post build code, but I have to understand the issue. As far as I understand, it is just a simple batch file. And in a batch file I'm using the % character to create and use variables.

**Comment by slaner** [comment]
Because MSBuild uses % as a reserved keyword and it's not work properly.
I haven't tested it on multiple devices, but it's issued on other users.

There's no error on your code but MSBuild has.
So I recomment to make a batch file and fill with your post build event code and you just call a batch file at post build event.

Click the link below for more detailed information.(MSDN OFFICIAL)
https://msdn.microsoft.com/en-us/library/h7dhf0ty.aspx

**Comment by Ambusy** [comment]
The problem still exists in the latest download of CSCore. In the script there is one name for the Windows SDK. But that name is different for each version of Windows, as Microsoft changes the directory structure. A final solution (until we get Windows 10 SP1) is to find out which sdk path is valid, by trying them one by one in a loop. And add new paths as new windows appear and leave the old ones for the die hards.
On my Windows 7 SP1 (I still use CSCore 1.0.0.2) the path is 
  %25PROGRAMFILES(x86)%25\Microsoft SDKs\Windows\v7.1A\bin
on Windows 10 
  %25PROGRAMFILES(x86)%25\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools
