### ISSUE TITLE
Using equalizer on current sound device

### ISSUE THREAD

**Issue by antferr** [filoe/cscore#119]
In the example "EqualizerTest" I can use AppendSource(Equalizer.Create10BandEqualizer, out _equalizer) to add an equalizer to an audio source like a wav file.
Can I do the same thing on listening audio on the actual device?
A kind of equalization in real time on the device.
Thank you

**Comment by filoe** [comment]
I'm sorry, but as far as I know, you would have to kind of hook the wasapi rendering engine. It is defenitly not possible with cscore.
