### ISSUE TITLE
Help With Recording

### ISSUE THREAD

**Issue by Bombonatto** [filoe/cscore#121]
HI.

I´m trying to record the microphone sound with the under format, but the result is totally diferent.
Can anyone help me ?
Format:
Sample Rate: 8000
Channels: 1
Bits: 16

The code is:
WaveFormat waveFormat = new WaveFormat(8000, 16, 1, AudioEncoding.Gsm);
                capture = new WasapiCapture(false,AudioClientShareMode.Shared,100, waveFormat);
                capture.Initialize();  
                w = new WaveWriter(sUploadFile, capture.WaveFormat);
                capture.DataAvailable += (s, capData) =>
              {  
                  w.Write(capData.Data, capData.Offset, capData.ByteCount);
              };  
                capture.Start();

Thanks for all

**Comment by filoe** [comment]
The format specified in the constructor is just a suggestion. WasapiCapture has to choose a format, supported by the driver. It chooses the closest match of the supported formats. 
If you really need exactly that format, you have to apply some conversion.

**Comment by Bombonatto** [comment]
Thanks for your help.
Where can I get a documentation of cscore?

**Comment by filoe** [comment]
This is the only documentation... http://filoe.github.io/cscore/sharpDox/

**Comment by wahahadada** [comment]
Hi,I really need specified a format,how can ido?
can you please help me?
Thanks!

**Comment by filoe** [comment]
As mentioned in #120, the format passed to `WasapiCapture` is just a suggestion for the driver.
If you really want to make sure, that you're getting a specific format you have to do a little trick:

```
//create a new soundIn instance
ISoundIn soundIn = new WasapiCapture();
//optional: set some properties 
//soundIn.Device = ...
//...

//initialize the soundIn instance
soundIn.Initialize();

//create a SoundSource around the the soundIn instance
//this SoundSource will provide data, captured by the soundIn instance
SoundInSource soundInSource = new SoundInSource(soundIn) {FillWithZeros = false};

//create a source, that converts the data provided by the
//soundInSource to any other format
//in this case the "Fluent"-extension methods are being used
IWaveSource convertedSource = soundInSource
    .ToStereo() //2 channels (for example)
    .ChangeSampleRate(8000) // 8kHz sample rate
    .ToSampleSource()
    .ToWaveSource(16); //16 bit pcm

//register an event handler for the DataAvailable event of 
//the soundInSource
//Important: use the DataAvailable of the SoundInSource
//If you use the DataAvailable event of the ISoundIn itself
//the data recorded by that event might won't be available at the
//soundInSource yet
soundInSource.DataAvailable += (s, e) =>
{
    //read data from the converedSource
    //important: don't use the e.Data here
    //the e.Data contains the raw data provided by the 
    //soundInSource which won't have your target format
    byte[] buffer = new byte[convertedSource.WaveFormat.BytesPerSecond / 2];
    int read;

    //keep reading as long as we still get some data
    //if you're using such a loop, make sure that soundInSource.FillWithZeros is set to false
    while ((read = convertedSource.Read(buffer, 0, buffer.Length)) > 0)
    {
                    
    }

    //your logic follows here
    //for example: stream.Write(buffer, 0, read);
};

//we've set everything we need -> start capturing data
soundIn.Start();

```

**Comment by filoe** [comment]
I've added a tiny sample that should demonstrate the whole thing...

**Comment by wahahadada** [comment]
hi @filoe , thanks for your reply, i have use the code
`
               IWaveSource convertSoundSource = soundInSource
                .ToStereo()//2 channels  
                //.ToMono()//1 channel
                .ChangeSampleRate(96000)//48kHz sample rate   unity will crash,48kHz will be ok
                .ToSampleSource()
                .ToWaveSource(16);//16 bit pcm  //8, 16, 24, 32
`
i can change the channels and bit pcm, but the unity always crash when i change the sampleRate,anything wrong?
Thanks!

**Comment by filoe** [comment]
Are you using it inside of Unity3D?

**Comment by wahahadada** [comment]
Yes , Unity3D 5.4, can't we ?

**Comment by wahahadada** [comment]
Sorry,Need I pay any special attention  when using Unity3D?

**Comment by wahahadada** [comment]
Hi, i find it will be ok when i change the attributes of the recording device in the Windows control panel firstly.
Then i can record  microphone sound with my  format into a wav file,but i can not play it directly inside Unity using ISoundOut.cs and IWaveSource.cs  ,outside will be ok.
All will be ok when i use the default format.
I do not know how to improve my code, can you give some suggestion?
Thank you!

**Comment by filoe** [comment]
I've never tried CSCore with Unity3D. To be honest, I'm suprised to hear that it works with unity.
I don't know the technical restrictions of Unity and C#. CSCore does a lot "none-standard" tricks to provide its functionality. I'm currently working on a native resampler without any windows components involved. Currently CSCore uses the Windows Dmo-Resampler. Maybe that causes your problems.
Are you recording sound with Wasapi?
Could you may show me the relevant code which does not work and provide some error messages?

**Comment by wahahadada** [comment]
Hi,thanks for your patient answers,following is my code:
My Windows control panel setting: 2 channels,48kHz,16 bit

        private MMDevice SelectDevice()
        {
            //soundIn = new WasapiCapture(false, AudioClientShareMode.Exclusive, 5);
            soundIn = new WasapiCapture();
            //you can select a device here.
            Debug.Log("CaptureToWav");
            MMDeviceEnumerator deviceEnum = new MMDeviceEnumerator();
            MMDeviceCollection devices = deviceEnum.EnumAudioEndpoints(DataFlow.Capture, DeviceState.Active);
            if (devices.Count > 0)
            {
                foreach (var device in devices)
                {
                    Debug.Log(device);
                }

                return devices[0];//select the first device

            }
            return null;
        }
    	   public void StartRecord_(string filename)
        {
            if (SelectDevice() == null)
                return;
            ((WasapiCapture)soundIn).Device = SelectDevice();
            //capture.Device = deviceEnum.GetDefaultAudioEndpoint(DataFlow.Capture, Role.Multimedia);
            soundIn.Initialize();
            soundInSource = new SoundInSource(soundIn) { FillWithZeros = false };
            convertSoundSource = soundInSource
                .ToStereo()//2 channels  
                //.ToMono()//1 channel
                .ChangeSampleRate(48000)//48kHz sample rate,others will crash
                .ToSampleSource()
                .ToWaveSource(16);//16 bit pcm  //8, 16, 24, 32 (16 will be normal,ohters abnormal,but not crash)

            string path = Application.dataPath + @"/" + filename;
            memoryStream = new MemoryStream();
            waveWriter = new WaveWriter(path, convertSoundSource.WaveFormat);//memoryStream
            soundInSource.DataAvailable += DataAvailable_;

            soundIn.Start();

            StartTimer();
        }
      private void DataAvailable_(object sender, DataAvailableEventArgs e)
        {
            //read data from the converedSource
            //important: don't use the e.Data here
            //the e.Data contains the raw data provided by the 
            //soundInSource which won't have your target format
            byte[] buffer = new byte[convertSoundSource.WaveFormat.BytesPerSecond / 2];//2
            int read;

            //keep reading as long as we still get some data
            //if you're using such a loop, make sure that soundInSource.FillWithZeros is set to false
            while ((read = convertSoundSource.Read(buffer, 0, buffer.Length)) > 0)
            {
                //write the read data to a file
                // ReSharper disable once AccessToDisposedClosure
                waveWriter.Write(buffer, 0, read);
                //memoryStream.Write(buffer, 0, read);
            }
        }
        private void StopRecord_(object sender, EventArgs e)
        {
            Debug.Log("stopCapture");
            soundIn.Stop();
            soundInSource.DataAvailable -= DataAvailable_;
            waveWriter.Dispose();
            soundInSource.Dispose();
            soundIn.Dispose();

        }

It has confused me severl days,how can i improve my codes?

**Comment by filoe** [comment]
First of all: Unity3D is not officially supported.
Maybe I can provide some suggestions. But first I would need some more details: Which error does occur? When and where does it occur?

**Comment by wahahadada** [comment]
Hi, thank you for your patients.
When I change the sampleRate with recording,the Unity will crash.
The Error is:
The file 'Assets/1.wav' does not contain a supported 'wav' format (Unity doesn't support 0 length audio clips.)
It seems like that no byte recorded under the specified format.
Thank you again.

**Comment by filoe** [comment]
I'm sorry, I've forgot about this issue.
I can't see any problems with the code posted above. Anyway as I said before, I don't know how cscore is behaving within unity3d. 
Can you check the recorded file whether it is really empty? 
Try to run the code within a simple windows application.
