### ISSUE TITLE
Can I get a cheat-sheet about visualization the audio file or waveform?

### ISSUE THREAD

**Issue by slaner** [filoe/cscore#122]
I checked all about the samples, but there has no comment on source code. So it is hard to understand samples.

Can I get any explanation about samples like Waveform or Visualization?

**Comment by filoe** [comment]
I did not add a lot of comments. Just at a few important points. But feel free to ask me out whatever you don't understand.

**Comment by slaner** [comment]
@filoe Thanks for your kindness.

I am working on make a games like AudioSurf.
It analyse a music before game start and when game started, sending blocks depending music's decibel or instruments played on.

I can't give you any more detailed information, because I'm not good at English, sorry for this.

Q. How do I get specific Hz decibel on specific position?
- looping 0 to end , check every sections.

**Comment by filoe** [comment]
Determining the instruments played on will be quite tricky. 
But getting the loudness isn't a big deal at all. If you are talking about Hz, you will have to with frequencies. I'm not sure whether you're talking about simple peaks, a frequency spectrum, ...?
Please be more specific what exactly you are trying to get.
Anyway... eventually this project using cscore might help you: https://github.com/opcon/turnt-ninja

**Comment by opcon** [comment]
If you want to track individual beats then you want something called onset detection, which analyses music and returns where the beats occur. I ported a python onset detection library to C# which you can find here: https://github.com/opcon/onset-detection, which I am using in my game that @filoe linked above.

This method is quite exact and requires preprocessing the song (which takes ~ 15 seconds), so it may be easier to use a more simple peak finding algorithm that simply looks at the frequency spectrum as @filoe suggested.

This tutorial http://archive.gamedev.net/archive/reference/programming/features/beatdetection/ is a good introduction to the subject. I also found the tutorial series here: http://www.badlogicgames.com/wordpress/?category_name=onset-detection-tutorial helpful when I was learning about beat detection.

**Comment by slaner** [comment]
@filoe @opcon Thanks you guys really!
I'll working on it right now. Thanks again and have a nice day :)
