### ISSUE TITLE
Add overload methods for WasapiLoopbackCapture

### ISSUE THREAD

**Issue by njbmartin** [filoe/cscore#123]
As mentioned in issue #120, the `WasapiLoopbackCapture` should have some more overload methods to allow the capture to be configured.

I'm happy to work on this.

**Comment by filoe** [comment]
I'm going to add that soon.

**Comment by filoe** [comment]
You may have a look at it, whether it fits your needs?

**Comment by njbmartin** [comment]
Yes, it definitely fits my needs. Will take a look today. Thanks!

**Comment by njbmartin** [comment]
Beautiful!

Here's my code now:
```C#
var captureDevice = MMDeviceEnumerator.DefaultAudioEndpoint(DataFlow.Render, Role.Console);
var deviceFormat = captureDevice.DeviceFormat;
_wasapiCapture = new WasapiLoopbackCapture(100, new WaveFormat(deviceFormat.SampleRate, deviceFormat.BitsPerSample, deviceFormat.Channels <= 2 ? deviceFormat.Channels : 2));
```
