### ISSUE TITLE
Wasapi Loopback Capture-Change output format to PCM

### ISSUE THREAD

**Issue by vijaysharma992** [filoe/cscore#125]
Hi, Is there a way to change output file format to PCM from default IEEEFloat when using wasapi loopback capture. I can record the audio coming out of my speaker but it is in IEEEFloat Format. I want it it in 16bit PCM wave format as my other application cannot handle floating points. Please help this is really urgent, it is for my school project. Also please tell me how can i download latest cscore library from here. I downloaded it from codeplex and i think the one i have is quite old.

This is my code:

```
private WasapiCapture capture = null;
private List<byte> dataList = new List<byte>();
capture = new WasapiLoopbackCapture();
                capture.Initialize();

                capture.DataAvailable += (s, capData) =>
                {
                    for (int i = 0; i < capData.ByteCount; i++)
                    {
                        dataList.Add(capData.Data[i]);
                    }
                };
                //start recording
                capture.Start();
```

I am using a list to collect all bytes and then put it in a wav file format.

Thanks in advance...

**Comment by filoe** [comment]
Take a look at #121 and #120 and the https://github.com/filoe/cscore/tree/master/Samples/RecordWithSpecificFormat sample.

**Comment by vijaysharma992** [comment]
hi @filoe , thanks for your reply i am trying to run the sample but i am getting an error:

**MMDeviceEnumerator does not contain defination for EnumerateDevices**

as i mentioned in previous post, i downloaded the cscore dll from codeplex. and it is version 1.0, please guide me how to download latest from git hub. i am new to git hub and have no idea how to get the library. Thanks

```
 //select the device:
            var devices = MMDeviceEnumerator.**EnumerateDevices**(dataFlow, DeviceState.Active);
            if (!devices.Any())
            {
                Console.WriteLine("No devices found.");
                return;
            }

            Console.WriteLine("Select device:");
            for (int i = 0; i < **devices.Count**; i++)
            {
                Console.WriteLine("- {0:#00}: {1}", i, devices[i].FriendlyName);
            }
            int selectedDeviceIndex = ReadInteger(Enumerable.Range(0, **devices.Count**).ToArray());
            var device = devices[selectedDeviceIndex];
```

**Comment by filoe** [comment]
The builds at codeplex are faaar toooo old.
Use the github or nuget release.
