### ISSUE TITLE
Transfer WasapiCapture data over network and playback that data

### ISSUE THREAD

**Issue by kestik** [filoe/cscore#126]
Hello. How can I get `IWaveSource` from data, received from `WasapiCapture` and transfered over network?
On a server side i'm sending data to a client like this:
```csharp
WasapiCapture capture = new WasapiCapture(false, AudioClientShareMode.Shared, 500);
capture.Initialize();

capture.DataAvailable += (s, data) =>
{
    Send(data.Data, data.Offset, data.ByteCount);
}
capture.Start();
```

The question is - how can I playback this data on a client side? Thanks.

**Comment by filoe** [comment]
First of all the client has to know the format of the audio data.
Afterwards you can use the `WriteableBufferingSource` class to buffer data and play them. You may also want to set its `FillWithZeros` property to `true`. Otherwise the playback will stop if no data is available.

**Comment by kestik** [comment]
So, I sent a `WaveFormat` of initialized `WasapiCapture` first, successfully initialized `WriteableBufferingSource` with it, but got an exception when trying to initialize `WasapiOut` with this source. Exception says:
> Waveformat is not supported. Invalid WaveformatTag.

`WaveFormatTag` recieveved from initialized `WasapiCapture` is equal to `AudioEncoding.Extensible`.

Should I configure `WasapiCapture` or `WasapiOut` in a certain way or try to use another SoundIn and SoundOut?

**Comment by filoe** [comment]
What is the Subformat of the Waceformat? Are you sure, that you are transmitting the whole format. Note that the Extensible Waveformat got some additional fields.

**Comment by kestik** [comment]
Subformat is `{00000003-0000-0010-8000-00aa00389b71}`. Yes, seems like I forgot about existence of extensible waveformat during serialization. Last time used this great library a year ago. Thanks for help.

**Comment by filoe** [comment]
So i would guess, you've got your solution?

**Comment by kestik** [comment]
Yes, everything working now. Thanks.
