### ISSUE TITLE
Track to long?

### ISSUE THREAD

**Issue by 007Hughy** [filoe/cscore#128]
Ok so i have Noticed that if you have a song / track that is over 2h 43min it will not be able to generate the correct track length im not to concerned about this but just thought that i should report it in case you were unaware of it as i randomly stumbled on it when trying to play a 5+ hour recoding.... anyway just thought you should know.

Best Regards

**Comment by 007Hughy** [comment]
Also i noticed that if you call the Track Number from ID3v2.Quickinfo.TrackNumber it will display the Year not the Track Number im using the latest from Nuget v1.1.0
`ExampleLable.Text = CSCore.Tags.ID3.ID3v2.FromFile("test.mp3").QuickInfo.TrackNumber;`

**Comment by filoe** [comment]
I'm sorry. I've did some tests with a 03:30:00 wav file. I can't reproduce the issue. Please provide some more details. Stacktrace or file to reproduce it would be nice. If the file is too big, please provide some details on its format and length.

**Comment by 007Hughy** [comment]
Hope this helps will be able to upload the file another day as my internet will reset in a few days time (currently using a mobile connection)

Artist: 
Title: 
Album: 
Track: 
Disc: 
Genre: 
Year: 
Rating: 
Composer: 
Size: 321.46 MB  (91% Compressed)
Original Size: 3.46 GB
Length: 5 hours 51 minutes
Channels: 2  (stereo)
Sample Rate: 44.1 KHz; 
Bit Rate: 128 kbps
Encoder: Blade (Guess)
Encoder Settings: Constant Bit Rate 128 kbps
Audio Quality: Low  (Lossy)
Contains: 
Channel Mapping: Left, Right
File: FLID Anime_21052015_00_38
Type: MP3 Format Sound    [.mp3]

**Comment by filoe** [comment]
Perfect, gonna try to reproduce it.
Thanks!

**Comment by 007Hughy** [comment]
if you want to 100% reproduce it i used this Android App to record the song... once again hope this helps :)

https://play.google.com/store/apps/details?id=com.maxxt.animeradio

Best Regards

**Comment by filoe** [comment]
This should fix it. Seems like there was a problem with the marshaller.
