### ISSUE TITLE
EqualizerTest: sliders 0 and 9 don't seem to affect audio

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#129]
I'm implementing a 10 band equalizer based on your EqualizerTest sample. I noticed that changing the value of the 2 outermost sliders (0 and 9) doesn't affect audio playback. The other sliders seem to work.

This is reproducible with your EqualizerTest sample.

**Comment by filoe** [comment]
Well the filters defined by the default 10 band eq have to following center frequencies:

1. 31
2. 62
3. 125
4. 250
5. 500
6. 1000
7. 2000
8. 4000
9. 8000
10. 16000

But of course you can adjust that or build any equalizer you want (for example an equalizer with 20 filters).

**Comment by digimezzo** [comment]
Ok, that's easy enough. Thanks!

I based this question on a comparison I did with MusicBee's equalizer. It uses these frequencies:

1. 32
2. 64
3. 125
4. 250
5. 500
6. 1000
7. 2000
8. 4000
9. 8000
10. 16000

When I play with the values of the 32Hz and 16KHz filter, there is an effect on the audio. Would that mean that MusicBee is not really adjusting the frequencies that the equalizer displays?

**Comment by filoe** [comment]
Well, I don't know. It depends on the parameters of each filter. I've never played much with these parameters. I've did a few tests and set the default values to something that sound quite good. 
Maybe MusicBee is using a different `BandWidth`. I don't really know... :(
But as I said, you can play with these parameters by setting up your own equalizer:
https://github.com/filoe/cscore/blob/master/CSCore/Streams/Effects/Equalizer.cs#L69

**Comment by digimezzo** [comment]
No problem. That's good info you gave me. I was able to create my own Create10BandEqualizer function. I adapted the frequencies a bit more to what Winamp and VLC are using (starting around 60 or 70Hz). Works well. In winamp, audio is also not affected when playing with the 16K slider.

**Comment by filoe** [comment]
Well 16kHz is a quite high frequency. Try it out, generate a 16kHz sine wave and listen to it. I would bet that there are a lot of people who don't even hear the noise.
