### ISSUE TITLE
Problem with ID3v2

### ISSUE THREAD

**Issue by 007Hughy** [filoe/cscore#130]
I have noticed that if you call the Track Number from ID3v2.Quickinfo.TrackNumber it will display the Year not the Track Number, also it will fail to get the Artist info from time to time im using the latest build from Nuget v1.1.0
`ExampleLable.Text = CSCore.Tags.ID3.ID3v2.FromFile("test.mp3").QuickInfo.TrackNumber;`

Best Regards

**Comment by filoe** [comment]
Fixed it. But I still don't know what's wrong with the artist. Does it crash, does it return an empty string? Please be more specific. 
Also remember, this library is no tag library. The ID3 part is working, but it is not even documented. I've moved the focus to a raw audio library, dropping the tag parts more or the less. There are several nice tagging libraries out there which support nearly all types of tags.

**Comment by 007Hughy** [comment]
Sorry for the Lack of info im not quite use to this... as for the Artist it will fail to find the artist it will happen no matter what song i use have tested with MediaInfo.dll and that has no problems finding the info so yeah not quite sure how to go about further investigating the problem 
[http://puu.sh/qsKrI/44c7829f61.png](url)
`ExampleLable.Text = CSCore.Tags.ID3.ID3v2.FromFile("test.mp3").QuickInfo.Artist;`

**Comment by opcon** [comment]
If you are looking for a tag reader with more features then I suggest TagLib Sharp: https://github.com/timheuer/taglib-sharp-portable. I've used it in lots of my projects.
