### ISSUE TITLE
Loudness level

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#132]
Request: 
It would be great if you add a method to calculate audio loudness level. (and other standard audio level)

Thank you!

**Comment by filoe** [comment]
Could you please be a little bit more specific? Do mean some kind of peak meter.

**Comment by Mitra-M** [comment]
My English is very poor and can not properly explain, but please check the following links.
[What Is Loudness And Why Is It Important?](http://www.tcelectronic.com/loudness/loudness-explained/url)

[](https://en.wikipedia.org/wiki/Loudnessurl)

[](http://dsp.stackexchange.com/questions/2951/loudness-of-pcm-streamurl)

**Comment by filoe** [comment]
So you basically want to calculate the RMS of a signal given a specific block size?

**Comment by Mitra-M** [comment]
I am not sure!.  

Nowadays, Audio broadcast equipments (Radio / Video) has 3 types of level meter:
1- dBU
2- dB FS
3- dB Loudness


(For the EBU European Broadcasting Union)

But I can 't find a formula to convert the dBU to the dBLU.

Please take a look at this links:

[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiO8MD8vOnOAhXL6xQKHVVvDnIQFggcMAA&url=http%3A%2F%2Fwww.yamaki-ec.co.jp%2Feng%2Ffaq%2Ffiles%2Ffaq_01.pdf&usg=AFQjCNEfpjZTw8wnMIkaBfB18SGGoL4C1A&sig2=tUIozKUDfRvCXvkL3pBV0A](url)

[http://www.sonycreativesoftware.com/webhelp/soundforgepromac/2.0/ENU/Content/Loudness_Meters.htm](url)

I have little knowledge about it.

filoe , If this is a waste of time, Please do not spend your time for it and forget it.
