### ISSUE TITLE
Unicode chars in post-build batch file

### ISSUE THREAD

**Issue by MichaelClerx** [filoe/cscore#135]
Hi all,

I downloaded and opened CSCorej, but had considerable difficulty building until I found the post-build batch file in CSCore.csproj and tested it in a separate batch file.
It seems the unicode characters don't work on my windows 7 machine and cause the whole build to fail! Replacing them by something simpler (OK/FAIL, for example) solves the issue.

Is this a windows 7 thing? Or did something go wrong when downloading perhaps?

Library itself is looking great.

Thanks,
Michael

**Comment by Mitra-M** [comment]
Hi,

I think you need to copy Mono.Cecil.dll , Mono.Cecil.Mdb.dll , Mono.Cecil.Pdb.dll and Mono.Cecil.Rocks.dll files to ...\cscore-master\Tools\CSCli\bin\Debug (or reference them in the CSCli project)

**Comment by MichaelClerx** [comment]
Really? My issue was that the unicode characters in the batch file caused errors when the post-build batch was executed. I don't really see how fonts would affect this?

**Comment by Mitra-M** [comment]
Sorry, I think I did not understand well your question.

But I hope my answer to help others.

**Comment by MichaelClerx** [comment]
Thanks! After you posted that answer I ran into that issue as well :-)
