### ISSUE TITLE
Exception in application exit

### ISSUE THREAD

**Issue by ravriel** [filoe/cscore#136]
Hi,

While testing CsCore I encountered an exception. I managed to narrow down the error to the following:

```

class Program
    {
        static void Main(string[] args)
        {
            foreach (var mmDevice in MMDeviceEnumerator.EnumerateDevices(DataFlow.Render, DeviceState.Active))
            {
                Console.WriteLine("Device name: '{0}'", mmDevice.FriendlyName);

                AudioSessionManager2 sesionManager = AudioSessionManager2.FromMMDevice(mmDevice);

                AudioSessionNotification sessionNotification = new AudioSessionNotification();

                sesionManager.RegisterSessionNotification(sessionNotification);
            }

            Console.WriteLine("Press any key...");
            Console.ReadKey();

            // Following exception is thrown:
            // System.ArgumentOutOfRangeException was unhandled
            // Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
            //Additional information: Index was out of range. Must be non-negative and less than the size of the collection.

        }

    }
```

After key is pressed an ArgumentOutOfRangeException is thrown.
I'm using latest NuGet CsCore 1.1.0.

Thanks,
Ron

**Comment by filoe** [comment]
I would guess you don't have some kind of stack trace? 
Is it reproducable?

**Comment by ravriel** [comment]
Hi,

Problem is consistently reproduced over multiple machines.
Here's some more information:

Stack trace is:

`>	mscorlib.dll!System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument argument, System.ExceptionResource resource)	Unknown
 	mscorlib.dll!System.Collections.Generic.List<CSCore.CoreAudioAPI.IAudioSessionNotification>.RemoveAt(int index)	Unknown
 	CSCore.dll!CSCore.CoreAudioAPI.AudioSessionManager2.Dispose(bool disposing)	Unknown
 	CSCore.dll!CSCore.Win32.ComObject.Finalize()	Unknown
`

Exception message is: `Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index`

and my output before crash is:

`Device name: 'Digital Audio (S/PDIF) (4- High Definition Audio Device)'
Device name: 'Headphones (4- High Definition Audio Device)'
Device name: 'Line 1 (Virtual Audio Cable)'`

Thanks,
Ron

**Comment by filoe** [comment]
Thanks for your feedback. This error got already fixed within the master branch. 
It will be fixed with the next release.
