### ISSUE TITLE
Allow setting of stream duration

### ISSUE THREAD

**Issue by vanstinator** [filoe/cscore#14]
I'm in the process of creating a native music player for the Plex ecosystem. I'm passing in the URI for the stream and the Plex API gives me the time of the stream which I'd like to pass in to the source like so...

_waveSource = CodecFactory.Instance.GetCodec(uri, streamLength);

This would allow me to query the current location to set the time bar without having to hack together some magical formula on my end. I can make the changes myself, test it, and submit a pull request if that works too.

**Comment by vanstinator** [comment]
While I found a work around by setting a max time in my GUI the ability to set this at the core of the audio stream would still be nice.

**Comment by filoe** [comment]
You can set and get the Position of a source by accessing the Position property. You can also query the length of a source by using the Length property. But not all implementations support that. Why should I adjust the CodecFactory?
