### ISSUE TITLE
MP3 Encoder with bitrate limit

### ISSUE THREAD

**Issue by Nekromancer** [filoe/cscore#141]
I'm following mp3 encoding sample to create downsampler. Basically, what i need, is to produce as small mp3 file as possible. I'm doing it now with ffmpeg like that:

`ffmpeg -i <input> -ac 1 -ar 11025 -acodec mp3 -ab 16k <output>`

It's working, but i have a huge number of conversions, and calling ffmpeg binary causes a few problems.

What i tried is code:

```
        public void ConvertFile(string path, string targetPath)
        {
            var supportedFormats = MediaFoundationEncoder.GetEncoderMediaTypes(AudioSubTypes.MpegLayer3);
            if (!supportedFormats.Any())
            {
                throw new Exception("No mp3 encoder");
            }

            IWaveSource source;
            try
            {
                source = CodecFactory.Instance.GetCodec(path);

                if (
                    supportedFormats.All(
                        x => x.SampleRate != source.WaveFormat.SampleRate && x.Channels == source.WaveFormat.Channels))
                {
                    //the encoder does not support the input sample rate -> convert it to any supported samplerate
                    //choose the best sample rate with stereo (in order to make simple, we always use stereo in this sample)
                    var sampleRate =
                        supportedFormats.OrderBy(x => Math.Abs(source.WaveFormat.SampleRate - x.SampleRate))
                            .First(x => x.Channels == source.WaveFormat.Channels)
                            .SampleRate;

                    Console.WriteLine("Samplerate {0} -> {1}", source.WaveFormat.SampleRate, sampleRate);
                    Console.WriteLine("Channels {0} -> {1}", source.WaveFormat.Channels, 2);
                    source = source.ChangeSampleRate(sampleRate);
                }
            }
            catch (Exception)
            {
                throw new Exception("Decoding problem");
            }

            var newSource = source.ToMono();

            using (newSource)
            {
                using (var encoder = MediaFoundationEncoder.CreateMP3Encoder(newSource.WaveFormat, targetPath, 16 * 1024))
                {
                    var buffer = new byte[newSource.WaveFormat.BytesPerSecond];
                    int read;
                    while ((read = newSource.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        encoder.Write(buffer, 0, read);

                        Console.CursorLeft = 0;
                        Console.Write("{0:P}/{1:P}", (double)newSource.Position / newSource.Length, 1);
                    }
                }
            }

            source.Dispose();
        }
```

The issue is - output mp3 have 48k bitrate. Is there a down limit that prevents me from using 16k?

**Comment by filoe** [comment]
MediaFoundation is quite limited. I'm working on a ffmpeg wrapper (see ffmpeg branch). 
The only problem I'm still having is that I'm not able find a source which builds for win, linux, osx (each with x64 and x86). I'm not that used to C ...

**Comment by Nekromancer** [comment]
Okey, thanks anyway :)

**Comment by filoe** [comment]
I'm looking forward to implement a propper ffmpeg api as soon as possible... Would be perfect for bringing cscore to linux and osx... 
Anyway ... I'm not really happy with all this MediaFoundation stuff. It makes quite a lot of troubles...

**Comment by Nekromancer** [comment]
Yes, i'm aware. I'm dealing with it for quite long time. Shame that there isn't really good C# ffmpeg/lame wrappers out there. Looking forward for yours!

**Comment by opcon** [comment]
Since you're using the generator [https://github.com/Ruslan-B/FFmpeg.AutoGen](https://github.com/Ruslan-B/FFmpeg.AutoGen) for FFMpeg bindings, would it be feasible to have 2 or more versions of the API in CSCore, and the version to use could be selected based on the FFMpeg library present on the system? As far as I can tell the major API break happened going from v2.x to v3. Most Linux distributions are on v2 I think.

**Comment by filoe** [comment]
First of all, you can't compile the code generated by the binding generator. 
The other problem is that there are not just major API breaks. As far as I could see, there are many little API breaks by chaning structures and so on (for example see https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/29).

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
