### ISSUE TITLE
Wasapi exclusive mode doesn't work when changing IWaveSource SampleRate

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#143]
This bug is reproducible by launching the EqualizerTest sample in Wasapi Exclusive mode.

How to reproduce:

Change line 50 in EqualizerTest from

`_soundOut = new WasapiOut();`

to

`_soundOut = new WasapiOut(false, CSCore.CoreAudioAPI.AudioClientShareMode.Exclusive, 200);`

Start a new instance of the EqualizeTest, click button "Open" and select an mp3 to play. This exception occurs:

> System.NotSupportedException: Could not find a supported format.
>    at CSCore.SoundOut.WasapiOut.SetupWaveFormat(IWaveSource source, AudioClient audioClient)
>    at CSCore.SoundOut.WasapiOut.InitializeInternal()
>    at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
>    at EqualizerTest.MainWindow.button1_Click(Object sender, EventArgs e) in C:\Git\cscore\Samples\Equalizer\MainWindow.cs:line 63
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at EqualizerTest.Program.Main() in C:\Git\cscore\Samples\Equalizer\Program.cs:line 16
>    at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
>    at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

This exception seems caused by "ChangeSampleRate(32000)" on line 56. After removing the "ChangeSampleRate(32000)" line, so the source is created as such:

```
var source = CodecFactory.Instance.GetCodec(ofn.FileName)
                    .Loop()
                    .ToSampleSource()
                    .AppendSource(Equalizer.Create10BandEqualizer, out _equalizer)
                    .ToWaveSource();
```

 the mp3 file plays without throwing the above exception.

I'm not sure if this is a bug, or exclusive mode just doesn't support changing SampleRate. I'd like to understand why this exception happens.

**Comment by filoe** [comment]
Give it a try please.

**Comment by digimezzo** [comment]
That fixes it. Thanks!
