### ISSUE TITLE
Audio Compressor/Limiter

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#144]
Request: 
It would be great if you implement an audio Compressor/Limiter.

From internet:
**"**Dynamic range compression (DRC) or simply compression is a signal processing operation that reduces the volume of loud sounds or amplifies quiet sounds by narrowing or compressing an audio signal's dynamic range. Audio compression reduces loud sounds above a certain threshold while leaving quiet sounds unaffected.
Compression is commonly used in sound recording and reproduction, broadcasting, live sound reinforcement and in some instrument amplifiers.**"**

**"**Compressors are used to reduce the dynamic range of audio where vocals and/or instruments change from low to very high levels in a project. Compression helps prevent distortion and allows optimization of various sounds across a project to perfectly blend sounds. **Limiters** stop signal output from exceeding a certain level, and are often used during the mastering process to prevent distortion and clipping in digital and analog systems**"**

Thank you!

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
