### ISSUE TITLE
Sounds Synchronisation

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#146]
I want to play an input device to 3 output devices simultaneous. (I mean of the "simultaneous" is the difference less than 250 milliseconds)

I can play 3 instances of the WasapiCapture with the same input device to 3 instances of the WasapiOut with the different output devices, But the delay time and the difference between sounds sometimes reaches about 8 seconds! (it is random, Sometimes there is no delay and good works).

I used this :
 `soundIn = new WasapiCapture(true, AudioClientShareMode.Shared, 1,null,ThreadPriority.Highest);`
and
`soundOut = new WasapiOut(true, AudioClientShareMode.Shared, 1,ThreadPriority.Highest);
     `   

But had no effect.

How can I set  the delay time or the difference time between output sounds to a minimum?  (Or at least a fixed amount)

Thanks!

**Comment by Mitra-M** [comment]
I'm Sorry.
My question was wrong, and it was my fault code. (Threading issue)

Now I noticed that the delay is much less than what I expected.  (I think that is less than 30 milliseconds)
Thanks to the CSCore!

Another question :
To do what I mentioned above there is a better way?  (Instead of making 3 instances of the WasapiCapture and 3 instances of the WasapiOut to do it)

sorry again ,and thank you.

**Comment by Mitra-M** [comment]
I tested and compared the NAudio to do this. 
Now, I'm sure the latency of the CSCore is much less than the NAudio.

the CSCore is great.

**Comment by filoe** [comment]
Glad to hear that :).
