### ISSUE TITLE
 AudioMeterInformation 

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#147]
I want to get the sound peak value of an input device. (Without capture it)

To do that I use this code:

```
void timer_Tick(object sender, EventArgs e)
        {
 using (var meter = AudioMeterInformation.FromDevice(currDevice))
                        {
                        LeftMeter.Value = (int)(100 * meter[0]);
                        RightMeter.Value = (int)(100 * meter[1]);
                         }
       }
```

If the "Recording Devices" window is open (by Right-click on the small speaker on the taskbar, and select Recording Devices) , it will work otherwise it not work.

(I think the AudioMeterInformation does not callback.) 

please tell me how can solve this problem?

Thanks

**Comment by filoe** [comment]
Don't create a new instance within the tick event. 
Try to create one instance and reuse it.

**Comment by Mitra-M** [comment]
The problem is not solved , But I realized that is not due to the CSCore.

I tested the CoreAudio and the NAudio , both  have the same problem.

It seems that the problem is related to the Windows CoreAudio API.

Anyway, thank you!

**Comment by Mitra-M** [comment]
The problem was solved with the help of filoe in [this issue](https://github.com/filoe/cscore/issues/166)

Thanks to filoe.
