### ISSUE TITLE
Is it possible to play internet radio streams?

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#148]
I tried playing internet radio streams. Some examples of those I tried:

[http://us1.internet-radio.com:8180/](http://us1.internet-radio.com:8180/)
[http://uk2.internet-radio.com:31491/](http://uk2.internet-radio.com:31491/)
[http://s7.voscast.com:7000/](http://s7.voscast.com:7000/)

I tested it by downloading the cscore source code, replacing following line in the EqualizerTest:

`var source = CodecFactory.Instance.GetCodec(ofn.FileName)`

by:

`var source = CodecFactory.Instance.GetCodec(new Uri("http://s7.voscast.com:7000/"))`

And then opening a random audio file, so the button1_Click() code is called. I'm always getting this exception:

```
Interops::MFCreateSourceReaderFromURL caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported.".
at CSCore.MediaFoundation.MediaFoundationException.Try(Int32 result, String interfaceName, String member) in C:\Git\cscore\CSCore\MediaFoundation\MediaFoundationException.cs:line 54
```

**My question**: is playing of such streams just not supported, or do I miss something in code to be able to play them?

**Comment by filoe** [comment]
I'm not happy with the media foundation, online streaming implementation.
You can try out the ffmpeg branch. It's not released yet, but you can give it a try. Please note LGPL license.

**Comment by filoe** [comment]
Could try it out yet?

**Comment by digimezzo** [comment]
Yes. The ffmpeg branch throw a ""Stream does not support seeking." exception.

```
   at System.IO.BufferedStream.get_Position()
   at CSCore.Tags.ID3.ID3v2.SkipTag(Stream stream) in C:\Users\rapha\Desktop\cscore-ffmpeg\CSCore\Tags\ID3\ID3v2.cs:line 48
   at CSCore.Codecs.MP3.DmoMp3Decoder.ParseForMp3Frames(Stream stream, Boolean enableSeeking) in C:\Users\rapha\Desktop\cscore-ffmpeg\CSCore\Codecs\MP3\DmoMp3Decoder.cs:line 90
   at CSCore.Codecs.MP3.DmoMp3Decoder..ctor(Stream stream, Boolean enableSeeking) in C:\Users\rapha\Desktop\cscore-ffmpeg\CSCore\Codecs\MP3\DmoMp3Decoder.cs:line 54
   at CSCore.Codecs.MP3.Mp3WebStream.BufferProc(Object o) in C:\Users\rapha\Desktop\cscore-ffmpeg\CSCore\Codecs\MP3\Mp3WebStream.cs:line 274
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by filoe** [comment]
Seems like you're not using the correct decoder. Don't use the CodecFactory within the ffmpeg branch. Use the https://github.com/filoe/cscore/blob/ffmpeg/CSCore.Ffmpeg/FfmpegDecoder.cs class.

**Comment by digimezzo** [comment]
Oops thanks. After using the correct decoder and putting the necessary ffmpeg libraries in the correct subfolder, streaming seems to work fine with that branch. I tried all of the above streams and some more.

The ffmpegdecoder is only for streaming right? Not for playing files?

**Comment by filoe** [comment]
Of course you can also use it for decoding files.

**Comment by digimezzo** [comment]
Ok indeed. I was getting a FileNotFoundException in FfmpegDecoder when trying to play a local file. It is caused by FfmpegDecoder  line 94:

`int result = InteropCalls.avformat_open_input(formatContext, uri.AbsoluteUri, null, null);`

uri.AbsoluteUri causes the path not to be recognized. Replacing it with "uri.LocalPath" solves that. There might be a need for a constructor for decoding local files.

**Comment by digimezzo** [comment]
I've been reading a lot about whether or not it is OK to distribute ffmpeg in binary form with a GPL v3 application, as there is a lot of scaremongering going around on the internet. As far as I understand GPL and LGPL, it would be OK, as long as the required license, copyright notices and link to source code are provided together with the GPL v3 application. So my conclusion:

- distribute cscore ffmpeg in binary form with a GPL v3 application 
- disitribute ffmpeg in binary form with a GPL v3 application 

-> both OK if this is included: license, copyright, link to source code or distributed application

Am I right or am I missing something?

**Comment by filoe** [comment]
Well the main problem I'm having with ffmpeg is not the license. The main problem is that I would like to have a stable version of source code, I can compile for win x86/x64, linux x86/x64, osx x86/x64.
I've tried hard, but I wasn't able to do that yet. Since the api of ffmpeg changes quite frequently I can't use any already compiled binaries.

**Comment by filoe** [comment]
We've got an update now. Ffmpeg is now supported (beta).
There is currently no nuget package available.
