### ISSUE TITLE
Playback speed?

### ISSUE THREAD

**Issue by DanDevPC** [filoe/cscore#149]
I'm trying to figure out how to adjust the playback speed (both pitch and tempo). According to [this page](https://en.wikipedia.org/wiki/Audio_time-scale/pitch_modification#Resampling) resampling should be what I want, so I tried using `DmoResampler`, but it seems to just reduce quality while keeping the same speed. Do you have an idea of how I could implement this?

**Comment by DanDevPC** [comment]
Nevermind, sorry. Got it to work by reading the original stream in a SampleAggregator.

```c#
        private class TestSource2 : SampleAggregatorBase
        {
            private readonly ISampleSource _source;

            public TestSource2(ISampleSource source, float pitch) : base(source.ChangeSampleRate((int)(source.WaveFormat.SampleRate*pitch)))
            {
                _source = source;
            }

            public override int Read(float[] buffer, int offset, int count)
            {
                return _source.Read(buffer, offset, count);
            }
        }
```

**Comment by DanDevPC** [comment]
Turns out the above code doesn't work: it randomly throws a `NullReferenceException` during the song:
```
   at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)
   at dEngine.Instances.Sound.PitchShiftingSource.Read(Single[] buffer, Int32 offset, Int32 count) in C:\Users\Dan\Source\Repos\dEngine\Engine\dEngine\Instances\Audio\Sound.cs:line 480
```
I noticed the `Source` property of the `Pcm16BitToSample`, which should be a `DmoMp3Decoder`, is set to null when I catch the exception. I don't know if it causes the exception or the exception causes it. The `DmoMp3Decoder` doesn't seem to be disposed and claims to be seekable.

**Comment by filoe** [comment]
If the `Source` field of the `Pcm16BitToSample` class is null, the NullReferenceException occurs.
It is only null if the instance got disposed. Check you dispose it somewhere.

**Comment by DanDevPC** [comment]
I've just realized what's happening: every time I set the pitch I'm leaving the old `PitchShiftingSource` to get GC'd, but this also disposes the original cached source voice. Is there a way to dispose of the wrapped voices without disposing the root/original source?

**Comment by filoe** [comment]
You can do something similar like this: https://github.com/filoe/cscore/blob/master/CSCore/SoundOut/WasapiOut.cs#L847

**Comment by DanDevPC** [comment]
Thanks for the help, that seems to be what I need.
