### ISSUE TITLE
Convert m4a or wav to flac

### ISSUE THREAD

**Issue by theoosaam** [filoe/cscore#151]
How can I convert audio to flac I just work with google cloud speech api,  and only flac format I can send it to cloud  if you have exemple about that .

Thanks

**Comment by filoe** [comment]
I'm sorry. There is currently no flac encoder available. There is pure c# implementation of a flac decoder but not for a encoder. You could use any third party libraries or implement a flac encoder by using ffmpeg (see ffmpeg branch).

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.

**Comment by snalesso** [comment]
IMHO this is out of scope of the library, which is meant for playback, and not for conversions between formats.

**Comment by filoe** [comment]
Well, there is already an ffmpeg decoder. We could implement an ffmpeg encoder.
