### ISSUE TITLE
Anyway to do selective program recording?

### ISSUE THREAD

**Issue by robinator8** [filoe/cscore#152]
I'd like to be able to record multiple audio files at once, for each program, including my microphone. 
Eg. If I had TS3, GTAV, and Spotify open all at once and I was recording, they would all be separate audio files. This was I could cut out the spotify stuff, and turn up the TS3 voices.

Edit: First time using Git Hub, how can I make this a question?

**Comment by filoe** [comment]
I'm sorry. There is no native windows api for recording a specific program. You would have to play around with hooking windows api's or creating virtual drivers. CSCore does not support it. I'm sorry.
