### ISSUE TITLE
Your contact information.

### ISSUE THREAD

**Issue by Jean-de-Klerk** [filoe/cscore#154]
Good afternoon Filoe (Florian). Is there a way I can contact you personally? I don't want to mention my e-mail address on this space. If I mention my e-mail address on this space, then my e-mail address will be flooded with junk mail. I have send 3 messages to you via the web site, https://naudio.codeplex.com or https://www.codeplex.com , because this is the only way I can contact you at this moment. Your company is still listed on the web site of https://www.codeplex.com . My e-mail address was mentioned in one of the messages that was send to you via the web site, https://naudio.codeplex.com . I am not very sure how this web site (https://github.com) works in terms of receiving - and/or sending messages. Please, let me know. Thank you for your help. Regards. Mr. Jean de Klerk.

**Comment by filoe** [comment]
I've replied to your e-mail.
