### ISSUE TITLE
Can CSCore do quantization? 

### ISSUE THREAD

**Issue by RoyZ7** [filoe/cscore#156]
Can CSCore do quantization? 

By quantization or audio sync I mean, that the audio waves will be "remaped" to match the time signature/tempo and not just to "move" the audio to start at another point in time.. the duration of the audio clip doesn't change, but its content does. 

Quantization like all the "Digital Audio Workstation" programs have.. 

Thanks in advance for your help :)

**Comment by filoe** [comment]
What do you mean with 

> "remaped" to match the time signature/tempo.

**Comment by RoyZ7** [comment]
I mean that it changes the audio wave in a way that the spikes are aligned with the time signature, this would better explain it: [wikipedia](https://en.wikipedia.org/wiki/Quantization_(music)) and [Screenshots of programs which demonstrate it](https://www.google.co.il/search?q=audio+quantization&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi6mcGyktHPAhULWhQKHbhOA0QQ_AUICCgB&biw=1097&bih=528#tbm=isch&q=audio+quantize&imgrc=_) 
Thanks a lot! :)

**Comment by filoe** [comment]
I'm afraid that this is currently not supported.
You could use CSCore as some kind of base for implementing something like that. But it is currently not supported out of the box.

**Comment by RoyZ7** [comment]
Sorry, I didn't see your answer on time, thank you very much :)

בתאריך 27 באוק' 2016 12:26,‏ "Florian Rosmann" <notifications@github.com>
כתב:
