### ISSUE TITLE
Lots of plops when using a SineGenerator and a WasapiOut

### ISSUE THREAD

**Issue by MichaelClerx** [filoe/cscore#157]
Hi all,

I'm trying to use CSCore to play simple sine waves, using the SineGenerator class and a WasapiOut.

However, if I start/stop playback a couple of times, I start getting lots of plops during playback, so I'll have started playback and then a few seconds later several loud plops occur.

Does anybody know how this could happen and how I could debug this issue?

Thanks,
  Michael

**Comment by filoe** [comment]
Do you have some kind of sample code to reproduce it?
