### ISSUE TITLE
CodecFactory question

### ISSUE THREAD

**Issue by renevaessen** [filoe/cscore#162]
Hi.

Too bad, there isn't a way to use the CodecFactory with a stream.

But besides that, my question is this:

In the constructor:

            if (Mp1Decoder.IsSupported)
            {
                Register("mp1", new CodecFactoryEntry(s => new Mp1Decoder(s),
                    "mp1", "m2ts"));
            }

            if (Mp2Decoder.IsSupported)
            {
                Register("mp2", new CodecFactoryEntry(s => new Mp1Decoder(s),
                    "mp2", "m2ts"));
            }

Should the 2nd one, not instanciate an instance of the Mp2Decoder instead?

**Comment by filoe** [comment]
It is not so easy to find a propper decoder just by using streams.
Anyhow I'm planing to build a ffmpeg wrapper. Ffmpeg can determine a propper decoder by a raw stream.
