### ISSUE TITLE
Sound affected by UI thread

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#165]
Hello , dear filoe

I have a problem with WPF + CSCore.   (I did not see this problem in Winform+ CSCore)

I'm using WasApi to PlayBack/Capture , But sound affected by UI thread.
 
for example : When showing a message (During play/capture) by this code:
 
`MessageBox.Show("a message");`

or this :
 ```
Dispatcher.BeginInvoke((Action)delegate
                   {
                    MessageBox.Show("a message");
    }, System.Windows.Threading.DispatcherPriority.Background);

```
I can hear a moment of noise/silence .

Please tell me how to solve this problem?

Thank you!

**Comment by filoe** [comment]
I don't know your scenario. But you could try to increase the latency.
Does it make difference whether you call the messagebox from any ui events or from any background thread using the dispatcher?

**Comment by Mitra-M** [comment]
I wanted to make a sample project for you , But I realized that the problem is related to Visual Studio debug mode , I built my project in release mode ,it works great now.

I am sorry. this was my mistake.
Please delete this post or close it.
 
Thank you!

**Comment by filoe** [comment]
Nice to hear that. That's they way I like to solve solutions :).
Anyway thanks for reporting.

**Comment by Mitra-M** [comment]
:).
