### ISSUE TITLE
How to get level of an output device without playing another output device? (using PeakMeter)

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#166]
Hello , dear filoe

I want to get level of an output device using PeakMeter without assigning another output device.

The following code shows the level of **OutputDevice1** as well.

       `using (var soundIn = new WasapiLoopbackCapture())
                  {
                 soundIn.Device=**OutputDevice1**;
                 soundIn.Initialize();

                 IWaveSource source = new SoundInSource(soundIn) { FillWithZeros = true };
                using (var peakMeter = new PeakMeter(source.ToSampleSource()))
                {
                     soundIn.Start();
                     peakMeter.PeakCalculated += peakMeter_PeakCalculated;

                     using (var soundOut = new WasapiOut())
                    {
                        soundOut.Device=**OutputDevice2**;
                        soundOut.Initialize(peakMeter.ToWaveSource());

                          soundOut.Play();

                        Console.ReadKey();
                    }
                }
            }`

Please tell me how can I do that without assigning/playing **OutputDevice2**?

Thank you!

**Comment by filoe** [comment]
So you basically want to display the peak for all devices without playing anything?
You can use the `AudioMeterInformation` class.
For some usage examples take a look at 

- https://github.com/filoe/cscore/blob/master/CSCore.Test/CoreAudioAPI/EndpointTests.cs#L84

- CanGetAudioMeterInformationPeakValue

**Comment by Mitra-M** [comment]
Because of [this issue](https://github.com/filoe/cscore/issues/147) I can't use the AudioMeterInformation class.

There is no other way?

Thank you!

**Comment by filoe** [comment]
I've added a sample which demonstrates the usage.

**Comment by Mitra-M** [comment]
Works great.

2  BIG thanks.

A big thank  for the EndpointAudioMeter sample.
and 
A big thank  for the WPF sample.
