### ISSUE TITLE
Recording: Multiple visualizations question

### ISSUE THREAD

**Issue by igl00** [filoe/cscore#167]
I'm building a basic recording app and I was wondering if someone could point in the right direction for this feature.

I have a visualization that starts when the recording has started, which works great. However, I also want to have a peak meter that is running at all times to let the user get their input levels correct before hitting the record button. From what I can tell I would either need to have a second WasapiCapture() that is running at all times to pass data to the PeakMeter or I would need to write some custom start/stop functionality around the file writer to control the disk output on a single WasapiCapture() that is running at all times.

Are these the only two options or is there a better way of doing this that I'm missing?

Thanks!

**Comment by filoe** [comment]
Could you show some basic code you're already using?
It should be quite easy to integrate. Where is the data for the visualization coming from?
You can just add the `PeakMeter` class to the chain.

**Comment by igl00** [comment]
Thanks @filoe! The reply you gave in [this issue](https://github.com/filoe/cscore/issues/166) pointed me in the right direction to get things working.
