### ISSUE TITLE
Synchronous playback

### ISSUE THREAD

**Issue by VitalyEr** [filoe/cscore#168]
Hello , dear filoe.
How can I play simultaneously one audio file into two separate audio output?
Thank you!

**Comment by filoe** [comment]
That will be really tricky. There is currently no nice solution for that.
You can of course create two instances of any SoundOut object and play two seperate sources.
But you'll have to hope for the best what "simultaneously" concerns.

**Comment by Mitra-M** [comment]
@VitalyEr , It is quite possible using CSCore. (It worked for me.)

I played 8 files simultaneously without any latency. (I can not hear any delay)

create two or more instances and play seperate sources.

Note:

1 - Hard drive speed should be just right. 
2 - set latency and ThreadPriority like this:

`soundOut = new WasapiOut(true, AudioClientShareMode.Shared, 1, ThreadPriority.Highest);`

**Comment by VitalyEr** [comment]
@filoe I want to play simultaneously two large flac files. Can I create a cache for faster playback?

**Comment by filoe** [comment]
You can create a cache by using the `CachedSoundSource` class.
You could also mix both files together during playback. 
See the SimpleMixer example.
