### ISSUE TITLE
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module.

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#170]
I'm using CSCore in my media player. When changing the audio device (reproduced by plugging in a USB headset), my application crashes every few times (meaning: sometimes it doesn't crash, sometimes it does). 

The crash seems to happen before CSCore is notified that the audio device changed (I'm monitoring MMNotificationClient.DefaultDeviceChanged for that).

I attached the source code of CSCore to the running application and reproduced the problem. This is the exception I got:

> An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module.

I realize this is very vague, but I do not know how to get more information out of this. it seems to happen in external code (maybe some P/Invoke failing?) 
Any ideas where this could come from or how to debug this in a better way?

**Comment by filoe** [comment]
Are you using the latest version of the master branch?
Is it connected to the new stream routing feature?

**Comment by digimezzo** [comment]
No, I'm using release 1.1.0. I suspect the issue is caused by something I'm doing after all, but it is so hard to troubleshoot. Some times it happens as lot, sometimes it doesn't. Long story short: when the default audio device changes and MMNotificationClient.DefaultDeviceChanged is raised the first time, I remember playback position, stop SoundOut, and start a timer that waits until the last MMNotificationClient.DefaultDeviceChanged has been raised (it is raised multiple times when change the audio device). After the timer expires, I re-initialize SoundOut, start playing the current file, and set the position to what it was before.
It is a hacky solution, but the only one I could think of. I suspect the issue occurs when stopping SoundOut, but it's hard to find out.

Does this stream routing allow me to do this in a proper way? If yes, is there an example I can look at?

**Comment by filoe** [comment]
It is hard for me to know why this actually occurs.
Streamrouting is built to handle these situations.
Is is brand new in cscore and not as much as tested as the rest of the features.
But it seems to be stable. If there are any bugs, as always report them. 
By default it handles device format changes and disconnected devices.
In order to handle defaulf device changes, set the StreamRoutingOptions of the WasapiOut instance.

Regards!

**Comment by digimezzo** [comment]
Excellent! Thanks for the StreamRoutingOptions tip. I'll try that out. Anything is better than what I'm currently doing.

**Comment by digimezzo** [comment]
As far as I could see, the exception was caused by my ugly hack. I've now compiled the latest version of the source code, and am using StreamRoutingOptions.All. This works like a charm! Thanks. This issue can be closed.
