### ISSUE TITLE
Question : Is there a way to get information about the input file/stream ?

### ISSUE THREAD

**Issue by StefH** [filoe/cscore#173]
Question : Is there a way to get information like the WaveFormat, # channels and bitrate about the input file/stream ?

**Comment by filoe** [comment]
What kind of input are you talking about? 
If you open up any file using the CodecFactory you can get information about the WaveFormat.

**Comment by StefH** [comment]
I dont use the codec factory because I read from stream.

-----Oorspronkelijk bericht-----
Van: "Florian Rosmann" <notifications@github.com>
Verzonden: ‎24-‎12-‎2016 16:00
Aan: "filoe/cscore" <cscore@noreply.github.com>
CC: "Stef Heyenrath" <Stef.Heyenrath@gmail.com>; "Author" <author@noreply.github.com>
Onderwerp: Re: [filoe/cscore] Question : Is there a way to get information aboutthe input file/stream ? (#173)

What kind of input are you talking about?
If you open up any file using the CodecFactory you can get information about the WaveFormat.

**Comment by StefH** [comment]
Only the `DmoMp3Decoder` does have a property **InputFormat** which contains information about the original input.

All the other decoders only have an **OutputFormat**.

**Comment by filoe** [comment]
I'm afraid that cscore is not the best way for solving problems like this.

**Comment by StefH** [comment]
I was thinking to use the MediaInfo (https://www.nuget.org/packages?q=mediainfo) library for that, however there are several available...
