### ISSUE TITLE
CSCore.XAudio2  unhandle exception

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#176]
I want to use Xaudio2 + X3daudio to play  sound files/devices.

If I don't set FilterParameters on streamingSourceVoice ,Xaudio2 works good. 

But if I set FilterParameters ,causes this error always:

> An unhandled exception of type 'CSCore.XAudio2.XAudio2Exception' occurred in cscore.dll
Additional information: IXAudio2Voice::SetFilterParameters caused an error: 0x88960001, "Unknown HRESULT"

streamingSourceVoice.SetOutputMatrix and streamingSourceVoice.SetFrequencyRatio works , but the below code causes the exception.
  
            ` streamingSourceVoice.SetFilterParameters(new FilterParameters { Frequency = 0.5f, OneOverQ = 0.5f, Type = FilterType.LowPassFilter }, XAudio2_8.CommitNow);`
      

Thanks.

**Comment by filoe** [comment]
0x88960001 means `XAUDIO2_E_INVALID_CALL`.
Did you create the source voice using the `UseFilter` `VoiceFlags`?

**Comment by Mitra-M** [comment]
No I didn't , You said right.
 (it is because of my little knowledge about x3daudio)

I think it is better to me that I  wait , until you put the x3daudio example that you said me before.

so ,this can be closed.

Thank you!

**Comment by filoe** [comment]
Do you have a local copy of the branch?
If yes, could you please try to set the VoiceFlags to VoiceFlags.UseFilter see https://github.com/filoe/cscore/blob/master/CSCore/XAudio2/StreamingSourceVoice.cs#L33?
If that solves the problem, I'll update the wrapper in order to make this configurable.

**Comment by Mitra-M** [comment]
Excellent diagnosis.!
 The problem solves. (you should update the wrapper)

Thank you so much
