### ISSUE TITLE
Low latency audio for Windows 10

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#177]
Dear filoe ,Please have a look at [this article](https://msdn.microsoft.com/en-us/windows/hardware/drivers/audio/index) .  (specially [this session](https://msdn.microsoft.com/en-us/windows/hardware/drivers/audio/low-latency-audio#windows_audio_session_api_wasapi))

It might be useful to CSCore.

Thanks.

**Comment by filoe** [comment]
Thats a good point. I'll have a look at it.

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
