### ISSUE TITLE
How to capture audio from soundcard whilst sending through network stream?

### ISSUE THREAD

**Issue by TechnoMaster** [filoe/cscore#179]
I have the code working if I create a wav file on the local machine, but I would like to record off the card and then immediately begin to send it through the network stream to the server

**Comment by filoe** [comment]
The `ISoundIn` interface defines a `DataAvailable` event. 
You can use it to trigger sending the captured data.
For a more detailed answer, I need some more details.

**Comment by TechnoMaster** [comment]
Hi, I did manage to figure it out already. Thanks for the great library

**Comment by filoe** [comment]
Glad to hear that. I'm gonna close it.
