### ISSUE TITLE
When Wasapi exclusive mode is enabled, only a high pitched sound is played.

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#180]
As you already know, I'm using cscore in my audio player Dopamine. I was notified by a user that enabling Wasapi excusive mode doesn't work anymore: instead of playing the correct sound, it plays a high pitched sound. I tested this out and can confirm it. As it has worked correctly before, I tried to pin down the commit which causes this.

I've pinned it down to commit 6cf434bfc41e82ae36a18c33c71358b0cc760e50. When using a cscore build which is from before that commit, Wasapi exclusive mode works fine. When using a build starting from that commit, Wasapi exclusive mode is broken.

It happens on a Realtek sound chip (if that is of any importance).

If can also confirm that reverting the changes from commit 6cf434bfc41e82ae36a18c33c71358b0cc760e50 on the latest code of cscore (on 6-01-2017) fixes this issue.

**Comment by filoe** [comment]
Well, it is quite tricky. 
I could reproduce it but I don't know what to do with it.
The `IsFormatSupported` function returns true for the format, but it sounds like garbage. 
I can hardly change the logic to ignoring the return value of the mentioned function. In fact it is the only way to determine whether a format is supported or not.

What I've done is the I check whether the device format is supported or not(I've heard about drivers which report that they don't support their own internal format ...). 
On my system it solves the problem. There is currently not much more I could do.
As far as I could see, I'm doing everything according the specification and recommendation of Microsoft.
