### ISSUE TITLE
Getting Waveform Data is very slow

### ISSUE THREAD

**Issue by tjscience** [filoe/cscore#187]
First off, I would like to say that this library is really awesome! Great job on it.

I hope this is something that I am doing wrong. When I attempt to get waveform data from a Wavesource, it takes anywhere from 7 - 30 seconds to obtain the data from the Wavesource.

I am using the following code (taken directly from the waveform sample) to grab the data:

```
        public float[][] GetData(IWaveSource waveSource)
        {
            if (waveSource == null)
                throw new ArgumentNullException("waveSource");

            var sampleSource = new InterruptDisposeChainSource(waveSource).ToSampleSource();

            var channels = sampleSource.WaveFormat.Channels;
            var blockSize = (int)(sampleSource.Length / channels / NumberOfPoints);
            var waveformDataChannels = new WaveformDataChannel[channels];
            for (var i = 0; i < channels; i++)
            {
                waveformDataChannels[i] = new WaveformDataChannel(blockSize);
            }

            var buffer = new float[sampleSource.WaveFormat.BlockAlign * 5];
            var sampleCount = 0;

            var flag = true;
            while (flag)
            {
                var samplesToRead = buffer.Length;
                var read = sampleSource.Read(buffer, 0, samplesToRead);
                for (var i = 0; i < read; i += channels)
                {
                    for (var n = 0; n < channels; n++)
                    {
                        waveformDataChannels[n].AddSample(buffer[i + n]);
                        sampleCount++;
                    }
                }

                if (read == 0)
                    flag = false;
            }

            foreach (var waveformDataChannel in waveformDataChannels)
            {
                waveformDataChannel.Finish();
            }

            Length = sampleCount;


            return waveformDataChannels.Select(x => x.GetData()).ToArray();
        }

```

Any help would be greatly appreciated here. 

Thanks!

**Comment by filoe** [comment]
What is the format and length of the track.

**Comment by tjscience** [comment]
I did notice that the lengths on the tracks I was testing with were all different. They are all mp3 and here are some times for them (track length = time to get data):

4:08 = 2104 ms.
5:21 = 2716 ms.
1:06:00 = 31578 ms.

It was taking 7 min for the 4 and 5 minute tracks before, but now it is faster. I am not sure why.

**Comment by filoe** [comment]
I'm sorry. I was quite busy last week and forgot about your issue.
The problem is just, that decoding a whole mp3 and building up the waveform takes some time.
You can compare it with applications like audacity. Audacity is a native application which is for sure a bit faster, but even with audacity it takes some time to load the waveform.
