### ISSUE TITLE
Using FFMpeg overwrites existing call to SetDllDirectory

### ISSUE THREAD

**Issue by Nikey646** [filoe/cscore#189]
If possible, could we have an option to disable the call completely, or require the user to do it themselves.

I use the call to SetDllDirectory to keep my project clean for other dependencies, and would in fact prefer if i could move the required binaries to my existing location that has other c/++ dlls that i p/invoke into.

**Comment by filoe** [comment]
Of course we can do something about it.
What would you suggest? Some kind of configuration?

**Comment by Nikey646** [comment]
I think there are a couple ways that it could be done, such as reading a value from app.config, or accepting a "FfmpegConfig" object somewhere that will take priority over the default path. A less appealing options would be to require that the user register the search path their self, but that is definitely less then desirable, because it encourages leaving all the various binaries in the root folder.

In truth, a simple boolean that can be toggled from an external assembly indicating if the default structure should be used or not would work for me personally.

**Comment by filoe** [comment]
Implemented with c63df1506f4a44e817fd2f8df2fad71d069e1d60

**Comment by filoe** [comment]
Does that fit your needs? Please give it try and give me some feedback.

**Comment by Nikey646** [comment]
Looks good to me :D
