### ISSUE TITLE
non-english characters in the file name

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#196]
Both `CodecFactory` and `FfmpegDecoder` can't open  file ,If the file name contains non-English characters. (e.g :  chinese , Arabic , . . . )

OS= windows

**Comment by filoe** [comment]
For now, I would recommend to open the file as a `FileStream` and pass the `FileStream` to the `FfmpegDecoder`.

**Comment by Mitra-M** [comment]
OK. (the FileStream works)

Thank you

**Comment by JJtheJJpro** [comment]
Close?
