### ISSUE TITLE
Gracefully switch waveindevice when current is removed

### ISSUE THREAD

**Issue by dwebb7** [filoe/cscore#199]
Is there a way to detect that the current WaveInDevice has been removed. My app is recording from the default WaveInDevice is removed (eg, by turning off a usb interface) my app will lockup.

**Comment by filoe** [comment]
I would suggest to switch to wasapicapture.

**Comment by dwebb7** [comment]
I was at one point and now I can't remember why I switched to WaveIn. Will wasapicapture fail more gracefully or allow me to know when the device is removed?

**Comment by filoe** [comment]
There is no reason for using WaveIn while your system supports Wasapi.
Wasapi is not supported on Windows XP.

**Comment by filoe** [comment]
Is this still an open question?

**Comment by dwebb7** [comment]
Yes, at some point I will try  WASAPI and hope this fixes the issue.
