### ISSUE TITLE
Visualization Library

### ISSUE THREAD

**Issue by tjscience** [filoe/cscore#200]
I have been working on DJ software for some time now and have been using bass.net for audio processing, playback, etc. I have decided to replace this with cscore, which I have been very impressed with! I have also started revamping my visualizations by building a separate library of which the sole purpose is to encapsulate cscore behavior and all visualizations to be used in WPF projects. Currently the code is hosted on my private github, but I may make it public. Would anyone be interested in using it and/or helping with it? I have waveform done and will be adding the following: timeline, spectrum analyzer, equalizer, time clock, dynamic waveform, among other things. Here is a screenshot of my simple waveform control:

![capture](https://cloud.githubusercontent.com/assets/3706870/22578481/18f3984c-e997-11e6-819a-1ad8a2cb7006.PNG)

Just want to say a big thank you to the author of cscore! This is a very nice audio library for being open source. Great work!

Here is a screenshot from my current software in "queue" mode. I am currently using the wpf visualization library for visualizations.

![djlab](https://cloud.githubusercontent.com/assets/3706870/22578620/0df1e8e4-e998-11e6-9024-db421c30785e.png)

**Comment by Mitra-M** [comment]
Hi,

It is a good work.

> Would anyone be interested in using it and/or helping with it?

Yes, I am interested. It would be nice if  you share it. (Especially,  If the latest version of the cscore is used in your project)

Thanks.

**Comment by filoe** [comment]
I'm a big fan of Open Source. Of course it would be interesting to have a look at it :).

**Comment by przemo1983** [comment]
I am interested as well. Please share it.

**Comment by tjscience** [comment]
Hi everyone. I have done some initial work on the project and made it public as promised! Let me know what you think and where you can help if possible. You can find the project at https://github.com/tjscience/audion

**Comment by filoe** [comment]
Thanks for sharing! Looks great. Is your DJ software open source as well?

**Comment by tjscience** [comment]
The DJ software is not currently open source. Although, I am seriously thinking of making an open source version with audion and cscore.

**Comment by filoe** [comment]
I'll close this. Unfortunately, your project is offline 👎

**Comment by tjscience** [comment]
Hey guys. Unfortunately my time frame to get the parent project done for this was narrowed and I had to go with NAudio to complete it. There were many strange issues that I was having with cscore with regard to sharing sample sources and other types between multiple different UI mechanisms. I do plan on releasing audion with NAudio and then circling back around and hooking it up with cscore to try to figure out some of the issues. Sorry for tabling this!
