### ISSUE TITLE
WinformsVisualization sample - geting X-asis and Y-asis values

### ISSUE THREAD

**Issue by przemo1983** [filoe/cscore#204]
Hi.

Could you please help me to get info from WinformsVisualization  sample code about values of X-asis (Hz) and Y-asis (dB)?
I have audio with 1kHz tone, and a would like to inform user on X-asis that this is exactly 1kHz and on Y-asis about dB of loudness.

Is it possible to get such an information from functions in this sample?

Thanks.

**Comment by filoe** [comment]
So you would like to know the loudnesd of a specific frequency? Is that correct or am I wrong?

**Comment by przemo1983** [comment]
Yes, that's right. Is it possible?

**Comment by filoe** [comment]
Of course it is. You need to calculate a FFT and then get the band index of your specified frequency.
To start, take a look at the WinformsVisualization sample.
To get the index of the band take a look at this method: https://github.com/filoe/cscore/blob/master/Samples/WinformsVisualization/Visualization/BasicSpectrumProvider.cs#L23
