### ISSUE TITLE
Calling Dispose() no longer frees the underlying FileStream in WaveWriter.cs

### ISSUE THREAD

**Issue by DanielGilbert** [filoe/cscore#205]
Hi,

this issue was introduced by fixing #138 - the underlying FileStream, which gets created using this constructor:

```
public WaveWriter(string fileName, WaveFormat waveFormat)
            : this(File.OpenWrite(fileName), waveFormat)
```

won't be closed. This means that the file will never be released until the application exits, which makes it impossible to work with the file during program runtime outside the process (e.g. calling ffmpeg to convert it to another format).

From my perspective, `_disposeStream = false;` and `_disposeStream = true;` are just interchanged. The latter should be set in
```
public WaveWriter(string fileName, WaveFormat waveFormat)
            : this(File.OpenWrite(fileName), waveFormat)
```
and the former should be set in
```
public WaveWriter(Stream stream, WaveFormat waveFormat)
```

At least, this fixes it for me.

**Comment by filoe** [comment]
I ll have a look at it as soon as possible. Thanks for reporting!

**Comment by przemo1983** [comment]
I have the same problem. Could you please fix it?

**Comment by MulleDK19** [comment]
There's a major oversight here. Now you can't dispose of a WaveWriter without it closing the underlying stream, so now you can't access the data it's written to a stream. I had to use reflection to fix this.

```csharp
FieldInfo fieldInfo = w.GetType().GetField("_disposeStream", BindingFlags.NonPublic | BindingFlags.Instance);
fieldInfo.SetValue(w, false);
w.Dispose();```

**Comment by filoe** [comment]
Doss the referenced commit solve the problem?
If yes, I'm going to add a new release.

**Comment by MulleDK19** [comment]
I haven't tried it, but looking at the source, that should indeed fix it.

**Comment by MulleDK19** [comment]
Btw, things like MediaFoundationEncoder.CreateMP3Encoder has the same issue. It closes the output stream when it's disposed, so there's no way to use the data, unless the stream is a FileStream.

**Comment by filoe** [comment]
I will check that. Thanks for reporting!
