### ISSUE TITLE
Calling Dispose on a DMOMP3Decoder.cs does not close the stream

### ISSUE THREAD

**Issue by robbyxp1** [filoe/cscore#206]
Hi,
I'm seeing the file opened during MP3 playback being held locked for reading, even though I am disposing of the IWaveSource at the application layer.

Looking at the code, DmoMp3Decoder.cs holds the _stream, but during dispose does not close/dispose it.  I'm presuming thats where it should be done.  A Grep shows no disposals on the _stream.

Great tool BTW!

**Comment by filoe** [comment]
You are right. Thanks for reporting. I ll fix this as soon as possible.
