### ISSUE TITLE
Record to stream and recall after stopping audio capture

### ISSUE THREAD

**Issue by TechnoMaster** [filoe/cscore#207]
I am having issues recalling the stream after capturing my audio to a memorystream, each time I try it says the Wave Header is corrupt

**Comment by filoe** [comment]
Please provide some code that reproduces your issue.

**Comment by TechnoMaster** [comment]
_writer = new WaveWriter(MemoryStream, _finalSource.WaveFormat);


And I get the error when trying to play the audio using System.Media.SoundPlayer, everything works fine if I save to a file, but I need it to be in a memory stream

**Comment by TechnoMaster** [comment]
I have resolved the issue

**Comment by filoe** [comment]
You need to set the Position of the stream to zero.
