### ISSUE TITLE
XAudio 2.8 : An unhandled exception (Windows 10)

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#209]
Hi,

If we set `inputChannels `and `inputSampleRate `in the `CreateMasteringVoice `method, the following exception occurs when the `SetOutputMatrix `method runs. (for Windows 10 and XAudio **2.8**)

> An unhandled exception of type 'CSCore.XAudio2.XAudio2Exception' occurred in CSCore.dll
> Additional information: IXAudio2Voice::SetOutputMatrix caused an error: 0x88960001, "Unknown HRESULT".

for example this code in the X3DAudioSample :

   ` _masteringVoice = _xaudio2.CreateMasteringVoice (XAudio2.DefaultChannels, XAudio2.DefaultSampleRate);
`       
  works for both Windows 8.1 and 10, but if we change the code like this: 

 `  _masteringVoice = _xaudio2.CreateMasteringVoice(_waveSource.WaveFormat.Channels, _waveSource.WaveFormat.SampleRate);
`     
it works only for Windows 8.1 , and get the exception for windows 10.

**Comment by filoe** [comment]
What's the desired samplerate and number of channels?

**Comment by Mitra-M** [comment]
Channels=1 
Samplerate =44100

**Comment by filoe** [comment]
And what does your matrix look like?

**Comment by Mitra-M** [comment]
`  _streamingSourceVoice.SetOutputMatrix(_masteringVoice, _sourceChannels, _destinationChannels, dspSettings.MatrixCoefficients);`

I'm using your X3DAudioSample  sample.

To better diagnosis , Please in the X3DAudioSample project change this line :

`_masteringVoice = _xaudio2.CreateMasteringVoice (XAudio2.DefaultChannels, XAudio2.DefaultSampleRate);`

with this :

`_masteringVoice = _xaudio2.CreateMasteringVoice(_waveSource.WaveFormat.Channels, _waveSource.WaveFormat.SampleRate);`

and run that , Now, should the error occur.

**Comment by filoe** [comment]
Well it's hard to say where the error is coming from. 
The XAudio2 wrapper is just a wrapper for the XAudio2 API.
I don't see any reason for setting the number of channels and samplerate manually.
I would suggest to use the default values.

**Comment by Mitra-M** [comment]
It seems that the problem is related to Windows 10 .

Thank you!
