### ISSUE TITLE
How to display a waveform while recording?

### ISSUE THREAD

**Issue by atesoglu** [filoe/cscore#211]
Hello,

I'm new on recording and processing wav files and i sadly do not have any theorical background about wav files. So please forgive me if this is a little bit absurd.

My goal is to plot a waveform in real time while recording an wave file in wpf application. However i have no idea about real time data plotting using sound. And also after plotting i would like to edit (cut/paste) those bits but i think i could manage that part. Currently i'm stuck with plotting.

Could you please at least give me a direction how to start with this? Thank you in advance.

**Comment by filoe** [comment]
First of all, you need a library which supports drawing these waveforms.
There is a sample included in the cscore samples.
You can also use a 3rd party lib like
https://github.com/postacik/SoundFactory
https://github.com/filoe/cscore/issues/200

Now you need to feed the waveform with data.
A good point to start would be this sample: https://github.com/filoe/cscore/blob/master/Samples/Recorder/MainWindow.cs#L96.
It shows how to intercept samples during recording and feed them to any visualization.

**Comment by tjscience** [comment]
You could use the DynamicWaveform control from the audion framework to accomplish this, which uses cscore behind the scenes ([https://github.com/tjscience/audion](https://github.com/tjscience/audion)). It is pretty simple with just a few lines of code. Please note however, that this library is still in pre-alpha. Using it in a production application is not recommended. At a minimum it will show you how it can be done.
