### ISSUE TITLE
[Question] Disposing audio sessions

### ISSUE THREAD

**Issue by cchalm** [filoe/cscore#212]
I use CSCore in a program that manages relative volumes of audio sessions behind the scenes, but I am having some trouble with session lifetimes. My understanding of the Windows Core Audio API is that sessions exist as long as someone holds a reference to them. Using CSCore, if I hold on to an AudioSessionControl2 object, it seems to keep the session alive even when all other references to it by other programs are released. So my question is: how can I prevent my application from keeping these sessions alive? I would like to dispose of the sessions when other programs are done with them, as their volumes don't matter if no one is pushing audio through them.

I tried detecting when the process associated with an audio session ends, but access violations make me think that strategy relies on some incorrect assumptions.

I am also considering periodically releasing and re-enumerating audio sessions as a form of garbage collection, but I figured I'd ask the developer before going down that route.

Thank you for your time, and thanks for this awesome library.

**Comment by filoe** [comment]
Well, to be honest, that behaviour is new to me.
But you could register an event handler for handling disconnected sessions:
```
AudioSessionEvents events = new AudioSessionEvents();
events.SessionDisconnected += (s, e) =>
{
    //...
};
events.StateChanged += (s, e) =>
{
    //...
};
session.RegisterAudioSessionNotification(events);
```

**Comment by cchalm** [comment]
I did try that originally, but the SessionDisconnected event never fires. I also log all state changes, but those seem unrelated to session lifetime.

**Comment by cchalm** [comment]
Turns out this is a relatively obscure but known problem with the core audio APIs. sndvol.exe uses an internal interface to determine when audio sessions are no longer needed. Advice to third-party developers seems to be "good luck". Referenced [http://stackoverflow.com/questions/27848268/windows-audio-api-session-removed-notification](here [stackoverflow]) and [https://social.msdn.microsoft.com/Forums/sqlserver/en-US/59e87263-ae83-4816-b6b2-80df83242d91/re-custom-audio-endpoint-rdpendpdll-for-2008-r2?forum=windowspro-audiodevelopment](here [microsoft])

**Comment by Reintjuu** [comment]
Hey @cchalm, have you figured out why the `SessionDisconnected` event never triggers? The `SimpleVolumeChanged` on a `AudioSessionControl` works perfectly fine for me, but the disconnected one never does. All other events work perfectly fine, just as the `SessionCreated` on the `AudioSessionManager2`. I read through the links you provided but didn't get quite get how you resolved your issue.

**Comment by cchalm** [comment]
@Reintjuu unfortunately I never resolved my problem. It's been a while since I worked on this and my memory is fuzzy, but I recall deciding that it was an issue with the underlying API that I wouldn't be able to fix
