### ISSUE TITLE
Exception when loading large files

### ISSUE THREAD

**Issue by LAGonauta** [filoe/cscore#215]
Hello,

I am using latest release of the nuget package, which is 1.2.0;
While testing CSCore I noticed that large files like audiobooks (mine has 16h of audio) cannot be read. On my particular file the IWaveSource.Length was negative. This property is a "long", so maybe if it was "long long" this bug would be fixed.

I couldn't find this bug here, sorry if it was already reported or fixed.

Thanks.

**Comment by filoe** [comment]
What kind of files are you talking about? MP3, WAV,...?
How does other media players deal with it? Do they load them correctly?
I can't imagine that long is to short for a 16h track.
I've made a little calculation (see attachment).
![long](https://cloud.githubusercontent.com/assets/5208801/23413921/842d9d18-fdda-11e6-8d83-b51b1c4ae3e6.png)

**Comment by LAGonauta** [comment]
Yes, you are right. The problem might be somewhere else... I should have done the math before assuming.
The file is a 16h 38 min MP3, mono, 48 kb/s and 32 kHz.
Totaling 343MB.

Yes, other media players loads the file correctly (foobar2000, WMP, Winamp, Media Player Classic, VLC, ffplay).
I also forgot to mention that this bug also happens on the AudioPlayerSample. CSCore keeps trying to load the file and the GarbageColector is called a lot.

**Comment by filoe** [comment]
Could you please try using the `MediaFoundationDecoder`?
I would guss, this is connected to #68. 
I'm working on it, but it's a bit tricky.
