### ISSUE TITLE
How to get an internet stream and send it to multiple output devices?

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#219]
I want to get an internet stream (using FfmpegDecoder ) and write it to multiple output devices.

Because bandwidth problem , I can't create multiple instance of FfmpegDecoder to get streams.

Please tell me, how can I do that?

**Comment by filoe** [comment]
That will be a bit tricky. I'll have to think about that.

**Comment by Mitra-M** [comment]
Thank you in advance

**Comment by filoe** [comment]
I currently, don't really see a good way to do that. Maybe I'll add it as feature in the future.

**Comment by Mitra-M** [comment]
OK, Thanks.

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
