### ISSUE TITLE
Add timeout option for remote loading

### ISSUE THREAD

**Issue by Guevara-chan** [filoe/cscore#220]
So far, it seems like there is simply no way to stop `CSCore` from hanging on load of unsupported file format: 

```
CodecFactory.Instance.GetCodec(Uri("http://us1.internet-radio.com:8105/listen.pls&t=.pls"))
# Hangs for an indefinte time.
```

I guess, there should be some way to specify optional timeout for this operation, like:

```
CodecFactory.Instance.GetCodec(Uri("http://us1.internet-radio.com:8105/listen.pls&t=.pls"), 5000)
# Returns null after 5 seconds.
```

**Comment by Mitra-M** [comment]
I'm having the same problem with FfmpegDecoder .

It hangs ,when the URL address is not correct.

Please find a way to solve this problem.

**Comment by filoe** [comment]
Well, the first question has nothing to do with the comment.
In fact, the CodecFactory will be reworked with release of 1.3.
The point with the FfmpegDecoder is for me not reproduceable. 
If I enter a invalid url, there will be a `FfmpegException`. So please provide a sample to reproduce it. @Mitra-M

**Comment by Mitra-M** [comment]
That is weird.!
A few days ago I tried it was stuck on the following line:
`  int result = ffmpeg.avformat_open_input(formatContext, url, null, null);`

But today that I tried it , only about 3 seconds the UI (WPF UI) is blocked before happening the exception.

**Comment by filoe** [comment]
So, I'm gonna close this?

**Comment by Mitra-M** [comment]
Of course.
Thanks
