### ISSUE TITLE
WasapiOut.Stop() hangs eventually.

### ISSUE THREAD

**Issue by Guevara-chan** [filoe/cscore#221]
Consider following code:
```
import System
import CSCore
import CSCore.Codecs
import CSCore.SoundOut

records = (
	Uri("http://142.4.202.125:8006/128mp3"),
	Uri("http://stream.chipbit.net:8000")
	)
output	= WasapiOut()
idx		= iter = 0

while true:
	origin	= records[idx = (idx+1) % records.Length]
	stream	= MP3.Mp3WebStream(origin)
	print iter++ + ":: " + origin
	output.Initialize(stream)
	output.Play()
	Threading.Thread.Sleep(5000)
	output.Stop()
	stream.Dispose()
```

Each 5 seconds it loads new radio webstream into WasapiOut device. For 40-50 or so first iterations it works, until eventually whole process hangs silently on following line:
`output.Stop()`
Why so and what could be done ? Funnily enough, it works better if streams was created before loop:
```
import System
import CSCore
import CSCore.Codecs
import CSCore.SoundOut

records = (
	MP3.Mp3WebStream(Uri("http://142.4.202.125:8006/128mp3")),
	MP3.Mp3WebStream(Uri("http://stream.chipbit.net:8000"))
	)
output	= WasapiOut()
idx		= iter = 0

while true:
	stream	= records[idx = (idx+1) % records.Length]
	print iter++ + ":: " + stream.StreamAddress
	output.Initialize(stream)
	output.Play()
	Threading.Thread.Sleep(5000)
	output.Stop()
```
...yet, unfortunately, it doesn't work with some servers, which will simply make Mp3WebStream lose any audiodata after some iterations.

**Comment by filoe** [comment]
Have you tried using the FfmpegDecoder? 
Are you doing some further stuff? For example having some eventhandlers etc.?
