### ISSUE TITLE
How to get the FFT bins?.

### ISSUE THREAD

**Issue by VortexGator** [filoe/cscore#223]
Hi, I'e been looking through the WinformsVisualization example, and through a combination of my programming inexperience and a lack of commenting in the example, I can't figure out how to get the loudness(dB) of various frequency bins, for that matter, I can't find where the bins are being kept either.

**Comment by filoe** [comment]
Please tell me a bit more about your scenario.
What are your exact requirements? Basically, it's all about reading out samples of any stream and feed some fft calculation. The implementation depends on whether you want to do that during a playback, analyse a file,...

**Comment by VortexGator** [comment]
Well, I suppose it would be during playback.

**Comment by filoe** [comment]
Well, so you have to do 2 major steps:
Step number one, is to pick out the samples being played. See this one: https://github.com/filoe/cscore/blob/master/Samples/WinformsVisualization/Form1.cs#L130.
The event is used to process the samples.
The second step is to process the samples. In the WinformsVisualization sample, I am using the BasicSpectrumProvider class which calculates the fft bins. The rest of the sample is just rendering.
Tell me which part you have problems with to understand.

**Comment by VortexGator** [comment]
I'm not sure how the data is processed in BasicSpectrumProvider (will call BSP to shorten), from what I can tell, the event is only calling BSP.Add, and GetFftData and GetFftBandIndex are both totally unused.

**Comment by filoe** [comment]
No, the GetFftData method is used.

**Comment by VortexGator** [comment]
Where?, I find no references anywhere related to processing, just in the spectrum drawing classes.

**Comment by filoe** [comment]
For example here: https://github.com/filoe/cscore/blob/master/Samples/WinformsVisualization/Visualization/VoicePrint3DSpectrum.cs#L57

**Comment by VortexGator** [comment]
Okay, but I still don't understand how to retrieve the processed data.

**Comment by VortexGator** [comment]
I'm still not clear on how to use this, sorry, GetFftData just returns a bool doesn't it?, how is it used for getting any fft results?.

**Comment by filoe** [comment]
Just follow the sample. The method fills the passed buffer. Make sure that the passed buffer has a valid size.

**Comment by VortexGator** [comment]
Okay, so the buffer I fill in the parameter of GetFftData will be filled with the frequency bins and their volumes?.

**Comment by LucioSantinelli** [comment]
I'm trying to get fftData too from audio samples via WaveIn Class.
The samples are pretty correct, because each time i get data from WI_DataAvailable i print the maximum value of them (13.260 values) and i found that the more loud sounds i make the more is the max value.
Then i add the samples to the fftprovider, i read back the fftData but i get wrong values (inconstintent).

I also debugged your WinformsVisualization example wich prints correct values! 
But that example can't really helps me because it calculate fft from audio files and not from WaveIn (it use provider.add(left,right) and not provider.add(samples[],lenght)).

It's there a way to make it work?

some examples from my code:

`
//i used the class shown in WinformsVisualization with 2 channels, the sample rate i get from my //WaveinData and i wants 1024 fat values
spectrumProvider = new BasicSpectrumProvider(2, wf.SampleRate, FftSize.Fft1024);

//I get bytes from WaveIn and i convert them into float (2 bytes each sample)
  samples[j] = BitConverter.ToInt16(data, i);
`

Thank's and sorry for bad english.

**Comment by VortexGator** [comment]
Okay, I think I've figured out the logic of how it works in WinformsVisualization, but I'm completely lost on how to actually use it, there are so many different pieces like `BasicSpectrumProvider`, `SpectrumBase` ect interlinked and inheriting everywhere, I can't keep track of it.

How can I access the `GetFftData` method with my own code?, what additions/changes must I make?.

What I've tried so far is adding in my own method to `timer1_Tick`, so that it gets called as often as the spectrum drawers, and adding the object with the method to Form1 as a variable so that it can be accessed, however, I have no idea how to access `GetFftData` from either my own class or Form1.

**Comment by filoe** [comment]
@VortexGator: Remove all, visualizations. Declare `spectrumProvider` as public. Remove the line and voiceproint3d spectrum (see https://github.com/filoe/cscore/blob/master/Samples/WinformsVisualization/Form1.cs#L106).
In the timer, call `spectrumProvider.GetFftData`. 

@LucioSantinelli: Take a look at this code and the following lines. https://github.com/filoe/cscore/blob/master/Samples/Recorder/MainWindow.cs#L76
It shows how to get a IWaveSource of a SoundIn. The `_writer.Write` is not neccessary.

**Comment by VortexGator** [comment]
@filoe Thank you for this help, though I have 4 questions:

1. What is this syntax: fftBuffer = new float[(int)FftSize];, I don't recognise the (int) in the float declaration, what is it doing?.

2. In the FftBuffer, is there some portion of the array I'm supposed to ignore?, I recall that after processing, only half as many bins as the fft-size are full, ie Fft4096 would result in 2048 bins, is this the case in CScore?.

3. Do the frequency bins overlap?, if so, by how much?.

4. How can I convert the FftBuffer to contain decibels?.

**Comment by filoe** [comment]
1. it initializes a float array with a specific size. The FftSize is an enumeration, which is basically a collection of constant values. The (int) casts the value behind the value of the enumeration in it's integer value. See http://stackoverflow.com/questions/943398/get-int-value-from-enum

2. That's the case in cscore. Read more about it here: http://dsp.stackexchange.com/questions/4825/why-is-the-fft-mirrored

3. This may help you: http://stackoverflow.com/questions/4364823/how-do-i-obtain-the-frequencies-of-each-value-in-an-fft

4. You can try a formula like this: `20 * log(|float|)`

**Comment by VortexGator** [comment]
> You can try a formula like this: 20 * log(|float|)

Okay, I tried this, but I'm getting an error related to converting floats into doubles, I notice that in SpectrumBase, you use some `double value0`, but overall, I'm a bit lost on how this works or is applicable considering I don't need to draw anything, could you help?.

**Comment by realvictorprm** [comment]
@VortexGator I don't want to be impolite but you seem to be completely lost in the field signal processing.  I heavily suggest to learn more about it to understand why things are done in a specific way.

**Comment by VortexGator** [comment]
@realvictorprm Well, yes, my understanding of this sort of thing is very limited, but I figured that since the code already mostly exists, it would be easy enough to just get the frequency bins storing their volume in decibels, which is essentially all I need.

**Comment by realvictorprm** [comment]
The function itself returns you enough information. _Decibels_ are simply only a mapping of the linear values to log values.

**Comment by VortexGator** [comment]
@realvictorprm I understand that, and I also already knew about doing the 20*log thing to get them, but I don't know how to apply it.

Anyhow, I've gotten the code compiling, but I want to check to be sure, will this (I cast the double to float) work as intended? (convert all frequency volumes into decibel amplitude accurately).

				for (int i = 0; i < fftBuffer.Length; i++)
				{
					fftData [i] = 20 * (float)Math.Log10 (fftData [i]);
				}

**Comment by realvictorprm** [comment]
This should work if the output of the buffer is the magnitude. However keep in mind that this only maps the value on log 10.  The frequencis could be acquired like this:
```
std::vector <std::tuple<float, float>> frequencies;
float samplerate = 44100.0f;
for(int i = 0; i < fftBuffer.length; i++){
      float frequency = (float) i * (2.0f * (float)fftBuffer.length /sampleRate);
      vector.push_back(std::tuple <float, float>(fftData[i], frequency);
}
```

We need a sampleRate to calculate the correct frequencues.  Furthermore we need to map the number of values onto it but have to multpliy it with 2 simply because the function returns only half as much values as there actually would be. At least we multiply the result with I to get the frequency for each fft result and save it as tuple.

**Comment by VortexGator** [comment]
Whoa, that was fast.

First of all, the fftBuffer has been filled by the GetFftData method in CSCore, does that not already give magnitude?.

Second, by 
> This should work

Do you mean that your code snippet should work if the output of the buffer is the magnitude, or my original one works, but your snippet ensures that the output is magnitude?.

Finally, I have 0 experience with vectors, and the syntax being used here is very alien to me (std::?, tuple?), googling it mostly tells me that it's a C++ thing, the errors tell me that the alias std is not found.

**Comment by realvictorprm** [comment]
Haha like I said :smile: If you would know the basics of Signal processing you would be able to follow me. I already wrote my own FFT in Java about a year ago. Quite useful to do such stuff, you'll learn a lot.

Beside that:
1. Your code should work (maybe a conversion to double is needed in the log because the buffer values are floats)
2. The output of a classic FFT is a field of complex numbers. 
3. I haven't used the lib yet and don't know the signature of the function.  Just followed the conversation here so. To convert complex numbers to real numbers or rather to the magnitude simply Compute the magnitude of the complex number.
4. My snippet depends on that the buffer is an float array consisting of magnitude values.

PS: I think my calculation is minimal wrong, it should be:
```
float frequency = (float) i * (sampleRate / ((float) fftBuffer.length * 2);
```

**Comment by VortexGator** [comment]
> Your code should work (maybe a conversion to double is needed in the log because the buffer values are floats)

From what I can tell, Math.Log10 automatically converts them to doubles anyway.

So you're saying that my code will convert the magnitudes to decibels?, if so, was your code to show another way of going about it, or have I missed something?.

> The output of a classic FFT is a field of complex numbers.

Well, the fftBuffer doesn't contain complex numbers, but floats, so I assume that's magnitude, plus see my next response/comment.

> I haven't used the lib yet and don't know the signature of the function. Just followed the conversation here so.

Well, tying back to my last comment, this code looks to me like it's filling the fftBuffer with magnitudes (I cut out the checks for exceptions to make it clearer):

                //This method calls the magnitude maker I assume
		public virtual bool GetFftData (Complex[] fftResultBuffer)
		{
			Array.Copy (this._storedSamples, fftResultBuffer, this._storedSamples.Length);
			FastFourierTransformation.Fft (fftResultBuffer, this._fftSizeExponent, FftMode.Forward);
			bool newDataAvailable = this._newDataAvailable;
			this._newDataAvailable = false;
			return newDataAvailable;
		}
                //This is the method I call:
		public virtual bool GetFftData (float[] fftResultBuffer)
		{
			Complex[] array = new Complex[(int)this._fftSize];
			bool newDataAvailable = this._newDataAvailable;
			this.GetFftData (array);
			for (int i = 0; i < array.Length; i++) {
				fftResultBuffer [i] = array [i];
			}
			return newDataAvailable;
		}
This one I presume does the magnitudes thing?:
```
                public static void Fft (Complex[] data, int exponent, FftMode mode = FftMode.Forward)
		{
			int num = (int)Math.Pow (2, (double)exponent);
			FastFourierTransformation.Inverse (data, num);
			int num2 = 1;
			float num3 = -1;
			float num4 = 0;
			for (int i = 0; i < exponent; i++) {
				float num5 = 1;
				float num6 = 0;
				int num7 = num2;
				num2 <<= 1;
				for (int j = 0; j < num7; j++) {
					for (int k = j; k < num; k += num2) {
						int num8 = k + num7;
						float num9 = num5 * data [num8].Real - num6 * data [num8].Imaginary;
						float num10 = num5 * data [num8].Imaginary + num6 * data [num8].Real;
						data [num8].Real = data [k].Real - num9;
						data [num8].Imaginary = data [k].Imaginary - num10;
						int expr_E1_cp_1 = k;
						data [expr_E1_cp_1].Real = data [expr_E1_cp_1].Real + num9;
						int expr_F7_cp_1 = k;
						data [expr_F7_cp_1].Imaginary = data [expr_F7_cp_1].Imaginary + num10;
					}
					float num11 = num3 * num5 - num4 * num6;
					num6 = num4 * num5 + num3 * num6;
					num5 = num11;
				}
				if (mode == FftMode.Forward) {
					num4 = (float)Math.Sqrt ((double)((1 - num3) / 2));
				}
				else {
					num4 = (float)(-(float)Math.Sqrt ((double)((1 - num3) / 2)));
				}
				num3 = (float)Math.Sqrt ((double)((1 + num3) / 2));
			}
			if (mode == FftMode.Forward) {
				FastFourierTransformation.Forward (data, num);
			}
		}
```

**Comment by realvictorprm** [comment]
The last code you posted is the fft itself. The magnitude is made only in one line.

Anyway, the code I posted was the code for acquiring the frequency for each value in the fftBuffer.

A tuple is like a row of a table.

**Comment by VortexGator** [comment]
> The last code you posted is the fft itself. The magnitude is made only in one line.

Okay, so the fft code there includes the magnitude transformation?.

> Anyway, the code I posted was the code for acquiring the frequency for each value in the fftBuffer.

Ah, so it's for showing the frequency range (or at least center) of each value in fftBuffer?, meaning my code is sufficient for the decibel transformation?.

> A tuple is like a row of a table.

Okay, nice to know.

**Comment by realvictorprm** [comment]
Yes your code transforms the data into Dezibel.
Yes the fft results magnitude values.

My code only returns a table where each row describes the magnitude at a
frequency
| magnitude | frequency |

Am 31.03.2017 5:55 PM schrieb "VortexGator" <notifications@github.com>:
