### ISSUE TITLE
I am having trouble reading the audio file once it is created.

### ISSUE THREAD

**Issue by zacharysully** [filoe/cscore#225]
First off I want to thank you for all the work you have put into this project. It is much appreciated. As for my issue, I am trying to use your library as a way to read the audio that is being outputted by the computer and use it for an audio visualization app I am working on. I am mainly building this app in Unity because I want to create a 3D visualizer. My problem currently is with the reading of the audio file. I can use CScore to write the .wav file but when I try to read it in Unity, it comes up as a corrupt or missing file. This happens if I try to just open the file through my desktop after it is saved as well. Should I be able to save the file out into a normal readable form? Or is it something I can only put back into the CScore library?

**Comment by filoe** [comment]
Of course you can create a new wave file.
Make sure to dispose it properly. Does the problem still exist?

**Comment by zacharysully** [comment]
@filoe Yes, the problem is still occurring. I am not sure if I am doing anything wrong. Can you see something I am missing?

The code I am using to capture and save the wave file.
`void GetOutputAudio()
    {
        using (var wasapiCapture = new WasapiLoopbackCapture())
        {
            wasapiCapture.Initialize();
            var wasapiCaptureSource = new SoundInSource(wasapiCapture);
            using (var stereoSource = wasapiCaptureSource.ToMono())
            {
                //using (var writer = MediaFoundationEncoder.CreateWMAEncoder(stereoSource.WaveFormat, "output.wma"))
                using (var writer = new WaveWriter(@"D:\Users\Zacharysully\Documents\Unity Projects\Audio Visualization Tutorial\Assets\_Audio\output.wav", stereoSource.WaveFormat))
                {
                    byte[] buffer = new byte[stereoSource.WaveFormat.BytesPerSecond];
                    wasapiCaptureSource.DataAvailable += (s, e) =>
                    {
                        int read = stereoSource.Read(buffer, 0, buffer.Length);
                        writer.Write(buffer, 1, read);
                    };

                    wasapiCapture.Start();



                    wasapiCapture.Stop();
                }
            }
        }`

**Comment by zacharysully** [comment]
not sure why it's not formulating the code in the text correctly

**Comment by filoe** [comment]
Is there any particular reason for using a offset of `1` to write to the WaveWriter?
`writer.Write(buffer, 0, read);`

Also do you really stop wasapiCapture just right after starting it as shown in your code?

**Comment by zacharysully** [comment]
@filoe I'm not sure why the buffer is there, didn't see that. As for the stopping, I thought that I have to start, record a point of audio, then stop, and read it then apply it to the visualizer. Don't I have to Stop the recording of it in order for the audio to be readable as a .wav file? Or is there a way to continue writing it while it is being read?

**Comment by filoe** [comment]
You don't have to write it to a file. 
Just stream it in memory. 
Do something like this (of course you have to make sure that the WasapiCapture and WasapiOut are getting disposed after you don't need them anymore, etc.):
```
            var capture = new WasapiCapture();
            capture.Initialize();

            var soundInSource = new SoundInSource(capture);
            var soundOut = new WasapiOut();
            soundOut.Initialize(soundInSource);
            soundOut.Play();
```
