### ISSUE TITLE
Can't install library via NuGet in Visual Studio using the newest version of Xamarin

### ISSUE THREAD

**Issue by kWinCode** [filoe/cscore#227]
It outputs the following Error when installing the CSCore package to a blank Xamarin Forms Multi Platform Project:
	
Could not install package 'CSCore 1.2.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by filoe** [comment]
CSCore is not compatibel with Xamarin.

**Comment by kWinCode** [comment]
Ok thank you, so is there no way to get it working?

**Comment by filoe** [comment]
I'm sorry but currently it is not working.
