### ISSUE TITLE
WinformsVisualization: Release build crash "System.DllNotFoundException: openal32.dll"

### ISSUE THREAD

**Issue by VortexGator** [filoe/cscore#228]
For some reason, the debug build works perfectly well, but attempting to play a file crashes it in Release builds.

OS is Xubuntu.

**Comment by filoe** [comment]
Well, to be honest, I've got no idea. 
I've got no Xubuntu system to test it out. There should be no difference between Debug and Release. Both require the openal assemblies. 
Make sure that the CSCore.Linux.dll.config file is in the output folder.

**Comment by VortexGator** [comment]
> Make sure that the CSCore.Linux.dll.config file is in the output folder.

Ah, that was the problem.
