### ISSUE TITLE
Implementation phase inverter

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#229]
Hello,

I'm using Wasapi to capture audio.

Sometimes , I need to reverse phase of input audio (Microphone)  for some reason.

To Implement a phase inverter , each audio sample must be multiplied by minus one. (I think)

My question:  
where should I apply it?  in `ReadData `method of `WasapiCapture class` or Elsewhere?

Please Guide me.

**Comment by filoe** [comment]
Well, how does your actual setup look like?
Follow these steps:

1. Use a SoundInSource (see the [this](https://github.com/filoe/cscore/blob/master/Samples/RecordWithSpecificFormat/Program.cs) one as a sample).
2. Create a new filter based on the SampleAggregatorBase class. Override the Read method and multiply all read values by -1.
3. Place the new filter in the source chain and pull data through it. 

```
//create wasapiCapture and initialize it

var source = new SoundInSource(wasapiCapture) { FillWithZeros = false }
	.ToSampleSource()
	.AppendSource(x => new YourNewFilter(x)).
	
//pull data from source
//see https://github.com/filoe/cscore/blob/master/Samples/RecordWithSpecificFormat/Program.cs

class YourNewFilter : SampleSourceAggregator
{
	public YourNewFilter(ISampleSource source) 
		: base(source)
	{
	}

	public override Read(float[] buffer, int offset, int count)
	{
		int read = base.Read(buffer, offset, count);
		for (int i = offset; i < offset + read; i++)
		{
			buffer[i] *= -1;
		}
		return read;
	}
}
```

**Comment by Mitra-M** [comment]
It works , Excellent. Thank you very much .

dear filoe , would you please tell me :
What resources (book, web pages ,...) do I study to become proficient in programming like you?
(Especially , In the field of audio coding)

'm sorry because I asked this question in this topic.

**Comment by filoe** [comment]
Glad to hear that.
First of all, I would not call my self "proficient". It is just some kind of hobby (unfortunately I've got nearly no time for it left). I've never read any programming or audio books. It's just from trying out, reading blogs etc.
