### ISSUE TITLE
Record only one channel

### ISSUE THREAD

**Issue by JimmyAppelt** [filoe/cscore#23]
Hi,

Would it be possible to only capture 1 channel of a specific device and replay it to 2 channels (just mono)?

**Comment by filoe** [comment]
You can filter the audio signal to only take the left, right,... channel. You may show me the relevant code?

**Comment by JimmyAppelt** [comment]
I need to start coding the application @filoe 

Wasn't sure if this was possible with this library, i went trough documentation and all necessary example apps to get familiar with CSCore.

**Comment by filoe** [comment]
Ok, to clearly answer your question: yes it is possible.
