### ISSUE TITLE
_steam in MediaFoundationDecoder should be dispose

### ISSUE THREAD

**Issue by PeoLeser** [filoe/cscore#230]
However, it can be released in version 1.1.0 and works well. Here is my code
```cs
            using (var player = new MusicPlayer())
            {
                using (var mmdeviceCollection =
                    new MMDeviceEnumerator().EnumAudioEndpoints(DataFlow.Render, DeviceState.Active))
                {
                    player.Open("Test.m4a", mmdeviceCollection[0]);
                    player.Play();
                    player.Stop();
                    mmdeviceCollection[0].Dispose();
                }
            }
```
Anything wrong with me?  Looking forward to your reply.
Thanks!

**Comment by filoe** [comment]
Well, would be nice to know what's behind player.Open.

**Comment by PeoLeser** [comment]
My fault, I should point out what the player is. It's the player in Samples/AudioPlayerSample.

**Comment by PeoLeser** [comment]
I found this issue [#174](https://github.com/filoe/cscore/issues/174). Could you tell me why FileStream shouldn't be disposed after stopping the player? If it's a correct implementation, is there any way I can dispose it explicitly?

Thanks.

**Comment by filoe** [comment]
Can you test the newest commit of master branch?

**Comment by PeoLeser** [comment]
Thanks for your fix!'
And I have tested the newest master branch, the FileStream of flac, mp3 and wav can be disposed properly but if it's a m4a file, the stream still cannot be disposed. I noticed that it called AacDecoder's constructor.

**Comment by filoe** [comment]
Please give it another try.

**Comment by PeoLeser** [comment]
Excellent! It works so well now.

**Comment by filoe** [comment]
Fine. The latest nuget package is online. You can use it.
