### ISSUE TITLE
Listen to the Position with WPF

### ISSUE THREAD

**Issue by segreeeen** [filoe/cscore#232]
Hi!

It's more of a question than an issue but since there doesn't seem to be a forum or anything related, I'll ask here:
Is it possible to bind a value to the Position property? I am pretty new to C# (coming from Java) and I don't see how I can update the label to display the current position. There are no registerListener methods or anything - I guess that's different in C#?
Any help would be appreciated very much!

Best wishes,

SeGreeeeen

**Comment by tjscience** [comment]
You need to use the WPF binding system, a timer of some sort to poll for position, and also need to implement the INotifyPropertyChanged interface. I would highly recommend reading up on INotifyPropertyChanged and WPF Data Binding. Here is a sample that will do what you are asking though: 

*Note: this is not tested and was written in the github comment editor*

**Code-Behind**
```
private TimeSpan cachedPosition = TimeSpan.Zero;
private Timer _timer;

private TimeSpan position;
public TimeSpan Position
{
    get { return position; }
    set
    {
        position = value;
        NotifyPropertyChanged("Position");
    }
}

public YourClass()
{
    this.DataContext = this;
    InitializeComponent();
    _timer = new Timer(TimerTick, null, 0, 10);
}

private void TimerTick(object state)
{
    if (Position != cachedPosition)
    {
        // position has changed
        cachedPosition = Position;
        Position = _waveSource.GetPosition();
    }
}

#region INotifyPropertyChanged

 public event PropertyChangedEventHandler PropertyChanged;

 private void NotifyPropertyChanged(string propertyName)
 {
     PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
 }

#endregion
```

**XAML**
`<TextBlock Text="{Bind Position}" /> 
`

**Comment by segreeeen** [comment]
Thank you for your answer 👍 !
