### ISSUE TITLE
CSCore on Azure function 

### ISSUE THREAD

**Issue by rahulbagal** [filoe/cscore#234]
I am using cscore to read MP3 file and create an image showing waveforms for that audio. Program works perfectly on my windows 10 machine . When I deploy it to Azure function , I face following error . 

`Exception while executing function: Functions.CreateThumbnailAudio. mscorlib: Exception has been thrown by the target of an invocation. CSCore: The type initializer for 'CSCore.Codecs.CodecFactory' threw an exception. CSCore: Unable to load DLL 'mfplat.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E).`

'mfplat.dll' is part of Media Foundation ( Windows Media Player ) . I presume , this component will not be present on servers of Azure function ( it must be using some version of windows server ) 

Any suggestions to run this on windows servers  ?

**Comment by filoe** [comment]
You may try to use CSCore.Ffmpeg?

**Comment by bryfa** [comment]
It did work on Azure Functions before... why are they removed?

**Comment by filoe** [comment]
Really? Maybe the CodecFactory picks some different codecs now.
Which features did work before? I'll try to restore them.

**Comment by bryfa** [comment]
It is also possible that Microsoft removed the Media Foundation from the servers Azure Function apps run on..

**Comment by filoe** [comment]
You could use CSCore.Ffmpeg instead of MediaFoundationDecoder.
