### ISSUE TITLE
How to explicitly switch WasapiOut.Device gracefully?

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#235]
**Some context**

In next case, WasapiOut is initialized without setting its "Device" property (and by doing so, WasapiOut uses the default audio device):

```
this.soundOut = new WasapiOut(this.eventSync, this.audioClientShareMode, this.latency, ThreadPriority.Highest);
((WasapiOut)this.soundOut).StreamRoutingOptions = StreamRoutingOptions.All;
```

In the above case, when the default device changed, thanks to StreamRoutingOptions, playback is automatically switched to the new default audio device.

Now I'd like to go 1 step further and allow the user to explicitly choose a audio device from a list of available devices. The enumeration of the available audio devices works and was done using "MMDeviceEnumerator". 

WasapiOut is now initialized as such (setting the device explicitly):

```
this.soundOut = new WasapiOut(this.eventSync, this.audioClientShareMode, this.latency, ThreadPriority.Highest){Device = outputDevice};
((WasapiOut)this.soundOut).StreamRoutingOptions = StreamRoutingOptions.All;
```

**My question:**

Is it possible to change the device explicitly, while playing a file, when a user chooses another device in the enumeration? Or is it required to re-initialize WasapiOut on the newly selected device?

**Comment by filoe** [comment]
The StreamRoutingOptions provide a way to switch the device if the current device got disabled or the default device changed.
Currently switching the device without re-initializing WasapiOut is not possible.
You could adapt the WasapiOut implementation for that (quite similar to the StreamRouting) but in fact currently it is not possible.
