### ISSUE TITLE
NotImplementedException

### ISSUE THREAD

**Issue by JJtheJJpro** [filoe/cscore#236]
OK.  Here's the scoop:
I have a laser tag program that runs on "CSCore.dll".  But when I stop the program (when I exit normally), CSCore.dll throws a NullReferenceException and couldn't edit it.  I was trying really hard to figure stuff out, but the only thing I could do was kill my program every time I exit.  A couple months later I tried to not import the file but get the information from here.  But right now, my program is now throwing a NotImplementedException in the namespace "CSCore.CoreAudioAPI" in class "InteropCalls".  I easily found it but I don't know WHAT to put in the block of code.  Please help.
The first attachment is my program with "CSCore.dll".
The second attachment is my program withOUT "CSCore.dll".

[Program with DLL file.zip](https://github.com/filoe/cscore/files/978063/Program.with.DLL.file.zip)
[Program without DLL file.zip](https://github.com/filoe/cscore/files/978064/Program.without.DLL.file.zip)

**Comment by filoe** [comment]
The post compilation did not run. Clean and rebuild your solution. The CSCli program has to patch cscore.dll. Otherwise, simply use the nuget build.

**Comment by JJtheJJpro** [comment]
[Program with DLL file.zip](https://github.com/filoe/cscore/files/980402/Program.with.DLL.file.zip)
[Program without DLL file.zip](https://github.com/filoe/cscore/files/980404/Program.without.DLL.file.zip)

Cleaned and rebuilt but still does the same thing.

**Comment by filoe** [comment]
Please take a look at this https://cscore.codeplex.com/wikipage?title=Build%20CSCore&referringTitle=Documentation

**Comment by JJtheJJpro** [comment]
You know what...nevermind this question.  I'm asking a different question.

**Comment by JJtheJJpro** [comment]
GEEZ!  That took me a while.  NOW I get 1 error whenever I build or rebuild the CSCore project (it's about the building projects):

![picture](https://cloud.githubusercontent.com/assets/28423962/26333077/41f20d4c-3f18-11e7-9653-d1c80a82a3b8.png)

If you figure this out I will not bug you anymore about this.

**Comment by JJtheJJpro** [comment]
Wait a minute...are you using Windows 8???

**Comment by JJtheJJpro** [comment]
8.1 I mean?

**Comment by filoe** [comment]
That is the problem why you get the not implemented exception and so on. The command in the post build has to run after the build. 
Take a look at the output window. You should see the problem there.

**Comment by JJtheJJpro** [comment]
OK.  I see.  But just in case, I'm still going to leave this open.

**Comment by JJtheJJpro** [comment]
OK.  Here's what I did:
So in the class 'CSCore.CoreAudioAPI.MMDeviceEnumerator' I changed one little thing;
from
![capture1](https://cloud.githubusercontent.com/assets/28423962/26478001/a02ff836-4186-11e7-943c-0622d182b8c1.PNG)
to
![capture2](https://cloud.githubusercontent.com/assets/28423962/26478012/aaebe852-4186-11e7-8907-900e2cce7e68.PNG)
Now...if that is fine with you and will not affect ANYTHING, 
if that is fine with you and does not affect ANYTHING, then I'll send you the file.

I have Visual Studio 2017 and when I loaded all the files it told me that there were a lot of messages and couldn't help myself to fix them.  All the messages do is just simplify the line(s) of code.  I could give you an updated solution including the fixed messages and all warnings that are gone (that part took me a while to figure out).  So...you just have to tell me what to do.

**Comment by filoe** [comment]
Catching these exceptions is not correct. There is already on open issue for that topic, see #233. 
You may just tell me what you're trying to do? Do you even need a custom build? Do you want to adjust something?

**Comment by JJtheJJpro** [comment]
I'm trying to make my program (I was talking about earlier) work smoothly, and it looks like you didn't look at the SPECIFIED exception: "NullReferenceException", which I thought wouldn't break anything.  I don't need a custom build.  Just that file.

**Comment by JJtheJJpro** [comment]
AND if you've noticed there is a warning 'Recorder.MainWindow' in the method 'StartCapture()'

**Comment by JJtheJJpro** [comment]
HEY!!!  Wadda'ya know?  I updated EVERYthing, AND IT WORKS (without throwing any exceptions)!!!!!  THANK YOU SO MUCH!!!!1!!  You've been a great help.

**Comment by JJtheJJpro** [comment]
One more thing, why do you make the "InteropCalls" classes "invisible" to decompile applications?  This is the first reason why I posted this question.

**Comment by filoe** [comment]
Because these are just dummy methods in order to compile the assembly by msbuild.
These calls cause the compiler to build up a proper stack and call the InteropCalls dummy method.
In order to call the COM object, the `call` instruction which calls the InteropCalls method, is replaced by a `calli` instruction which calls a function at a already specified position in the memory.
If everything went right, the whole assembly should not contain ANY references to ANY InteropCalls class anymore and all the InteropCalls classes marked with the `RemoveType` attribute are getting removed.

**Comment by JJtheJJpro** [comment]
Did you update the nuget so it will build the 3.0.0.0 version of CSCore?

**Comment by JJtheJJpro** [comment]
Nevermind that question.
