### ISSUE TITLE
'CSCore.CoreAudioAPI.InteropCalls' class does NOT exist.

### ISSUE THREAD

**Issue by JJtheJJpro** [filoe/cscore#239]
Last issue was a problem with the "NotImplementedException" but now its a problem with the "NotImplementedException" INSIDE A NOT-EXISTING CLASS!!!
![problem](https://cloud.githubusercontent.com/assets/28423962/26207223/2c07c8b8-3ba4-11e7-8539-81dcbe608837.png)
NOW tell me what to do.

**Comment by JJtheJJpro** [comment]
If you can't open the file or can't see the picture it will say
"The type or namespace name 'InteropCalls' does not exist in the namespace 'CSCore.CoreAudioAPI' (are you missing an assembly reference?)"
I need help.

**Comment by filoe** [comment]
This is not reproduceable.
The class is here: https://github.com/filoe/cscore/blob/master/CSCore/CoreAudioAPI/InteropCalls.cs
You can download the latest build from nuget or read this guid on how to build cscore: https://github.com/filoe/cscore/wiki/Building-CSCore

**Comment by JJtheJJpro** [comment]
Dude.  If the class exists then the class should NOT BE THROWING AN
EXCEPTION!!!  THERE SHOULD BE SOMETHING IN IT THAT RETURNS
SOMETHING!!!!!!!!!!  I.AM.NOT.STUPID!!!!!!!!!!!!

**Comment by filoe** [comment]
"Dude", as you're not stupid, please read one of my very old articles describing whats going on there https://www.codeproject.com/Articles/644130/NET-COM-Interop-using-Postbuild

There is no reason for flaming in here.
