### ISSUE TITLE
ASIO driver

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#240]
Hi
Dear filoe , 
Unfortunately , many of sound cards and audio interfaces does not support wasapi.

Do you have plan for support Asio driver?

**Comment by filoe** [comment]
I would say all sound cards and audio interfaces support wasapi. 
Without wasapi you can't play audio on windows. 
Or am I wrong?

**Comment by Mitra-M** [comment]
I don't think so.

When an audio interface with multiple inputs and outputs are connected to a Windows machine, then:

IF it is supported wasapi, then we can see all input and output channels in "Recording devices" and "Playback devices" window. (And we can enumerate all MMDevices by cscore)

ELSE we can see ONE input and ONE output device only, And we can not enumerate all MMDevices.  (using Asio with NAudio I can full enumeration , BUT I LOVE CSCORE)

Also , In professional and commercial audio applications such cards only work with assio, and wasapi option will be disabled automatically.

**Comment by Jan-m-Dan** [comment]
Support for ASIO drivers would be very welcome since it is the choice of all pro audio card manufacturers. This would make CSCORE interesting for those developing in that realm as well.

**Comment by filoe** [comment]
Currently the priority is to target netstandard.
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.

**Comment by Mitra-M** [comment]
:(
