### ISSUE TITLE
ISoundOut Reset

### ISSUE THREAD

**Issue by royben** [filoe/cscore#241]
Hi there,

First, I want to say, this library is an amazing piece of work!
I just started using it and had a great experience so far.
I have a small issue when stopping an output device, seeking to start, then playing again, as it is causing a small sound peak/glitch. It seems like the output device contains some "left overs" buffers from the previous play.

```
 _soundOut.Stop();
 _waveSource.Seek(0);
--Wait for several seconds...
__soundOut.Play();
```

In NAudio, there is a way to "reset" the output device and clear those buffers.
Something like:
`WaveInterop.waveOutReset(hWaveOut);`

Is there any way to avoid that sound peak?

Thanks!

**Comment by filoe** [comment]
Depends on which outputprovider you are using. WasapiOut? WaveOut?

**Comment by royben** [comment]
I am using WasapiOut, but both of them gives the same result.

בתאריך 3 ביונ' 2017 10:29,‏ "Florian Rosmann" <notifications@github.com>
כתב:

**Comment by royben** [comment]
I have narrowed down the problem a little bit.

It seems like you **are** resetting the audio output device when calling Stop().
Also, the problem doesn't seems to occur when playing .wav files, but only .mp3.
So maybe there is some issue with the Mp3 decoder/reader.

**Comment by royben** [comment]
I found a workaround for this:

Write a decoded version of the mp3 to a new stream before using it.

```
            MemoryStream ms = new MemoryStream();
            MediaFoundationDecoder decoder = new MediaFoundationDecoder(filename);
            decoder.WriteToWaveStream(ms);
            ms.Position = 0;
            WaveFileReader reader = new WaveFileReader(ms);
            decoder.Dispose();
            _waveSource = reader.ToSampleSource().ToWaveSource();
```

**Comment by royben** [comment]
This also works.

```
            MediaFoundationDecoder decoder = new MediaFoundationDecoder(filename);
            _waveSource = decoder.ToSampleSource().ToWaveSource();
```

**Comment by filoe** [comment]
Do you've got a sample which reproduces the issue? What does your source chain look like?

**Comment by royben** [comment]
You can reproduce the issue by using the AudioPlayerSample included in the solution.

1. Pick an Mp3 file.
2. Play.
3. Stop playing in the middle.
4. Play again. You should hear a sound glitch.

One more thing is in my workaround, I am using WaveOut with 100ms latency.

I think the issue could be associated with the fact that after calling Stop, the source chain still gets a few calls to the Read method.
I noticed that while implementing a custom SampleAggregatorBase.

**Comment by filoe** [comment]
I'll have a look at it.

**Comment by filoe** [comment]
Sorry for the late response.
Wasn't able to check that.
What I've tried:

1. I've pulled the latest version of the repository.
2. Started the AudioPlayerSample
3. Opened any mp3. The decoder that was used is the `DmoMp3Decoder`.
4. Played the file
5. Clicked Stop in the middle of the track
6. Opened the same mp3 again and clicked play again => can't hear any noise

Am I missing something?

**Comment by royben** [comment]
I think the problem is with step 6.
Do not open the file again as you are re-initializing the whole chain.
Just stop, then play again.

**Comment by snalesso** [comment]
@royben I was curious and took a look at the issue you're pointing out: you wrote

> Do not open the file again as you are re-initializing the whole chain.
Just stop, then play again.

it's not possible: in CSCore.Samples.AudioPlayerSample, after you clicked the "Stop" button, you can't "Play" again since it's disabled.

@filoe I think you can reproduce what @royben meant by replacing

	private void btnStop_Click(object sender, EventArgs e)
	{
		if (_musicPlayer.PlaybackState != PlaybackState.Stopped)
		{
			_musicPlayer.Stop();
			btnStop.Enabled = btnPause.Enabled = false;
			btnPlay.Enabled = true;
		}
	}

in Form1.cs's  code behind, and doing:

1. Open
2. Play
3. Get somewhere in the track by letting it play or using the slider
4. Stop
5. Set playback at 00:00 using the slider
6. Play (and notice the "blip")

**Comment by ArizonaInkStudios** [comment]
I too am hearing the "blip" that is being discussed. Doing a simple test, as follows, allows you to hear it. Even without the resetting of the time back to zero, you can hear it. Please note, the start and stop are in different functions and are being called from button presses. You get the idea. Let me know if I can help!

```
public function Main()
{
    var fileName = "music.mp3";
    IWaveSource waveSource = CodecFactory.Instance
                .GetCodec(fileName)
                .ToSampleSource()
                .ToStereo()
                .ToWaveSource();

    WasapiOut soundOut = new WasapiOut()
    {
        Latency = 100,
        Device = devices[2]
    };

    soundOut.Initialize(waveSource);
}

public void Start()
{
    soundOut.Play();
}

public void Stop()
{
    soundOut.Stop();
    waveSource.SetPosition(TimeSpan.Zero);
}
```

**Comment by filoe** [comment]
I've had a look at it.
Could not reproduce the behaviour described by @snalesso.
Converting it to a wave stream first, did not solve the issue.
Was searching over and over but I could not find a solution for wasapi. 
I'm resetting the audioclient as msdn describes.

**Comment by ArizonaInkStudios** [comment]
My way of solving this is when I stop the audio source from playing, I just reload the file. It may seem like a brute force approach, but it works well and causes very little overhead.
