### ISSUE TITLE
Is it possible to compile cscore for .NetFramework 2/3?

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#242]
I want to use cscore for old windows. (XP /2003)

I know that the wasapi and coreaudio there are not in WinXP , but I need to your waveout/directsound wrapper and other features of cscore for XP , Is it possible to compile cscore for .NetFramework 3.0 (or 2) ?

**Comment by filoe** [comment]
To be honest, I've never tried. It is written for .net 3.5.
The best you can do is to try it out.

**Comment by JJtheJJpro** [comment]
This sounds interesting.  I might give it a try; right now I'm reinstalling visual studio.

**Comment by Mitra-M** [comment]
I want to use the CSCore.Ffmpeg in legacy systems.

The cscore was compiled for .NetFramework  2 and 3  , After resolving a few errors.

But it seems the ffmpeg Library files are not compatible with XP.    :(

I could not find the ffmpeg shared Libraries version 3.2 that is compatible with XP 32bit and the CSCore.Ffmpeg.   :(

any help?

**Comment by Mitra-M** [comment]
I was wrong.
Now,I think the shared ffmpeg library is OK , Because when the CSCore.Ffmpeg compiled in x86 mode,  this unhandled exception occurs at run time:
![error](https://user-images.githubusercontent.com/17668160/26965306-fd768aae-4ca9-11e7-8fce-37fbd05e77ac.jpg)
Also, when the CSCore.Ffmpeg compiled in AnyCpu mode, the above unhandled exception occurs at run time.

It seems the CSCore.Ffmpeg can not be used for XP.
At least I can not compile it correctly.

**Comment by JJtheJJpro** [comment]
XP is pretty old.
