### ISSUE TITLE
DataAvailable event when playing audio file.

### ISSUE THREAD

**Issue by royben** [filoe/cscore#243]
When using **ISoundIn**, I have a nice **DataAvailable** event which I can use to save to a file, transfer over the network, and also push to **WriteableBufferingSource** (Write accepts only byte array).

What if I want to stream an audio file over the network or anything else? I there a way of delivering this event for WaveSource/SampleSource ?

I managed to produce similar event but with float array by inheriting from SampleAggregatorBase. But I want to deliver byte array.

This is my SampleAggregator.

```
    public class AudioDataSource : SampleAggregatorBase
    {
        public event EventHandler<float[]> DataAvailable;

        public AudioDataSource(ISampleSource source)
            : base(source)
        {

        }

        public override int Read(float[] buffer, int offset, int count)
        {
            int read = base.Read(buffer, offset, count);

            if (DataAvailable != null)
            {
                DataAvailable(this, buffer);
            }

            return read;
        }
    }
```

Thanks,

**Comment by filoe** [comment]
You may want to wrap a `SoundInSource` around it.
Maybe something like this:
```
var soundIn = new WasapiCapture()
...

var soundInSource = new SoundInSource();
var sampleSource = soundInSource.ToSampleSource();

soundInSource.DataAvailable += (s, e) => 
{
	sampleSource.Read( ... )
	//send read samples over network??
};
```

**Comment by royben** [comment]
SoundInSource can be initialized only with ISoundIn. How can I initialize it with wave/sample source?
Your sample, again, demonstrates how could a capture device might be streamed, not an audio file.

**Comment by filoe** [comment]
Ok, now I've got you. 
You want to stream a file the same way as you stream a microphone.
You can just constantly call the `Read` method of the source to read data from it.

**Comment by royben** [comment]
Actually what I have done is to implement SampleAggregatorBase with an event for delivering audio data. Then I override the Read method and raising the event every time the Read is being called along with the audio data. I called it AudioDataSource. I can connect it anywhere in the chain and it works. Actually that is very essential if you want to record an audio stream+DmoEffect to some file.

**Comment by filoe** [comment]
Well, you still have to trigger the read processing somewhere. 
So where are you trigger the Read method?

**Comment by royben** [comment]
Example Chain:

IWaveSource -> PeakMeter -> ReverbDmo -> AudioDataAggregator -> ISoundOut.

When connecting the AudioDataAggregator, the Read method will be called because it is part of the chain.

This is the AudioDataAggregator class:
`
    /// <summary>
    /// Represents an audio aggregation for delivering audio data from the audio chain.
    /// </summary>
    /// <seealso cref="CSCore.SampleAggregatorBase" />
    internal class AudioDataAggregator : SampleAggregatorBase
    {
        private static int counter = 0;
        private int index;

        /// <summary>
        /// Occurs when the data available.
        /// </summary>
        public event EventHandler<AudioReceivedEventArgs> DataAvailable;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="AudioDataAggregator"/> is enable.
        /// </summary>
        public bool Enable { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AudioDataAggregator"/> class.
        /// </summary>
        /// <param name="source">Underlying base source which provides audio data.</param>
        public AudioDataAggregator(ISampleSource source)
            : base(source)
        {
            index = counter++;
        }

        /// <summary>
        /// Reads a sequence of samples from the <see cref="T:CSCore.SampleAggregatorBase" /> and advances the position within the stream by
        /// the number of samples read.
        /// </summary>
        /// <param name="buffer">An array of floats. When this method returns, the <paramref name="buffer" /> contains the specified
        /// float array with the values between <paramref name="offset" /> and (<paramref name="offset" /> +
        /// <paramref name="count" /> - 1) replaced by the floats read from the current source.</param>
        /// <param name="offset">The zero-based offset in the <paramref name="buffer" /> at which to begin storing the data
        /// read from the current stream.</param>
        /// <param name="count">The maximum number of samples to read from the current source.</param>
        /// <returns>
        /// The total number of samples read into the buffer.
        /// </returns>
        public override int Read(float[] buffer, int offset, int count)
        {
            try
            {
                int read = base.Read(buffer, offset, count);

                if (DataAvailable != null && Enable)
                {
                    DataAvailable(this, new AudioReceivedEventArgs(buffer, offset, count));
                }

                return read;
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException("Failed on AudioData " + index, ex);
            }
        }
    }
`

Then I can register to the event from anywhere and write the resulting stream using WaveWriter.WriteSamples

**Comment by filoe** [comment]
Seems to be quite similar to this one :-) https://github.com/filoe/cscore/blob/master/CSCore/Streams/NotificationSource.cs

**Comment by royben** [comment]
Yes, even better -)
