### ISSUE TITLE
Building is VS 2017 and getting NotImplementedException in InteropCalls

### ISSUE THREAD

**Issue by robbyxp1** [filoe/cscore#244]
Hi,

Tried both the master and the .zip of 1.2 source.  Installed .net 3.5 on win10.

Selected AudioPlayerSample and built it. When run, its ending up in interopcalls.cs where all the members are marked as not implemented.

I've got this to work last year, in VS2015 on win7.

What silly thing am I doing wrong?

**Comment by robbyxp1** [comment]
Okay seeing i'm missing netfx 4.5.1 tools

**Comment by filoe** [comment]
Maybe related to #236 #239?

**Comment by JJtheJJpro** [comment]
This should close since it's done being solved

**Comment by robbyxp1** [comment]
Thanks! It builds, debugs fine using the 10.0A tools btw.  Imported the dll directly into my project and everything is fine, the project is .net 4.6.

**Comment by bellicapax** [comment]
Same problem, same fix. Why isn't there anything about this build events assumption in this [How To Build doc](https://github.com/filoe/cscore/wiki/Building-CSCore) explaining other problems with Visual Studio 2017?
