### ISSUE TITLE
crash in RegisterAudioSessionNotificationNative, when caching AudioSessionManager2

### ISSUE THREAD

**Issue by jeske** [filoe/cscore#245]
I'm seeing `AccessViolationException` in `RegisterAudioSessionNotificationNative` in `CSCore\CoreAudioAPI\AudioSessionControl.cs` in a sound level monitoring app.

It happens when I try to save around and reuse an AudioSessionManager2, instead of creating one every timer tick.

The source code for both versions of the app is here:

https://github.com/jeske/SoundLevelMonitor

![image](https://user-images.githubusercontent.com/15093/26990644-30b363a8-4d0c-11e7-9f8f-797fd3f0be5f.png)

Presumably if it returns null something went wrong, but I don't know what this is calling, so I don't know the right way to fix it.

**Comment by filoe** [comment]
Is there a chance to reproduce it?

**Comment by jeske** [comment]
Yes, here is a pretty simple example app which will reproduce it.. There is a Windows.Forms and WPF version of the same app. For some reason the WPF app triggers the bug more often, but they both trigger it. Just run the WPF version, play some music in the background, and usually it'll hit this bug in a minute or two.

https://github.com/jeske/SoundLevelMonitor/tree/crash_coreaudio

**Comment by JJtheJJpro** [comment]
This happened to me one time but now it's fine.

**Comment by jeske** [comment]
For me it happens every minute or so.. Though I usually run both the WF and WPF versions of the app simultaneously when I'm testing, so maybe that has an effect? 

As a workaround I just went back to creating the AudioSessionManager2 every timer-tick, but this feels very heavy weight, and seems like something I probably shouldn't be doing.

**Comment by jeske** [comment]
What is the [10] indexing?

**Comment by JJtheJJpro** [comment]
In the first picture, it did say, "This is often an indication that other memory is corrupt."  Maybe check to see if there is memory corrupt.  See [this](http://www.online-tech-tips.com/computer-tips/check-for-bad-memory/).

**Comment by jeske** [comment]
Did you not say it happened to you also?  This is not a problem with my machine's memory.

CSCore is the only native stuff in my simple sample app, so if something is corrupting memory, it is the most likely culpret.

**Comment by filoe** [comment]
I will have a look at this.

**Comment by filoe** [comment]
Ok, that was a tricky one.
Dispose the `session` and the `sessionEnumerator`.
Anyone got any suggestions on how to restructure the classes to avoid this error in the future?
