### ISSUE TITLE
Ffmpeg Based Resampler

### ISSUE THREAD

**Issue by KuroThing** [filoe/cscore#246]
It would be awesome to get a Ffmpeg Based Resampler, so that conversions of files could be done entirely within Ffmpeg.

It would be even more amazing if the CSCore.Ffmpeg library was to become a .Net Standard library since conversion wise it would be completely standalone (Due to Ffmpeg being cross platform itself)

**Comment by iamcarbon** [comment]
Also working on using cscore in a Linux project.

Would be great to see the entire MediaFoundation layer be abstracted in the same way as FFmpeg is see these co-evolve to support both platforms.

**Comment by filoe** [comment]
We'll cover this up in #288.
