### ISSUE TITLE
Extract FLAC metadata from file

### ISSUE THREAD

**Issue by shelland** [filoe/cscore#247]
Hello, thanks for the great library!

I'm trying to extract FLAC metadata (title, artist, etc.) from file, but i'm confused about current FlacMetadata class. My code is pretty simple:

```
var flacFile = new FlacFile("Track.flac");
var meta = flacFile.Metadata.FirstOrDefault(x => x.MetaDataType == FlacMetaDataType.VorbisComment);
```

Meta variable is not null, but i don't see any properties there except of some base fields like Type, LastBlock and so on. What should i do next with this metadata object to get actual information from file? Should i deal maybe with ID3 tags or something else? Should i use other libraries like TagLibSharp to extract metainfo?

Thanks in advance.

**Comment by filoe** [comment]
There is currently no implementation for vorbis comment.
You can implement if yourself if needed and register it by using the FlacMetadataFactory (see adebdef2110287243ac5f584d21515c690d27c59).
