### ISSUE TITLE
Crash when dispose or stop ISoundOut

### ISSUE THREAD

**Issue by festelo** [filoe/cscore#248]
Vesion - last from nuget (21 June 2017).
OS - Win10
Code:
`
            try
            {
                soundSource = GetSoundSource(path);
                soundOut = GetSoundOut();
                soundOut.Initialize(soundSource);
                soundOut.Play();
                while (!(soundOut.WaitForStopped(15) || _manualstopped)) { }
                soundOut.Stop(); // Crash here
                return !_manualstopped;
            }
            finally
            {
            }
`
or

`
            try
            {
                soundSource = GetSoundSource(path);
                soundOut = GetSoundOut();
                soundOut.Initialize(soundSource);
                soundOut.Play();
                while (!(soundOut.WaitForStopped(15) || _manualstopped)) { }
                return !_manualstopped;
            }
            finally
            {
                  soundOut.Dispose(); //crash here
            }
`
or
`
            using (var soundSource = GetSoundSource(path))
            {
                   using (soundOut = GetSoundOut())
                   {
                soundOut.Initialize(soundSource);
                soundOut.Play();
                while (!(soundOut.WaitForStopped(15) || _manualstopped)) { }
                return !_manualstopped;
                  } //crash here
            } //or here
`
path - path to mp3 file.

**Comment by festelo** [comment]
I can't write normal code, sorry. https://pastebin.com/88zEFUfb

**Comment by filoe** [comment]
Which soundOut are you using?
Could you may post the stacktrace of the exception?

**Comment by festelo** [comment]
>Could you may post the stacktrace of the exception?
Now, I can't. Debugging just pause and in debug console appear message "Dispose exception in mscorlib.dll".

>Which soundOut are you using?
I get soundOut from GetSoundOut method:
https://cscore.codeplex.com/wikipage?title=Play%20a%20sound&referringTitle=Documentation

My code - part of async task method.

**Comment by Seed122** [comment]
This problem was because you called WaitForStopped(15).
This solution works: https://github.com/filoe/cscore/pull/287
