### ISSUE TITLE
CodecFactory stream usage and closing of file stream

### ISSUE THREAD

**Issue by robbyxp1** [filoe/cscore#249]
1) I've noticed that the MP3 file opened is not closed when the IWaveSource is disposed of.  The closing of the stream is delayed until the program terminates.  I would prefer a method to cause the stream to be closed at the iwavesource.Dispose() point.

2) When grabbing a MP3 codec using..
                IWaveSource s = CSCore.Codecs.CodecFactory.Instance.GetCodec(file);

I notice at codecfactory.cs that it does at 163:
          source = codecEntry.Value.GetCodecAction(File.OpenRead(filename));

Surely this should be:
          source = codecEntry.Value.GetCodecAction(stream);

using the stream thats just been opened at 152?

**Comment by Bahaatya** [comment]
@robbyxp1 That's true, and this cause an IOException when you try to modify the file (let's say when trying to update its tags) and the error happens even after stopping it from being played and making the sources null;
even there's a manual method to play the file and loop inside the codecs, I tried it but in vain, still the file is being used and locked to CSCore library, unless you terminate the whole application!

Hope somebody gets solution soon to this serious problem.

**Comment by filoe** [comment]
Thanks for reporting!
I've just fixed it according your suggestion.
