### ISSUE TITLE
Execution in Windows Service not working

### ISSUE THREAD

**Issue by NicolasConstant** [filoe/cscore#25]
I am executing your library in a windows service and I get the same issue described here: http://stackoverflow.com/questions/32155412/cscore-not-working-in-a-windows-service

Is CSCore not compatible with a service execution?

**Comment by filoe** [comment]
Windows Services are quite restricted. You're not allowed to interact with the user in any way,...
I could imagine, that this also includes that you're not allowed to access audio api's. Are you also trying to use AudioSession APIs? The only thing you could try, would be to write a native services, using the native COM objects and try whether you can use them. But I would definitely guess NOT.

**Comment by NicolasConstant** [comment]
Ok, thanks. I rolled back to a desktop app.
