### ISSUE TITLE
CSCore Equalizer Processor Quality

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#251]
Hi,
There's noticeable difference between the Equalizer of the normal and famous applications (like Winamp, AIMP, GOM, and Window Media Player) and the equalizer that's presented by CSCore... 
All of these apps are 10 EQ. Trackbars starting from 16k ending by 31/32b... but the equalizer sounds better and more efficient with the mentions applications rather than with the CSCore based applications.
With CSCore Equalizer you feel the 2k, 4k, 8k, and 16k having the same effects (which is 16k)!
I made sure that the indices are correct when giving the equalizer with the values, however the equalizer works with each Trackbar control, but results in a very poor voice [because the 2k, 4k, 8k, and 16k having the same effects (which is 16k)]
With Winamp for example, the voice is far better, you feel the strong effects of 2k, 4k, and 8k which make the voice comforting to the ears.

What I'm saying could be noticed easily if you play the same file on Winamp at a time, and on CSCore based application at a time (with the same values of each Equalizer button).

One last thing is that, I made sure to make the SampleRate at 44100, and even 48000, but in vain, so no this is not the point.

Please review this problem and make test to get us with fixes to this poor quality.

Thanks in advance.

**Comment by Bahaatya** [comment]
Alright, Thanks for anyone was intend to answer... I found a solution.

**Comment by filoe** [comment]
You may share your solution with us?

**Comment by Bahaatya** [comment]
@filoe 
One of the solutions is to higher the trackbars Maximum values of all Equalizer bands (say 24 as max values)
then when giving the the values of trackbars of 16k and 8k I devide the values (of only 16k and 8k) into 1.5f to make their effects lower than others.

it seems somehow odd solution, but it works and gives better quality results!

**Comment by Bahaatya** [comment]
@filoe 
One of the solutions is to higher the trackbars Maximum values of all Equalizer bands (say 24 as max values)
then when giving the the values of trackbars of 16k and 8k I devide the values (of only 16k and 8k) into 1.5f to make their effects lower than others.

it seems somehow odd solution, but it works and gives better quality results!
