### ISSUE TITLE
CSCore versions

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#252]
by chance I saw this [page that titled with CSCore 1.3](https://github.com/filoe/cscore/milestone/5)
I was thinking that yet we're in 1.2.1.1 or so, then is there such new version 1.3 available? 
If "Yes" then where is it? and why it's not declared? and what's new in the new version?

Thanks in advance.

**Comment by snalesso** [comment]
You clicked on the "Milestones" tab. Take a look at the ["Milestone" definition on Wikipedia](https://en.wikipedia.org/wiki/Milestone_(project_management))

Notice the 

> Due by June 30, 2017

and the

> 30% complete

under

> CSCore 1.3 release
