### ISSUE TITLE
NullReferenceException in ComObject finalizer on Windows 7

### ISSUE THREAD

**Issue by spellizzari** [filoe/cscore#253]
We encountered a bug while using the XAudio wrapper in CSCore in a .NET 4.6 application on Windows 7. Sometimes the application would crash because of a `NullReferenceException` in the finalizer of `ComObject`: the field `_lockObj` is null and the lock operator throws the exception.

It is legal for the GC to collect some objects before others during finalization, thus making some references invalid when a particular finalizer is invoked. As a consequence, it must be expected for `_lockObj` to be null sometimes.

One solution would be to check for a null reference and skip the lock completely in such case. But looking at the code of class `ComObject`, I think the synchronization between the public `Dispose()` method and the finalizer is unnecessary: the public `Dispose()` method will never be called by the GC thread (as it's not invoked by the finalizer code), and if any living thread is calling `Dispose()` on a `ComObject`, there's no chance the finalizer would start executing at the same time because the `Dispose()` method itself retains a reference to `this` until the end of its execution (for the call to `GC.SuppressFinalize`), thus preventing the GC from collecting the `ComObject` instance. Therefore, I think the lock inside the finalizer could be removed completely.

**Comment by filoe** [comment]
Thanks for reporting! Should be fixed.
