### ISSUE TITLE
Microphone boost & Audio Live Streams

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#254]
Hi Filoe @
I came across a point where I need to control the _sounInSource Volume and I succeed to do it from the example given in other issues, but When the CaptureMode is set to Capture (which means to listen to the Microphone) if I use the _sounInSource.Volume = ... it controls the level of the given General boost level of the mic, (it's like controlling the volume level of the app only we're working on, not the Microphone General Mixer).
**So, how to control the Mic boost level to affect the general Mixer of the Mic for all the System?**

Second question is based on the null result on my search on the internet including here... I'm looking for a method or code examples to show how to make live Audio stream to online servers, like any mp3 Radio servers hosting that's available on the internet (or YouTube Live stream which I think it has a different protocol and almost will require a new integration of Codecs to add into CSCore library)... 
**So the question about this is How to make Live Radio Streamer App to stream file to an online server?**

Thanks in advance for any help

**Comment by filoe** [comment]
You can change the volume of the microphone by using the following snipped:
```
            var device = MMDeviceEnumerator.DefaultAudioEndpoint(DataFlow.Capture, Role.Multimedia);
            var endpointVolume = AudioEndpointVolume.FromDevice(device);
            endpointVolume.MasterVolumeLevelScalar = 0.0f;
```
Implementing a audio streaming server is not the scope of cscore.
CSCore provides the tools for capturing audio, mixing audio and so on. But sending audio via http server is not part of cscore. If you plan to implement it, would be interesting to see your solution.

**Comment by Bahaatya** [comment]
Hello filoe
Thanks for your great efforts in CSCore in general and in supporting its fans here
The above code works fine but for the Microphone Level only, is there any further step/code to control the Microphone Boost? Please see the below picture:

![bahaasshot_9](https://user-images.githubusercontent.com/7080504/27985970-2cfbbaa4-6408-11e7-8fb3-566cce60079c.png)

Thanks in advance

**Comment by filoe** [comment]
I could not find any apis for it. I'm sorry.

**Comment by Bahaatya** [comment]
No problem, thanks anyway filoe...
I would keep looking into this point as well as streaming files into Radio Servers and will keep in touch here to let you know if there's any results in these issues

Thanks again
