### ISSUE TITLE
Decoding Multi-Channel stem Files

### ISSUE THREAD

**Issue by hyperion51** [filoe/cscore#255]
Greetings,

I've been desperately searching for an audio framework that can open [stem files](http://www.stems-music.com/), which are mp4 containers containing 5 stereo audio files. The first is the stereo master and this is what CSCore decodes using CodecFactory.Instance.GetCodec(filename) as per the MusicPlayer sample. But codec.WaveFormat.Channels returns 2, indicating that CSCore did not find the remaining 8 channels in the file.

The point of using stems is for note onset and fundamental pitch detection to return clean results specific to the instrumentation of the song. Polyphonic feature detection is not reliable enough yet on mastered music, but analyzing stems instead with even simple algorithms has [great results](https://www.youtube.com/watch?v=osUCa383hSg).

Therefore, I don't actually need to play back anything but the master, but I do need to be able to get samples from the stem tracks for feature detection.

What do?

Attached is a sample .stem.mp4 file from the [Native Instruments free stem pack](https://www.native-instruments.com/en/specials/stems-for-all/free-stems-tracks/).

[CG_JaesGroove.stem.mp4.zip](https://github.com/filoe/cscore/files/1133004/CG_JaesGroove.stem.mp4.zip)

**Comment by filoe** [comment]
Well, the media foundation decoder detects 5 streams within the media foundation source.
The cscore implementation just decodes the first audio audio stream.
You could modify the `MediaFoundationDecoder` to allow decoding the other streams and provide the additonal data of the other streams by an event.

**Comment by hyperion51** [comment]
Looks like MF_SOURCE_READER_FIRST_AUDIO_STREAM has a brother named MF_SOURCE_READER_ALL_STREAMS, but a bit of naive substitution in MediaFoundationDecoder.cs does not seem to be enough. Like if I pass that to SetCurrentMediaType it complains that "The stream number provided was invalid".

Ideally the extra channels would just be IWaveSources like everything else in CSCore, but you're talking about hacking in an event hook to get samples from the other channels? Doesn't that defeat CSCore's whole architecture?

Man, it'd be really cool if you could support this feature. I haven't the foggiest what I'm doing when it comes to dealing with Media Foundation or native audio in general, honestly that's why I'm using an audio library.

**Comment by filoe** [comment]
Well, as you've said, only the master has to be played. 
So if the WaveSource itself returns the data, it will be played.

**Comment by hyperion51** [comment]
Right, but CSCore seems to have the ability to split and redirect streams. I was planning to do all of my audio analysis in realtime using CSCore as well, with each stem stream going through an FFT stage - most feature extraction algorithms start with FFT. This should naturally result in the extracted audio features being perfectly aligned with the master. The only difference is that samples coming from the stems don't need to be output to the speakers.

I see that you're using a SingleBlockNotificationStream to accomplish this in your WinformsVisualization sample. That seems like a great way to go.

**Comment by filoe** [comment]
I know what you mean. But I'm sorry. I currently see no chance to implement it. 
You would need to write a mp4 parser first in order to read to right atoms. 
I could not find a way using media foundation or ffmpeg.

**Comment by hyperion51** [comment]
Wait, you saying that sounds like you made the attempt. Are you saying that even with your expertise, you couldn't find a way to decode the extra audio channels in an .mp4 container? With either media foundation or ffmpeg? That sure doesn't give me much hope towards finding a solution myself...

**Comment by filoe** [comment]
Well, yes. Decoding the streams is not the problem.
Decoding the json stored in the header is the problem.
I don't wanne write a m4a decoder myself. Decoding the header as specified can be a bit tricky. I've never done that.
