### ISSUE TITLE
VoiceCallback potential memory leak

### ISSUE THREAD

**Issue by giangregorio** [filoe/cscore#257]
Win10, CsCore 1.2 or latest source, XAudio2

Every time `CreateSourceVoiceNative` contained in **XAudio2_8.cs** is called, a new istance of `VoiceCallback` class seems to leak.

I think the problem is related to `GetComInterfaceForObjectWithAdjustedVtable` , if the element is not inserted in `_patchedVtables` , no one will release it.
I have some doubt about `Release` method too, it searches for the IntPtr returned by `GetComInterfaceForObjectWithAdjustedVtable`, but it doesn't seems the same IntPtr inserted in  `_patchedVtables`.

Thanks for your time and for your work

**Comment by filoe** [comment]
Do you have any code to reproduce it?

**Comment by giangregorio** [comment]
Something like that should be enough:

```
xaudio2 = XAudio2.CreateXAudio2();
xaudio2.CreateMasteringVoice();

for (int i = 0; i < 100; i++)
  using (var source = CodecFactory.Instance.GetCodec("c:/a.mp3"))
     using (StreamingSourceVoice voice = new StreamingSourceVoice(xaudio2, source))
     {
       StreamingSourceVoiceListener.Default.Add(voice);
       voice.Start();
       voice.Stop();
       StreamingSourceVoiceListener.Default.Remove(voice);
     }
```

As a results, 100 RefCounted GCHandle of CSCore.XAudio2.VoiceCallback are still alive.

**Comment by filoe** [comment]
Wow, that was a tricky one. I'm glad you've found that bug. I have to honest, I would never find it 👍

**Comment by giangregorio** [comment]
Seems ok now. Thanks for your time.
