### ISSUE TITLE
Apply effects (e.g. echo, pitch, delay) to radio stream

### ISSUE THREAD

**Issue by fred87lim** [filoe/cscore#258]
Hello. I like to know how I can apply audio effects on a radio stream. I looked through the sample program and I found out that I can use the following code:

IWaveSource ffmpegDecoder= FfmpegDecoder(<stream_url>)
WasapiOut wasapiOut= new WasapiOut();
wasapiOut.Initialise(ffmpegDecoder);
wasapiOut.Play();

to play the radio stream. I see there is an echo effect "DmoEchoEffect" but I don't know how I can apply this effect (and if possible, a few effects concurrently) to the radio stream. Is that possible?

**Comment by filoe** [comment]
Try the following:

```
IWaveSource ffmpegDecoder= FfmpegDecoder(<stream_url>)
var echoEffect = new DmoEchoEffect(ffmpegDecoder);
WasapiOut wasapiOut= new WasapiOut();
wasapiOut.Initialise(echoEffect);
wasapiOut.Play();		

//OR
var source = FfmpegDecoder(<stream_url>)
	.AppendSource(x => new DmoEchoEffect(x));
WasapiOut wasapiOut= new WasapiOut();
wasapiOut.Initialise(source);
wasapiOut.Play();		
```

**Comment by fred87lim** [comment]
Thanks filoe. Both of your code worked! 

Actually I did try initializing the WasapiOut with the echoeffect, but I wrote the code as follow - 
`using (var echoSource = new DmoEchoEffect(ffmpegDecoder))
{
   wasapiOut.Initialize(ffmpegDecoder);
}
wasapiOut.Play();`

but it doesn't work. I used the "using(var...)" block because I was looking through the Samples->PlayInputDeviceSample project and I saw it being used in that manner. I'm glad it's working with the code you have given.

Can I check if it is possible to change the echoEffect's variables such as feedback, LeftDelay and etc during runtime? 
I tried - 
`DmoEchoEffect echoEffect = new DmoEchoEffect(ffmpegDecoder);
ffmpegDecoder.AppendSource(x => echoEffect);`

but the echo effect is not working.

**Comment by filoe** [comment]
Of course it is possible to change the properties of the effects at runtime.
```
IWaveSource ffmpegDecoder= FfmpegDecoder(<stream_url>)
var echoEffect = new DmoEchoEffect(ffmpegDecoder);
WasapiOut wasapiOut= new WasapiOut();
wasapiOut.Initialise(echoEffect);
wasapiOut.Play();	

echoEffect.LeftDelay = ...

```
