### ISSUE TITLE
Using current version in project

### ISSUE THREAD

**Issue by dwebb7** [filoe/cscore#26]
Thanks for fixing the DmoWavesReverbEffect! I'm having trouble using it. I downloaded the zipfile and built the project in Visual Studio 2013 and referenced the dll created by the build in my project. Now I get no audio. When I switch back to the NuGet version I get audio again. What am I doing wrong?

**Comment by filoe** [comment]
Please provide some additional information. Code, errornessages, behaviour,...

**Comment by dwebb7** [comment]
If I use the following code with the NuGet package I hear my mic. If i use the same code with cscore I compiled from here I hear nothing. There is no error it just doesn't play sound.

```C#
        public MainWindow()
        {
            InitializeComponent();
            WasapiCapture wasapiCapture = new WasapiCapture();
            wasapiCapture.Initialize();
            var wasapiCaptureSource = new SoundInSource(wasapiCapture);
            WasapiOut wasapiOut = new WasapiOut();
            wasapiCapture.Start();
            wasapiOut.Initialize(wasapiCaptureSource);
            wasapiOut.Play();
        }
```
Thanks

**Comment by dwebb7** [comment]
Ok, here is what I found out. If I add a Thread.Sleep(100); before I play the wasapiOut it works fine. I guess the WasipiCapture isn't finished initializing yet when the play is called so it fails. No error though.
This will work fine for me because the wasipiOut is going to be controlled by an button in my application so the capture will be done long before the user clicks the button.

Thanks

**Comment by filoe** [comment]
The solution to use Thread.Sleep is not intended. I'm going to have a look at it.

**Comment by filoe** [comment]
I'm sorry for the late answer. 
Try setting FillWithZeros Property to true: https://github.com/filoe/cscore/blob/master/CSCore.Test/RecentIssueTests/SoundInToSoundOutTests.cs#L22

**Comment by dwebb7** [comment]
This fixed it (and some other issues I created by using Thread.Sleep). Thank you so much!!
