### ISSUE TITLE
Access to WasapiOut ISampleSource

### ISSUE THREAD

**Issue by robertturner** [filoe/cscore#260]
In WasapiOut.Initialize the IWaveSource waveSource is turned into ISampleSource for a VolumeSource. Many (most?) applications have an ISampleSource instead of an IWaveSource. So usually we would have an ISampleSource, convert it to an IWaveSource to pass to ISoundOut.Initialize, and then WasapiOut immediately converts the IWaveSource to an ISampleSource for the VolumeSource. This results in an unnecessary and computationally expensive float-to-PCM-to-float conversion. 

How can we eliminate this? We could get rid of the VolumeSource but then it would not fulfil the ISoundOut Volume property. I do wonder if it's appropriate to include Volume in ISoundOut as if someone wants volume control then can optionally add their own VolumeSource, and then the rest of us can have more efficient processing. I am aware that DirectSoundOut has an intrinsic volume control whereas WasapiOut and WaveOut each use a VolumeSource - perhaps Volume could still be exposed on DirectSoundOut, but not be a member of the generic ISoundOut.
Another alternative would be to add an ISoundOut.Initialize overload that accepts an ISampleSource. WasapiOut and WaveOut could pass it directly to VolumeSource.

**Comment by filoe** [comment]
You are right.
The original architecture did not include ISampleSource so it is designed to work with IWaveSource only.
One reason for using VolumeSource is that DirectSoundOut and WaveOut would need some conversion from a scalar float value to some other value (e.g. decibel).
If you use the getter of the property there was always a difference between the value which was set and the value which was returned.

**Comment by robertturner** [comment]
I'm not facing a performance problem yet, but I'm in the middle of implementing a multi-capture multi-sink app where we'll be handling ~6 streams, so I'm just wary of opportunities for improvement

**Comment by filoe** [comment]
Ok, you're right. There is some potential for improvement. 
But in fact, I've never met a situation where this was a problem. In fact the overhead is not too big.
If you'll run into any situation where this may get critical, we can think of any other solution. But changing the interfaces is not an option. All the other applications would be broken.
