### ISSUE TITLE
Question: Audio routing of individual programs

### ISSUE THREAD

**Issue by dtphase** [filoe/cscore#261]
Hi there, is it possible with this library to route the audio from a program to a playback device other than the default?

I can't change the program's audio output device and the only program that seems to be able to is CheVolume.

Thank you

**Comment by filoe** [comment]
You may take a look at this project:
https://github.com/ChaosinaCan/AudioPipe

**Comment by dtphase** [comment]
This is really close but I need to route the audio from one specific program, not from the whole playback device.

**Comment by filoe** [comment]
As far as I know, that is not possible without hooking win apis.
