### ISSUE TITLE
Uri format file://localhost/<local_file_path> causes FileNotFoundException

### ISSUE THREAD

**Issue by snalesso** [filoe/cscore#265]
If you try to

    var location = new Uri(@"file://localhost/C:/song.mp3");
    var ws = CodecFactory.Instance.GetCodec(location);

a `FileNotFoundException` is raised.
Since it is a meaningful format, shouldn't it be supported?

**Comment by filoe** [comment]
Sorry for the very late response.
Hopefully this will do the job.

**Comment by snalesso** [comment]
Are these updates you're working on these days supposed to get into a new release?

**Comment by filoe** [comment]
Will publish it soon.
