### ISSUE TITLE
LinearFadeStrategy fails to detect fade completion for sub-second durations

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [filoe/cscore#268]
Depending on sample frequency and specified fade duration (usually, < 500ms), fade volume increment step can become too large and _currentVolument will overshoot the _targetVolume. Fade completion never gets detected and volume keeps increasing infinitely. Here is the fix:

File: LinearFadeStrategy.cs

Original:

```
private bool IsFadingFinished()
{
   return Math.Abs(_currentVolume - _targetVolume) < 0.00001f;
}
```

Fixed:

```
private bool IsFadingFinished()
{
   return Math.Abs(_currentVolume - _targetVolume) < Math.Abs(_step) ||
      _step > 0.0f && _currentVolume > _targetVolume ||
      _step < 0.0f && _currentVolume < _targetVolume;
}
```

**Comment by filoe** [comment]
Thanks for reporting and providing a propper solution! 👍

**Comment by R0ll1ngSt0ne** [comment]
Sorry, I forgot to cover the case when _step is 0) - fade should finish immediately (probably a check should be added to StartFading so that no cycle is wasted to detect completion:

if (Math.Abs(_step) <= 0.00001f)
... complete fade right away

**Comment by filoe** [comment]
You mean here: https://github.com/filoe/cscore/blob/75242c93df5ac133cfddf8f5193fc112dd74bb80/CSCore/Streams/LinearFadeStrategy.cs#L86 ?

**Comment by R0ll1ngSt0ne** [comment]
I rewrote StartFading like this to cover these edge cases:


        public void StartFading(float? from, float to, double duration)
        {
            if (SampleRate <= 0)
                throw new InvalidOperationException("SampleRate property is not set to a valid value.");
            if (Channels <= 0)
                throw new InvalidOperationException("Channels property it not set to a valid value.");
            if (to < 0 || to > 1)
                throw new ArgumentOutOfRangeException("to");

            if (IsFading)
                StopFadingInternal();

            if (!from.HasValue)
                _startVolume = CurrentVolume;
            else
            {
                if (from.Value < 0 || from.Value > 1)
                    throw new ArgumentOutOfRangeException("from");
                _startVolume = from.Value;
            }

            _targetVolume = to;
            _currentVolume = _startVolume;

            float delta = _targetVolume - _startVolume;

            // Done immediately if duration is 0 or start end end volumes are the same
            if (Math.Abs(duration) < 1.0 || Math.Abs(delta) < 0.00001f)
            {
                FinalizeFading();
            }
            else
            {
                //calculate the step
                var durationInBlocks = (int)(duration / 1000 * SampleRate);
                _step = delta / durationInBlocks;

                IsFading = true;
            }
        }
