### ISSUE TITLE
How to implement optional multiple DmoxxxxxxxxEffects

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#269]
Hello...
well an application shows multiple (optional) DmoxxxxxxEffects [xxxxxx represents the type of the effect eg. echo, chorus, etc...]
Now there's a switch button (On/Off) above each of the effects settings (sliders), when the user wants to switch Echo effect on he clicks that switch button, and when he wants to further switch Chorus effect, he clicks the relative On/Off switch to trigger that effect on, the same with Reverb, and so on...
Now I'm confused, as this scenario will result in multiple conditions as bellow:
```
IWaveSource _source;    // Assuming that is already available

DmoEchoEffect _echo;
DmoChorusEffect _chor;
DmoWavesReverbEffect _rev;

if (echoSwitch.Checked){_echo = new DmoEchoEffect(_source);}
if(chorusSwitch.Checked)
{
  if (echoSwitch.Checked) { _chor = new DmoChorusEffect(_echo); }
   else { _chor = new DmoChorusEffect(_source); }
}
if(reverbSwitch.Checked)
{
  //Here comes the confusion, because there are 4 previous scenarios for the two previous
  // switches which are:  (off, off) - (on, on) - (off, on) - (on, off)
  // And the more we have switches for more effects, the scenarios will be more complicated,
  // and this may lead to slow the performance.
}
```

Please help me if somebody has implemented these conditions before, or has an idea on how to implement it without affecting the performance.

**Comment by filoe** [comment]
All Effects got an Enabled property.

**Comment by Bahaatya** [comment]
What does this mean please? any explanation?
The problem is that IWaveSource can't be converted to DmoXxxxxxEffect, nor DmoXxxxxxEffect to IWaveSource
The situation is like series of chains, but once the user switch off an effect the chains loses one and I can't Convert the DmoChorusEffect into IWaveSource.
Please can you show me a code example on this scenario??

Thanks in advance.

**Comment by Mitra-M** [comment]
I think [this  issue.](https://github.com/filoe/cscore/issues/153) is what you want.

**Comment by Bahaatya** [comment]
@filoe Thank you so much for your respond, I got now what you meant by "Enabled Property"
@Mitra-M Thank you so much as well, for your support :)

Sorry guys for being late

**Comment by Mitra-M** [comment]
:)
