### ISSUE TITLE
Cannot identify the end of stream with some special encoders

### ISSUE THREAD

**Issue by Magentaize** [filoe/cscore#270]
Once the reader seeks the end of the stream, it will not stop and continue playing white noise.
It's the sample file but I don't know its encoder.
https://drive.google.com/file/d/0B621ujUI0FrVcDFfSUppVVBJcEU/view?usp=sharing

**Comment by filoe** [comment]
Should be fixed. Thanks for reporting the bug 👍

**Comment by Magentaize** [comment]
Thank you!
