### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DavidVogel** [filoe/cscore#274]
Hello, I am a technical writer with 7+ years of professional experience and am looking to work on an open source project for audio software that uses C# and .NET.

I am one class shy of a BS in Computer Science (I'll be finishing it at some point!) and also have a BM in (classical) Piano Performance. I have also worked a good deal with audio software such as Max/MSP and various DAWs (Pro Tools, Sonar, Ableton Live), plugins (Reaktor, Kontakt, etc), and notation programs (Finale).

It seems this project could benefit greatly from some docs in addition to the Doxygen reference--tutorials, guides, etc.

If you are interested in letting me work with you on this, please let me know.

Thanks, Dave

**Comment by snalesso** [comment]
Well you may throw pull requests and maybe with time he will take you in

**Comment by DavidVogel** [comment]
Yeah I'm planning on that, but I thought it would be worth giving a shout out just in case. Digging through the code and figuring things out myself takes a good bit longer :)

**Comment by filoe** [comment]
Hello David,

glad to hear that. Would be absolutely great, if you would contribute to this project!
Of course I can provide you any information you need.

Regards
Florian

**Comment by DavidVogel** [comment]
Excellent! If you want to contact me so we can discuss an approach, email me at david.michael.vogel@gmail.com. My timezone is EDT in the U.S. (-4 GMT).

**Comment by filoe** [comment]
I'll close this for now. 
We're in contact on skype anyway.

**Comment by DavidVogel** [comment]
Cool, I'll be in touch soon!

**Comment by andremarcondesteixeira** [comment]
any progress on this? I can't use the lib because I don't know how :S
