### ISSUE TITLE
White noise problem

### ISSUE THREAD

**Issue by ChristianFreak** [filoe/cscore#275]
So I'm trying to parse in an url of a audio stream to the **FfmpegDecoder("string url")**.
The playblack works normal with the **Wasapiout** but it generates a ton of white noise when I try to write it to a stream **(ffmpegDecoder.WriteToStream(stream))** (It's an audio stream from a program called Discord).

You can hear the song with a very bad quality in the backround quietly but in there is so much white noise in the foreground. I don't know if this is a problem with the WriteToStream function or with my stream.

Thanks in advance,
-Chris

**Comment by ChristianFreak** [comment]
I tried it with a different wrapper for the program called Discord but same goes for that.
Again white noise..
This time it's while loop with the stream.Read() function.

**Comment by filoe** [comment]
Do you have some code that reproduces the problem?

**Comment by ChristianFreak** [comment]
https://hastebin.com/iqikejibeb.cs
https://hastebin.com/cujofudiko.cs

**Comment by ChristianFreak** [comment]
Just try to stream that data with the WriteToStream or with the Read loop and output that. Maybe that reproduces the problem also.

**Comment by filoe** [comment]
Do you have any sample url?

**Comment by ChristianFreak** [comment]
I'm using url's from youtube. Audio stream: [https://r4---sn-bvvbax-8pxz.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=audio%2Fwebm&source=youtube&itag=251&id=o-AONeMRiKKxwK8Y5rUKWypy1onhiUq1BoqXGLt_8rY9Ts&lmt=1449589007371141&dur=237.101&mt=1505649998&key=yt6&ip=78.132.83.253&expire=1505671675&clen=4045631&mv=m&ei=m2W-WarSBc-qV4-qhIgB&ms=au&mm=31&mn=sn-bvvbax-8pxz&ipbits=0&requiressl=yes&pl=17&initcwndbps=687500&gir=yes&signature=A2706091AE3CAFA285043874FD9F65402B02363F.CF963BE32EA5C9D2B1708DEA83003197335D3E1E&ratebypass=yes](Stream)

**Comment by filoe** [comment]
Well, getting http 403 returned anyway. There is not even some white noise.

**Comment by ChristianFreak** [comment]
Wow you saved my day. Thank you! I'm really enjoying the audio stuff you created and I'm definitely going to use them!
