### ISSUE TITLE
Read Multiple Audio Streams from One Video

### ISSUE THREAD

**Issue by eklam** [filoe/cscore#276]
Is it possible to read multiple audio streams from one video file? 

I'm trying to implement a check that would tell if a video file has stereo (or better) sound. Is it currently possible with cscore?

**Comment by filoe** [comment]
Multiple streams or multiple channels?

**Comment by eklam** [comment]
Streams, like tracks in a video file

**Comment by filoe** [comment]
I'm sorry. It is not supported out of the box. 
Currently all the decoders read the default audio source from a video file. 
Of course you could fork the project and make the necessary changes. 
You could easily use the MediaFoundationDecoder buy replacing all occurrences of `MF_SOURCE_READER_FIRST_AUDIO_STREAM` with some custom logic here: https://github.com/filoe/cscore/blob/master/CSCore/MediaFoundation/MediaFoundationDecoder.cs
Something similar would be possible for ffmpeg. Is that an option`?

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.

**Comment by eklam** [comment]
I implemented a workaround for now in a fork: 

https://github.com/eklam/cscore/commit/766caf90e72bde0c60f68a7bee5e30aa0eaa24f4

**Comment by filoe** [comment]
Looks interesting!
Any plans on creating a pull request?

**Comment by eklam** [comment]
Currently I feel like my implementation doesn't sit well within the library. Could review it and suggest changes?
