### ISSUE TITLE
HRTF support

### ISSUE THREAD

**Issue by sanslash332** [filoe/cscore#280]
Hey guys, do you have plans to add HRTF support in the future?
Is a interestin technology, to add 3d sound to a two channels output, like headphones or similar.
I've tested your 3d support, but is only for multichannel, for two channel, is the same as you panning.

Well, that. if you're planed that, will be awesome. ¡thanks!

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
