### ISSUE TITLE
Program crash when loading invalid audio file

### ISSUE THREAD

**Issue by fabri9532** [filoe/cscore#281]
When I load an invalid audio file (ex: a .zip file renamed .wav) with the following code

        Dim codec As IWaveSource

        Try
            codec = CSCore.Codecs.CodecFactory.Instance.GetCodec("C:\Users\Pippo\Desktop\InvalidFile.wav")
        Catch ex As CSCore.MediaFoundation.MediaFoundationException
            If (ex.ErrorCode = &HC00D36C4 Or ex.ErrorCode = &HC00D36B3) Then '0xC00D36C4 = MF_E_UNSUPPORTED_BYTESTREAM_TYPE  |  0xC00D36B3 = MF_E_UNSUPPORTED_SERVICE
                MsgBox("Invalid file")
                Exit Sub
            End If

            Throw ex
        Catch ex As Exception
            Throw ex
        End Try
`
- If I'm in Visual studio, appear this message in the window "output" (Target framework .NET 3.5 or .NET 4): A first chance exception of type 'CSCore.MediaFoundation.MediaFoundationException' occurred in CSCore.dll

- If I run the program executable outside Visual Studio, the program, some times after a few moments, or when I re execute the code above, it crash with the following data (Target framework .NET 4):
Problem Signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	VBSequencer.exe
  Problem Signature 02:	1.0.6484.34101
  Problem Signature 03:	59d27ddb
  Problem Signature 04:	CSCore
  Problem Signature 05:	1.1.5992.18249
  Problem Signature 06:	57496005
  Problem Signature 07:	115
  Problem Signature 08:	0
  Problem Signature 09:	System.ArgumentNullException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1040
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

CSCore v1.1.0 to 1.2.1.1
Language VB.NET (Visual Studio 2012 update 5)
Possible related issue: https://github.com/filoe/cscore/issues/217

**Comment by filoe** [comment]
What would be the correct behaviour in your eyes?

**Comment by fabri9532** [comment]
The correct behaviour, in my eyes, is:
if I run the program outside Visual Studio (standalone executable), it does not have to crash the second time I run the code or sometimes after a few moments.
With respect to the place code, it must always display the message "Invalid file".

After further testing I found that the problem also occurs with target Framework .NET 3.5 if the program is compiled as x86.

I wanted to point out that renaming a .zip file to .wav is just one example: the audio file might be an unsupported or corrupt type.

**Comment by filoe** [comment]
CSCore will not ever display messages. We can talk about a nicer exception class with an inner exception. But the exception handling is the responsibility of the application.

**Comment by fabri9532** [comment]
Maybe you have not looked carefully at the code I posted; surely you have not tried it.
The "Invalid file" message is in my code.

I simplify the code and I will try to explain it better (sorry for my bad english).

        Dim codec As IWaveSource

        Try
            codec = CSCore.Codecs.CodecFactory.Instance.GetCodec("C:\Users\Pippo\Desktop\InvalidFile.wav")
        Catch ex As Exception
            MsgBox("Invalid file")
        End Try

Place the above code in a Button Click event of a Form.

If I run the executable outside Visual Studio, and the target framework is .NET 4 or the target framework is 3.5 with compile as x86:
the first time I call the code it work;
the second time I call the code, the program crash.

Moreover, even at the first call of the above code, if I wait several seconds before clicking the OK button on the MessageBox, when I click it, the program crashes.

**Comment by fabri9532** [comment]
After some further testing, I found that the program crashes when the garbage collector calls some CScore finalizers after trying to load an invalid file.

If after the following code (where InvalidFile.wav is an invalid wav file):

    Dim codec As IWaveSource

    Try
        codec = CSCore.Codecs.CodecFactory.Instance.GetCodec("C:\Users\Pippo\Desktop\InvalidFile.wav")
    Catch ex As Exception
        MsgBox("Invalid file")
    End Try

I call the following code:

     GC.Collect()
     GC.WaitForPendingFinalizers()

the program crash immediately with System.ArgumentNullException in CSCore.
Crash occurs only if the program runs out of Visual Studio (standalone executable).

**Comment by filoe** [comment]
I will have a look at it. Thanks for reporting.

**Comment by fabri9532** [comment]
I forgot to repeat:
if the target framework is .NET 3.5 the crash occur only if the program is compiled as x86;
if the target framework is .NET 4 the crash occur also if the program is compiled as x64

Thanks for your help.

Fabrizio.

**Comment by speige** [comment]
I believe this has been fixed in GitHub, but not on NuGet. I was having the same issue & removed NuGet & replaced it with the .dll compiled from latest github sourcecode & the problem was resolved for me.

**Comment by filoe** [comment]
New version is on nuget. Please try it out.

**Comment by fabri9532** [comment]
I tested the version 1.2.1.2 and the problem no longer occurs.
For me it's fixed.

Many thanks, Fabrizio.
