### ISSUE TITLE
Incorrect handling of new sample in FftProvider

### ISSUE THREAD

**Issue by Creepin** [filoe/cscore#282]
https://github.com/filoe/cscore/blob/29410b12ae35321c4556b072c0711a8f289c0544/CSCore/DSP/FftProvider.cs#L72

In my opinion the new samples are added incorrect to the _storedSamples Array.

```
if (_currentSampleOffset >= _storedSamples.Length) //override the already stored samples.
                _currentSampleOffset = 0;
```
If the Offset exceeds the length of the Array, the Offset is set to 0. Next samples will be written to the beginning of the Array overriding old samples. But this is not correct since now old samples follow new samples in a wrong order. Correct implemenation would be a circular buffer that kicks off old samples on one side and adding new samples on the other. With the current implementation an edge between an old sample and a new sample is created resulting in a false (high) frequency detection.

Please correct me if I am wrong.

**Comment by filoe** [comment]
Thanks for reporting!
This should fix the issue:
https://github.com/filoe/cscore/commit/cb7134e23708c3523f6ba050cb2cb64da50398cd#diff-df1a2b73de96e406dfc6a194fb591aee

What do you mean?

**Comment by Creepin** [comment]
Should work in theory, but I think _currentSampleOffset could be modified between the two uses, when GetFftData is called in parallel to one of the Add methods

**Comment by Creepin** [comment]
@filoe should this be regarded as closed despite the concerns?
