### ISSUE TITLE
SHOUTCast protocol support

### ISSUE THREAD

**Issue by Bahaatya** [filoe/cscore#283]
Hello Filoe;
Is there any idea on how to implement a SHOUTCast client/server using your CSCore great library?
What I ask for is a feature or so to make us able to online stream what's being played in the Application to a SHOUTCast server...

I've been searching for a very long time over here and there for an ability for streaming the Audio file to a SHOUTCast server, and I found some other libraries, but they can't work together with CSCore, due to the differences in the methods of parsing the audio file, or dealing with it.

Any idea or suggestion would be highly appreciated... 
Thanks in advance

**Comment by filoe** [comment]
Currently there are some else priorities. 
I'll close it for now. Maybe but it is marked as "open feature request". Maybe we'll come back to this.

Regarding other libraries. CSCore is quite flexible. It should be possible to work together with some else libraries.

**Comment by Bahaatya** [comment]
First thanks for your answer and concern

Yeah CSCore can be used with other libraries, but the other library while doing the SHOUTCast part, it captures all the Computer System Sounds (Stereo Mix) not only what's being played in the Application that uses CSCore...
This is why integrating SHOUTCast features to CSCore would make it very fruitful, plus the performance positive sides when you use as minimum libraries as possible in the application.
Thanks for understanding
