### ISSUE TITLE
On Win 10 FCU, CodecFactory.Instance.GetCodec throws DllNotFoundException for mfplat.dll

### ISSUE THREAD

**Issue by snalesso** [filoe/cscore#284]
OS: Windows 10 FCU (winver: 1709, build: 16299.19)
CSCore: v1.2.1.1 (last Nuget package)

when calling

    CodecFactory.Instance.GetCodec(<Uri>)

it throws

> DllNotFoundException: Unable to load DLL 'mfplat.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by filoe** [comment]
Are there any pending windows updates?

**Comment by snalesso** [comment]
Not yet.

**Comment by snalesso** [comment]
Quick search and ... My bad: forgot that running an N/KN version of Windows you need to install the Media Feature Pack separately. Since every version of Windows needs its own specific version of the MFP, and that it is always published some days after the new Windows release, need to to keep checking the [Media Feature Pack's download page](https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions)

**Comment by snalesso** [comment]
Media Feature Pack for Windows 10 FCU (1709) available [here](https://www.microsoft.com/en-us/software-download/mediafeaturepack)
