### ISSUE TITLE
Build CSCore with Visual Studio Community 2017 

### ISSUE THREAD

**Issue by Erhie** [filoe/cscore#285]
With my new installed Visual Studio Community 2017 I had to add the
package source **https://www.nuget.org/api/v2/** in settings of NuGet 
for installing the packages Mono.Cecil and NVorbis .
Than I installed these packages with the package manager
(Visual Studio->Tools->NuGet Package Manager->Manage NuGet Packages for Solution... )

This issue only for help others
Erhie

**Comment by filoe** [comment]
I'll close it and mark is as "documentation".

Thanks!
