### ISSUE TITLE
Is there a way to stream generic sound files, similar to Mp3WebStream

### ISSUE THREAD

**Issue by SamuelCox** [filoe/cscore#289]
Hi,
There's not a sample for this so I was wondering, how would you play generic sound files (mp3, m4a, wav, etc) from a tcp stream, chunked http stream or something similar? Essentially what I want is a MediaFoundationDecoder but for a streaming response. Would I have to write a custom layer to figure out what codec it is, write each frame to a buffer and use the right streaming player based on that?

**Comment by filoe** [comment]
In fact the Mediafoundation decoder does that for you. Or even better, use the ffmpeg integration.

**Comment by SamuelCox** [comment]
The way the docs read, it seems like MediaFoundationDecoder takes a complete stream, it doesn't seem it exposes a way to write parts of a stream to the decoder?

**Comment by filoe** [comment]
So you would like to stream data to any clients?

**Comment by SamuelCox** [comment]
I'll give an example. If I were to have an API that returned songs to me as a HTTP chunked response, and wanted to use cscore to play that song as individual frames came in, rather than waiting for the whole song and playing it then, how would I do that?

**Comment by filoe** [comment]
Try the MediaFoundationDecoder or even better, CSCore.Ffmpeg
