### ISSUE TITLE
Audible Pop at the end of fade using LinearFadeStrategy

### ISSUE THREAD

**Issue by R0ll1ngSt0ne** [filoe/cscore#291]
When fading volume to 0, there is an audible "POP" when fading completes - making the library useless for high end audio editing applications. The problem results from _currentVolume _"overshooting"_ 0 and momentarily becoming positive before fading finalizes:

To fix replace the following code:

            while ((sampleIndex - offset) < count)
            {
                if (channels == 1)
                    buffer[sampleIndex++] *= _currentVolume;
                else if (channels == 2)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;
                }
                else if (channels == 3)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                }
                else if (channels == 4)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;
                }
                else if (channels == 5)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                }
                else if (channels == 6)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;

                    buffer[sampleIndex++] *= _currentVolume;
                    buffer[sampleIndex++] *= _currentVolume;
                }
                else
                {
                    for (int i = 0; i < channels; i++)
                    {
                        buffer[sampleIndex++] *= _currentVolume;
                    }
                }

                _currentVolume += _step;
                if (IsFading && IsFadingFinished())
                {
                    FinalizeFading();
                    int c = count - (sampleIndex - offset);
                    if (c > 0)
                        ApplyFading(buffer, sampleIndex, c); //apply the rest

                    sampleIndex += c;
                }

With the following:

            while (sampleIndex - offset < count)
            {
                for (int i = 0; i < channels; i++)
                {
                    buffer[sampleIndex++] *= _currentVolume;
                }

                if (IsFading)
                {
                    _currentVolume += _step;
                    if (IsFadingFinished())
                        FinalizeFading();
                }
            }

Much more concise (I don't why the 6 special cases were even needed?), and makes sure that _currentVolume is no longer incremented once fading completes.

**Comment by filoe** [comment]
Thanks for reporting! Should be fixed.

**Comment by R0ll1ngSt0ne** [comment]
I suggest that you use the code I proposed ( as opposed to 47f6bfa1f6ccde6a169fcad6503e32625d19da9b commit):

Examining logic - all those special 6 cases (as well as the final ApplyFading call) are not necessary and are _fully replaceable by the 14 lines above_.

1) The special checks all boil down to the "for (int i = 0; i < channels; i++)" loop
2) ApplyFading call results in exactly the same processing as simply letting the loop above run its course if fading has completed.
