### ISSUE TITLE
Live Pitch Detection?

### ISSUE THREAD

**Issue by cambo2015** [filoe/cscore#292]
Hey. I am fairly new to audio processing, How would I send live Mic to process a pitch? I've read where FFT is not completely sufficient and would need to use another algorithm to find the fundamental frequency.   Thanks in advance. I've been at this for a few days.

**Comment by filoe** [comment]
Well, pitch detection is definitly possible. 
CSCore does not provide an out of the box algorithm. 
But there are several samples out there on how to get the fundamental frequency out of an fft result. 
For example: https://www.codeproject.com/script/Articles/ViewDownloads.aspx?aid=32172

**Comment by cambo2015** [comment]
That's great stuff. Ill have a look at that. Thank you.
