### ISSUE TITLE
CSCore.DSP.DmoResampler.Read cause Exception 0x80004001 (Not implemented)

### ISSUE THREAD

**Issue by fabri9532** [filoe/cscore#296]
Look at the following code:
```
 IWaveSource Codec = null;
 IWaveSource waveSource = null;
 byte[] Buffer = null;
 int count;

 Codec = CSCore.Codecs.CodecFactory.Instance.GetCodec("C:\\Users\\Pippo\\Desktop\\192000 fail.wav");

 waveSource = Codec.ToSampleSource().ToWaveSource(16);
 waveSource = waveSource.ChangeSampleRate(44100);

 Buffer = new byte[waveSource.Length];

 count=waveSource.Read(Buffer, 0, (int) waveSource.Length); //cause Exception 0x80004001 (Not implemented)

 waveSource.Dispose();
 Codec.Dispose();
```

If I resample a wav file with a duration of at least 18 seconds from 192000Hz to 44100Hz, CSCore.DSP.DmoResampler.Read causes Exception 0x80004001 (Not implemented).
If the file duration is 17 seconds or less, the exception does not occur but the count of readed bytes is less than the total length.
The exception also occurs from a 96000Hz file, but the duration of the sound should be higher.
I have not tried other frequency combinations.

Am I making a mistake or is it a Bug?

At this address you can find 3 sample wav files: http://ge.tt/1oqPcPn2
SHA-256: dba0847634236e5319067b90c8757091e99ce5a7640b2ddfd2817f3042f159b3

CSCore version: 1.2.1.2
Target framework: .NET 4
OS: Windows 7 x64

Thank for your help.
Fabrizio.

**Comment by filoe** [comment]
Thanks for reporting the bug. 
The issue is caused by Microsofts DMO Resampler, which raises the E_NOTIMPLEMENTED error if you process too much data at once.
There are two possible solutions:
1. Don't read so muchd at once.
2. Use my workaround which will split your data request into blocks and process each of them. (not on nuget yet)

**Comment by fabri9532** [comment]
Thank you for your interest in the problem and sorry for the delay in replying.
I downloaded today the source of CSCore and compiled it: the exception no longer occurs.
However, the second problem I have reported remains: the count of readed bytes is less than the total length.
Look at the code above: if I load the file "192000 fail.wav", after resampling, the "waveSource.Length" is 1587600 bytes (correct value) but the result of "waveSource.Read(Buffer, 0, (int) waveSource.Length)" is only 1587538 bytes.
**Also**, after about 3 or 4 seconds, the resulting audio is muted: try this code and open the resulting saved audio file with an audio editor:

            IWaveSource Codec = null;
            IWaveSource waveSource = null;
            byte[] Buffer = null;
            int count;
            CSCore.Codecs.WAV.WaveWriter writer = null;

            Codec = CSCore.Codecs.CodecFactory.Instance.GetCodec("C:\\Users\\Pippo\\Desktop\\192000 fail.wav");

            waveSource = Codec.ToSampleSource().ToWaveSource(16);
            waveSource = waveSource.ChangeSampleRate(44100);

            Buffer = new byte[waveSource.Length];

            count=waveSource.Read(Buffer, 0, (int) waveSource.Length); 

            writer = new CSCore.Codecs.WAV.WaveWriter("C:\\Users\\Pippo\\Desktop\\Resampled.wav", waveSource.WaveFormat);
            writer.Write(Buffer, 0, Buffer.Length);

            writer.Dispose();
            waveSource.Dispose();
            Codec.Dispose();


At this address you can find the audio file "192000 fail.wav": http://ge.tt/1oqPcPn2
Thanks for your help.
Fabrizio.

**Comment by filoe** [comment]
Well, the resampler changes the amount of bytes. Your resampling 192kHz to 44.1kHz. 
You can't tell exactly the number of output bytes.
In general: Most of the time, the length property is imprecise. If you need a absolutly precise value, you have to decode it first. Therefor, use a smaller buffer and decode till the Read method returns zero.
Hint: You can use the `WriteToFile` extension method. It will encode the stream to a wave file.

**Comment by fabri9532** [comment]
Yes, WriteToFile extension method work regarding the duration.
But, even with this method, when I resample the file "192000 fail.wav", after about 3 or 4 seconds, the resulting audio is still mute.
If I resample the file "96000 fail.wav", after about 17 seconds, the resulting audio is still mute.
It does not happen to me with other files I've tested.
Strange!

**Comment by filoe** [comment]
It has to do with the samplerate.
You need a higher samplerate for such high frequencies as your sample.
Try any other resampler like the one of audacity, the result will be the same.

**Comment by fabri9532** [comment]
You're right Florian!
I had not thought about this.
Thank you for your precious help.
Fabrizio.
