### ISSUE TITLE
Uri specification doesnt allow special character in filepath

### ISSUE THREAD

**Issue by KrayZeee** [filoe/cscore#298]
FfmpegDecoder(string url) throws invalid arguments when filepath includes special character for example Я like in KoЯn.

**Comment by digimezzo** [comment]
Some filenames which cause the issue:

クラブナイトメア.mp3
I.O.I - miss me_ [FLAC]1 너무너무너무.flac
クラブナイトメア.mp3

Stack trace from Dopamine:

> 2017-11-20 14:08:19.862|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\02 クラブナイトメア.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: avformat_open_input returned 0xffffffea: Invalid argument. StackTrace: at CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)
> at CSCore.Ffmpeg.AvFormatContext..ctor(String url)
> at CSCore.Ffmpeg.FfmpegDecoder..ctor(String url)
> at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
> at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
> at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Dopamine.Common.Services.Playback.PlaybackService.d__184.MoveNext()

**Comment by filoe** [comment]
This is a known issue. For quick fix, open a stream yourself and pass it to the decoder. Dont forget to dispose the stream.
