### ISSUE TITLE
Realtime processing buffer

### ISSUE THREAD

**Issue by joefrando** [filoe/cscore#299]
Hello,
i get realtime audio data from a telephone in a buffer. The buffer is constantly updated.

How to output that to the audio card?

Regards
Martin

**Comment by filoe** [comment]
Sorry for the late answer.
Use the `WriteableBufferingSource`.
You will need the format of the audio data.
If it is encoded you will have to decode it first. 
If not, you can just use the mentioned class, initialize it with the correct format and write data to its buffer.
In your scenario, it is recommended to set the `FillWithZeros` property to true.
If you've got your buffering source, just play it with any `ISoundOut` implementation.
`soundOut.Initialize(bufferingSource);`

`soundOut.Play();`

**Comment by joefrando** [comment]
Hello,

currently i implemented ISoundIn where i raise an event to signal new realtime data. When i use WriteableBufferingSource.Write will the be the sound API get informed for every new WAV frame?

PS: i'd only have one instance of WriteableBufferingSource.

Regards

**Comment by joefrando** [comment]
WriteableBufferingSource works realtime!
