### ISSUE TITLE
Sending ISoundOut through web API

### ISSUE THREAD

**Issue by Lauchi** [filoe/cscore#301]
Hi,

i wanted to use the cscore in a project where i would like to process audio in the server and send it to a browser throught an Web API. As far as I am concerend, you can send an audio stream to a browser and the browser will play it through the speakers. Is there a way to convert the ISoundOut to something i can transfer via a Web Api?

Thanks!

**Comment by filoe** [comment]
Using CSCore you can manipulate audio source and stream them to destinations (output device, stream,...).
CSCore does not cover the creation of web radios using ASP.NET.

**Comment by Lauchi** [comment]
Thanks for the reply. But where do i get a Byte-Stream, or something similar, that i could put through an web api?

**Comment by filoe** [comment]
The IWaveSource itself is kind of a stream. It will provide raw data. If you need encoded data, you can for example use the MediaFoundationEncoder.

**Comment by Lauchi** [comment]
Ok thanks, I will have a look into it this weekend. Happy with the library so far =)
