### ISSUE TITLE
Would I be able to distinguish between audio sources?

### ISSUE THREAD

**Issue by BogdanAlexandru** [filoe/cscore#303]
Hi, sorry if this is a completely noob question, I've 0 experience with audio, but would cscore allow me to distinguish between audio sources at runtime? For example, say I've some audio coming from YouTube (Chrome), and then I turn on Foobar2000, would I be able to programatically see the two sources as being separate, and maybe control the volume of each?

The volume control in Windows already lists the sources separately, so I'm guessing that the Windows APIs allow for this.

**Comment by filoe** [comment]
Yes, what you are looking for is the audio sessions api.
Take a look at this unit test:
https://github.com/filoe/cscore/blob/master/CSCore.Test/CoreAudioAPI/AudioSessionTests.cs#L142

I'll close it for now. If there are any further questions, feel free to reopen it.
