### ISSUE TITLE
Programme bleiben hängen mit Webradio Adresse http://st01.dlf.de/dlf/01/104/ogg/stream.ogg

### ISSUE THREAD

**Issue by KalleStae** [filoe/cscore#304]
Endlosschleife in   
namespace CSCore.Codecs.MP3 
public class Mp3WebStream : IWaveSource"
   private void CreateStream(bool async)
        
mit folgender Ausgabe
Mp3Frame::ParseFrame: MPEGLayer == MpegLayer.Reserved
Mp3Frame::ParseFrame: MPEGLayer == MpegLayer.Reserved
Mp3Frame::ParseFrame: MPEGVERSION = MpegVersion.Reserved
Mp3Frame::ParseFrame: MPEGVERSION = MpegVersion.Reserved
Mp3Frame::ParseFrame: MPEGVERSION = MpegVersion.Reserved
Mp3Frame::ParseFrame: MPEGVERSION = MpegVersion.Reserved
etc. etc,

Habe nur eine Webadresse mit oog benutzt über 

                _waveSource = CodecFactory.Instance.GetCodec(uri);
Adresse ist:
http://st01.dlf.de/dlf/01/104/ogg/stream.ogg
Es gibt keinerlei Rückmeldung.

**Comment by filoe** [comment]
Use the `FfmpegDecoder` or the `MediaFoundationDecoder`. 
The `Mp3WebStream` expects an mp3 stream and will continue searching for mp3 frames.
