### ISSUE TITLE
5.1 speakers, how to get only 2 channels

### ISSUE THREAD

**Issue by TheSpixxyQ** [filoe/cscore#308]
Hi, I'm using CSCore to calculate RMS from WasapiLoopbackCapture. It works well with headphones, but with 5.1 speakers it gives me very low values (around 0 to 2, instead of 0 to ~130), because it calculates it from 6 channels. How can I force it to use only 2 channels? I tried this:
`MMDevice captureDevice = MMDeviceEnumerator.DefaultAudioEndpoint(DataFlow.Render, Role.Console);`
`WaveFormat deviceFormat = captureDevice.DeviceFormat;`
`_capture = new WasapiLoopbackCapture(100, new WaveFormat(deviceFormat.SampleRate, deviceFormat.BitsPerSample, deviceFormat.Channels <= 2 ? deviceFormat.Channels : 2));`
, but it crashes with it.

Then I have this:
`_capture.Initialize();`
`_soundInSource = new SoundInSource(_capture) { FillWithZeros = false };`
`_stream = _soundInSource.WaveFormat.SampleRate == 44100
        ? new SingleBlockNotificationStream(_soundInSource.ToStereo().ToSampleSource())
        : new SingleBlockNotificationStream(_soundInSource.ChangeSampleRate(44100).ToStereo().ToSampleSource());`
`_soundInSource.DataAvailable += OnSoundDataAvailable;`
`_capture.Start();`

How can I do it?
I'll be very glad, if you could help me with this

**Comment by filoe** [comment]
I have to take a more detailed look at it. ToStereo should do the trick... are you reading data from the stereo source to calc rms?

**Comment by TheSpixxyQ** [comment]
I think I got something. Realtek driver is separating low frequencies and putting them into separated channels (low freqs go to subwoofer, high to satellites). I thought that ToStereo then should merge them (if I'm right), but it doesn't.
However when I turn off bass management in Realtek (so it won't separate low freqs), it suddenly works ok (but subwoofer is not playing at all).
There has to be way to merge those channels. 

I'm also using AudioBuffer ([https://github.com/DarthAffe/KeyboardAudioVisualizer/blob/1af8bb67c3645f783d9df737a3055454eb42f72c/KeyboardAudioVisualizer/AudioCapture/AudioBuffer.cs#L44](url)) and when I changed that permalinked line to "i += 6" (to match 6 channels), it now reads only left and right channel (if I set offset to i + 2 and i + 3, it reads from center and subwoofer, +4 and +5 are rear satellites - I found that channels have this positioning). But when reading from left and right, it's without low freqs, because they are separated. And when reading from subwoofer, there are only low frequencies, so that's not ok too.

Simply - ToStereo won't merge separated low and high frequencies for me.
I hope you understand what I mean

**Comment by filoe** [comment]
What does the `WaveFormat` of the `ISoundIn` look like?
Is there a property named `ChannelMask`?
If yes, what does it look like?
The `ToStereo` method uses a `ChannelMatrix` to convert 5.1 to stereo.
It can only do that if the `WaveFormat` of the input source is of type `WaveFormatExtensible`.
See https://github.com/filoe/cscore/blob/master/CSCore/FluentExtensions.cs#L106.
The matrix which will be choosen is defined here:
https://github.com/filoe/cscore/blob/master/CSCore/DSP/ChannelMatrix.cs#L190
You can of course create a a custom matrix for your needs and use the `DmoChannelResampler` class to convert the wave source.

But in general, the `ToStereo` does merge all of the channels.

**Comment by TheSpixxyQ** [comment]
So, deviceFormat.GetType() returned CSCore.WaveFormatExtensible. And that ChannelMask you mean when I write deviceFormat.ChannelMask? No, it's not there.
What can I do next, please?

**Comment by filoe** [comment]
It is there. Take a look at the WaveFormat while debugging.

**Comment by TheSpixxyQ** [comment]
Um, can you please explain it more in detail? I'm quite newb in C#, so I don't understand everything well
Btw. I'd be glad if you could help me on any chatting app like discord, Facebook or anything, would it be possible? Thank you.

**Comment by filoe** [comment]
Set after you called `ISoundIn.Initialize`.
Move your mouse over your `ISoundIn` object, expand the `WaveFormat` property and search for the `ChannelMask` property. It will be there (you may have to check nested elements).

**Comment by TheSpixxyQ** [comment]
I think there is no ISoundIn object. I'm using this audio detection from Keyboard Visualizer I wrote about earlier, I just removed functions which I don't need. Can you please look at it? I pushed my current project to my github [https://github.com/TheSpixxyQ/VU-meter-control](url)

**Comment by filoe** [comment]
See your first post:

> _capture.Initialize();

**Comment by TheSpixxyQ** [comment]
Oh, I got it now.
There is:
> ChannelMask: CSCore.ChannelMask.SpeakerFrontLeft | CSCore.ChannelMask.SpeakerFrontRight | CSCore.ChannelMask.SpeakerFrontCenter | CSCore.ChannelMask.SpeakerLowFrequency | CSCore.ChannelMask.SpeakerBackLeft | CSCore.ChannelMask.SpeakerBackRight

**Comment by filoe** [comment]
Sorry for coming back to this so late.
Looks good to me. 
The ToStereo should do the job propertly. You can also use the `DmoChannelResampler` and play with the channel matrix.
