### ISSUE TITLE
Not registering end of track

### ISSUE THREAD

**Issue by raylight75** [filoe/cscore#309]
I'v read that this problem has been fixed but still when some song ended song starting from beginning again, and do we have some event like MediaEnded in Media player Class or is just only Stopped event.
So to be clear when i have _soundOut.Stop() is working  i want just to detect end of the song.

**Comment by filoe** [comment]
Are you using the loop source?

**Comment by filoe** [comment]
The loop stream has a streamfinished event.

**Comment by raylight75** [comment]
OMG my mistake yes  i'm using loop that was the problem when i remove loop everything work fine. Thank you.

**Comment by filoe** [comment]
Well, even if you are looping the source, you can still use the StreamFinished event of the LoopStream.
