### ISSUE TITLE
Streaming audio oputputs verbose logs

### ISSUE THREAD

**Issue by J-kit** [filoe/cscore#312]
I'm using this project on a linux(debian 9) machine and it outputs some weird logs (https://i.imgur.com/rix3Pfd.png). As far as i know is that cscore and my tool dont echo such logs. Any ideas where those could come from and how to disable them?
Thanks

**Comment by filoe** [comment]
https://github.com/filoe/cscore/blob/master/CSCore.Ffmpeg/FfmpegUtils.cs
Disable the default logger.

**Comment by J-kit** [comment]
Theese logs still show up after setting LogLevel to Fatal
https://i.imgur.com/HiICjRp.png

**Comment by J-kit** [comment]
Closed because of #311 
Thank you
