### ISSUE TITLE
MMDeviceEnumerator

### ISSUE THREAD

**Issue by Salads** [filoe/cscore#313]
I'm a bit uncertain about the Win32 API, I see that in the source for `MMDeviceEnumerator`, the constructor registers notification callbacks for the enumerator. 

Does this mean I can safely have only one instance of the enumerator and have a correctly updated list of devices when I call `EnumAudioEndpoints` or`GetDefaultAudioEndpoint` in case for some reason the hardware on the computer changes?

**Comment by filoe** [comment]
Obe instance is enough yes. Of course you could have multiple of them. It is just how Microsoft designed their api.

**Comment by Salads** [comment]
thanks!
