### ISSUE TITLE
c# windows form waveform timeline and panning of waveform

### ISSUE THREAD

**Issue by premingiet** [filoe/cscore#315]
How to add timeline to the waveform in windows form ? There is no info on plotting waveform in windows form. I don't want to generate image, rather i want to plot it in windows form and also need to scroll it along with timeline. please show an example

**Comment by filoe** [comment]
Rendering waveform controls is not the purpose of cscore.
CSCore provides the toolset for audio applications. You can build a waveform yourself. 
There is a example for rendering a waveform using wpf. Building something similar using winforms should not be a big deal. Adding a timeline, scroll functionality and so on is also a task you have to figure out yourself. That's not my task. If you need any help regarding cscore, feel free to ask on github or even better on gitter. 
Hint: There are a few examples out there:
https://github.com/tjscience/audion.cscore
https://github.com/postacik/SoundFactory
