### ISSUE TITLE
Playing  next song

### ISSUE THREAD

**Issue by raylight75** [filoe/cscore#316]
I apologize for the stupid question but i have a problem because i want to play my  songs one after the other automatically. 
I have  _soundOut.Stopped += MediaEnded , Media Ended change automatic my next song without problem. The problem is that event raised and when i press stop button and when i play current song and i want  to start with double click new song . Is it posible event to be raised only when song ended.

**Comment by filoe** [comment]
You usually don't need a stop button.
I would stick to play and pause which won't trigger the stopped event.
Anyhow, you could use something like this:
```
public class EofTrackingSource : WaveAggregatorBase
    {
        public event EventHandler EndOfStream;

        public EofTrackingSource(IWaveSource source)
            : base(source)
        {
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            int read = base.Read(buffer, offset, count);
            if (read == 0)
            {
                EndOfStream?.Invoke(this, EventArgs.Empty);
            }
            return read;
        }
    }
```

Add it to your source chain like:
```
var source = CodecFactory.Instance.GetCodec("anyfile.mp3")
    //... any other stuff
    .AppendSource(x => new EofTrackingSource(x), out EofTrackingSource eofTrackingSource);
eofTrackingSource.EndOfStream += (s, e) => Console.WriteLine("Media ended.");

_soundOut.Initialize(source);
```

**Comment by raylight75** [comment]
Thanks I appreciate your help, that's what I needed
