### ISSUE TITLE
Mp3WebStream - Send User-Agent

### ISSUE THREAD

**Issue by Petmics** [filoe/cscore#317]
Hello,
I want to send a User-Agent for the WebStream.

Does anyone know how it works?

Best regards
Petmic

**Comment by filoe** [comment]
You would need to implement it yourself. Should not be to hard. But as I remember, I've already answered your question on any other community (stackoverflow - i guess).

**Comment by filoe** [comment]
You would need to implement it yourself. Should not be to hard. But as I remember, I've already answered your question on any other community (stackoverflow - i guess).
