### ISSUE TITLE
Panning Audio with DmoChannelResampler C#

### ISSUE THREAD

**Issue by ChrisCreateBoss** [filoe/cscore#318]
I am working in an audio player which supports some advanced options taking advantage of your audio library. One of that functions is Audio Panning, I want to be able to move audio to either left or right within a slider control just like in an audio editing software.
 I found a PanSource class... firstly I did not find any example on how to use it. Second.. it says it is deprecated, use DmoChannelResampler instead. So I moved en to that clases. I already defined The wavesource, I am not sure about the Channel Matrix.. I want standard two channels, so I think I must define MonoToStereo. After that I do not know what to do to achieve panning. I am also newbie in C# and audio managing so I do not understand EVERYTHING.

Hope you can guide me on how to achieve this.
Thanks in advance

**Comment by filoe** [comment]
Sorry for the late response.
What is your usecase?
Adjusting balance between left and right channel only?
Do you have to modify it during playback (like any slider etc.)?

**Comment by ChrisCreateBoss** [comment]
Ok no problem.
Yes, just adjust the balance between left and right during playback using either a slider or a knob control. The wavesource comes from the audio player class (exactly the same as your sample, integrated with an equalizer system).

**Comment by filoe** [comment]
Well, then I would tend to use the PanSource. It is marked as obsolete but for your use case it should work best.

**Comment by ChrisCreateBoss** [comment]
Ok, I tried some things with the PanSource but I just get runtime expections, I just don't know how to use it. Could you give me a short example on how to achieve panning?

**Comment by Mitra-M** [comment]
@ChrisCreateBoss , you can use the PanSource like this:

            ```
               WasapiCapture soundIn;
               WasapiOut soundOut;
                PanSource pan;
                  . . . . . . 
              trackBar1.ValueChanged += TrackBar1_ValueChanged;
                  . . . . .
            soundIn = new WasapiCapture(true, AudioClientShareMode.Shared, 30);
            soundIn.Initialize();
            IWaveSource source = new SoundInSource(soundIn) { FillWithZeros = true };
            soundIn.Start();
            soundOut = new WasapiOut();
            pan = new PanSource(source.ToSampleSource().ToStereo());
            soundOut.Initialize(pan.ToWaveSource());
            soundOut.Play();
            . . . . .         
        private void TrackBar1_ValueChanged(object sender, EventArgs e)
        {
            pan.Pan = trackBar1.Value; // should be :  >=-1  trackBar1.Value  <=1
        }

       ```

**Comment by ChrisCreateBoss** [comment]
That worked perfectly! Thanks!
