### ISSUE TITLE
MS-PL License Compliance

### ISSUE THREAD

**Issue by Salads** [filoe/cscore#319]
I want to use CSCore in an open source project, but am a little unsure about how to do it legally. 

- Do I need to have a copy of the license in my repo?

> (C) If you distribute any portion of the software, you must retain all copyright, patent, trademark, and attribution notices that are present in the software.

- What does this mean in terms of cscore? I can't seem to find anything besides the license itself.

**Comment by filoe** [comment]
You can use CSCore without a copy of the license itself.
You are not allowed to copy the and delete any copyright notes etc. in the software.
Anyhow, a little reference to the project is always welcome :-).
Have fun using it.
