### ISSUE TITLE
doesnt building on visual studio 2013

### ISSUE THREAD

**Issue by veselcraft** [filoe/cscore#326]
when trying to compile a project, many errors take off
Invalid expression term '.'

`VolumeDuckNotification?.Invoke(this, new VolumeDuckNotificationEventArgs(sessionId, countCommunicationSessions));`

and several such dozens of errors
how did the question marks turn out to be ??

**Comment by filoe** [comment]
see also https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators
