### ISSUE TITLE
Incorrect handling of new sample in FftProvider

### ISSUE THREAD

**Issue by HenKun** [filoe/cscore#327]
#282 I'd like to reopen the issue as the issue is not completely solved, just partially fixed. (I am the author of the referenced issue, just got a new account)

**Comment by filoe** [comment]
So would synchronizing `Add` and `GetFftData` help?

**Comment by filoe** [comment]
Should be fixed now. Please confirm.

**Comment by HenKun** [comment]
Seems correct now except that I cannot test it at the moment but I think it should work. Great, thanks!
