### ISSUE TITLE
Allow the usage of 'eventSync' in WasapiLoopbackCapture

### ISSUE THREAD

**Issue by DanielGilbert** [filoe/cscore#328]
Hi,

occasionally, I have glitches when using Wasapi Loopback recording. This results in files with cracking noise, etc. When I set `eventSync` to true, everything works "glitch-free".

Is it on purpose that this configuration option is missing in the original implementation of the `WasapiLoopbackCapture` constructors? Do you see any possible drawback in using `eventSync`?

**Comment by filoe** [comment]
Good idea. Implemented your feature request.
