### ISSUE TITLE
Reading wav gsm file in debug mode throws exception

### ISSUE THREAD

**Issue by kaksmet** [filoe/cscore#332]
[These](https://github.com/filoe/cscore/blob/7067a7535eb0faa01846b90628708168fb1b4c1f/CSCore/Codecs/WAV/FMTChunk.cs#L64-L65) debug assertions fails when loading a .wav file containing the gsm 6.10 codec.
In release mode the file plays successfully.

A sample file to test with can be found here:
www.nch.com.au/acm/11kgsm.wav

I'm using CSCore from nuget and this issue is causing me problems, is it correct to assume that the nuget binaries are debug builds? If so, is there any reason why they should be debug and not release builds?

**Comment by filoe** [comment]
Sorry for the late response. Was injured ...
The builds should be release builds. However, mistakes occur. I'll check that.
