### ISSUE TITLE
How to tell which file type is loaded ?

### ISSUE THREAD

**Issue by mozzak** [filoe/cscore#333]
Hi there,

In my application I need to determine the file type (mp3, wav, aiff). All other types are not allowed.

Once I read the file like this

var codec = CodecFactory.Instance.GetCodec(filepath);

How can I now determine the actual file type ?

P.S. I know I could examine the file extension but a user could fake another type. 
Reason is: The processing that happens afterwards only works for these 3 types. I need to catch it if a user fakes a type (changes the file extension).

thanks for your help.

**Comment by mozzak** [comment]
Is this still an active library ?

**Comment by filoe** [comment]
Sorry for the late response. Was injured ...
I'm sorry but this library does not support that out of the box.
The input type will be abstracted through various decoders. 
You could fork the project and adjust the FfmpegDecoder. 
Make the `_formatContext` field public. It has a field named `iformat` which indeed should give you some details on the input format.
