### ISSUE TITLE
Remove conditional access - breaks VS2013 support

### ISSUE THREAD

**Issue by maddinthegreat** [filoe/cscore#334]
Hello folks,

i understand that you like the conditional operator extensions of C#, but it breaks compilation in earlier versions of VS. I'm using VS2013.

Could please remove like **DeviceRemoved?.Invoke** and **nameof()-operator** to support VS2013 in future?

Regards
Martin

**Comment by filoe** [comment]
Well, we've got 2018. C#7 is kind of standard.
Why do you still need it?

**Comment by maddinthegreat** [comment]
Hello,

i have VS2013 and i'm still happy with it. Look when somebody uses VS2010/2013 he have to update to 2015 just to use your project. Sometimes it is not always to do so because it will break some other constraints in some bigger projects. 
On the other hand newer Visual Studios are not always better, so my thought was to be kinda compatible with at least 2 lower VS-versions and to not always use the latest syntactic compiler sugar.

BTW some of ReSharper hints to enhance your code can have some bad side effects.
I patched the code myself.

It's mainly nameof() and .? operator.

Regards
Martin

**Comment by filoe** [comment]
Got currently stuck to bed :-(
If you can provide a propper pull request, I can merge it. 
But anyway, there were plans to port cscore to netstandard which would mean that it would be incompatible anyway. Also take in mind that most of the active open source projects already use c#7. Take in mind to upgrade your vs.

**Comment by maddinthegreat** [comment]
Hallo Florian,

alles klar! Mach wie du denkst. Ich komm klar.

Gute Besserung!
