### ISSUE TITLE
Not closing stream in WaveFileReader

### ISSUE THREAD

**Issue by HenKun** [filoe/cscore#336]
https://github.com/filoe/cscore/blob/2ddcf6b646932e9f4c2adc684b0800f6df937257/CSCore/Codecs/WAV/WaveFileReader.cs#L46

Is it right that the stream is closed, when it is injected to the Reader? Shouldn't be the variable set to false in this scenario and only to true if a filepath is injected?

Edit: Seems in other implementations like DmoMp3Decoder it is done correctly and _closeStream is left on false if stream is constructor injected

**Comment by filoe** [comment]
Sorry for the late response. Was injured ...
You are right. The stream should be closed. 
I'm currently not able to develop. Maybe you could create a pull request? I'll merge it.
Thanks!
