### ISSUE TITLE
Playing files with special characters: avformat_open_input returned 0xfffffffe: No such file or directory

### ISSUE THREAD

**Issue by digimezzo** [filoe/cscore#344]
On some systems, trying to play audio files containing special characters using FFMpegDecoder causes this exception:

`avformat_open_input returned 0xfffffffe: No such file or directory. StackTrace:    at CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)`

The offending characters in this case are: "à", "æ", "ø". Example of files that cannot be played:

* Sigur Rós - Sæglópur.mp3
* 105-Save Me (feat. Susanne Sundfør).mp3

The problem with this issue is that it is not reproducible on my computer (Windows 10 Pro, x64, en-US). So I'm not sure what to think of it. It has however been reported by 2 different users so far.
It could be related to #298, but I am honestly not sure.

**Comment by filoe** [comment]
Does d35ac30ae25af3e01f54d812e91034ca524a1cbb fix the problem?

**Comment by digimezzo** [comment]
Sorry for the late reply. I've asked the user if I can sent him a test application to verify this. As the issue is not reproducible on my computer, it makes it hard to verify.

**Comment by digimezzo** [comment]
The user has confirmed that the issue is fixed. I'm closing this issue.
