### ISSUE TITLE
own decoder

### ISSUE THREAD

**Issue by furesoft** [filoe/cscore#349]
how can i create my own decoder/encoder for custom audio file format?

**Comment by filoe** [comment]
Basically write the decoder which has to implement `IWaveSource` or `ISampleSource` (prefer IWaveSource). 
The main part is the `Read` method. Make sure to fill the buffer with pcm or ieeefloat32 data. Return that format through the `WaveFormat` property and you're done. Seeking is optional (`CanSeek`, `Position`, `Length`). The encoder is quite straight forward. There are no restrictions. 
You can for example take a look at the `RawDataReader` or the `WaveFileReader` to see how it basically works.
