### ISSUE TITLE
Constant playback from microphone using WaveOut

### ISSUE THREAD

**Issue by levonravel** [filoe/cscore#356]
I think I figured it out but I cant hear anything from the speakers modified coded below

`private WaveIn _lineIn;
    private WaveOut _lineOut;
    private SoundInSource _waveProvider;
    public int Latency;

    public void Start()
    {
        //Setup Microphone In
        _lineIn = new WaveIn();
        _lineIn.DataAvailable += _lineIn_DataAvailable;
        _lineIn.Initialize();
        _lineIn.Start();

        //Setup Audio Out
        _waveProvider = new SoundInSource(_lineIn);
        _lineOut = new WaveOut(Latency);
        _lineOut.Initialize(_waveProvider);
        _lineOut.Volume = 1;
        _lineOut.Play();
    }

    private void _lineIn_DataAvailable(object sender, DataAvailableEventArgs e)
    {
        _waveProvider.Read(e.Data, 0, e.ByteCount);        
    }

    private void OnApplicationQuit()
    {
        _lineIn.Stop();
        _lineIn.Dispose();
        _lineOut.Stop();
        _lineOut.Dispose();
    }`

**Comment by filoe** [comment]
No need to make it this complicated:

```
var soundIn = new WasapiCapture();
var soundInSource = new SoundInSource(soundIn)
{
	FillWithZeros = true
};
soundIn.Initialize();
soundIn.Start();

var soundOut = new WasapiOut();
soundOut.Initialize(soundInSource);
soundOut.Play();
```

**Comment by copa017** [comment]
Hi !
Is this also the correct approach for my situation?
I am getting audio PCM from a bluetooth device by its API and want to play it on the speakers.
I tried before with RawDataReader as IWaveSource, but ISoundOut stops when the buffer is empty / or when bluetooth lags :-(

On your example here with SoundInSource: where can I specify the WaveFormat (it is write protected)?

**Comment by filoe** [comment]
See https://github.com/filoe/cscore/issues/403
