### ISSUE TITLE
DmoException when configuring DmoWavesReverbEffect

### ISSUE THREAD

**Issue by lukasz-matylla** [filoe/cscore#36]
I'm using CSCore from the latest stable NuGet package (version 1.0.0).

I'm trying to use DmoWavesReverbEffect in my code. When I set the properties of the DmoWavesReverbEffect object, I often get a DmoException thrown from SetValue, with message:
IDirectSoundFXWavesReverb::SetAllParameters caused an error: 0x80070057, "The parameter is incorrect.".

This happens in spite of all the values being in range (that is, between minimum and maximum values as specified in DmoWavesReverbEffect constants). For example, ReverbTime = 2f causes an exception (should accept anything between 0.001 and 3000); HighFrequencyRTRatio = 0.5f does, too (should accept anything between 0.001 and 0.999). ReverbMix does not accept any negative value, while the range is -96 to 0.

**Comment by filoe** [comment]
Please use this prerelease: https://www.nuget.org/packages/CSCore/1.1.0-beta2.

**Comment by lukasz-matylla** [comment]
Thank you very much. It works on 1.1.0 beta2.
