### ISSUE TITLE
Play mp3 on Windows XP Pro 2002 SP3

### ISSUE THREAD

**Issue by kaniffol** [filoe/cscore#362]
my program must play .mp3 files, on windows 7...10 - it's working, but on windows xp - not working, error [**not found mfplat.dll**], i downloaded, but he is not working! (sorry bad english)
![2030](https://user-images.githubusercontent.com/42143854/43717769-9aaa5228-9999-11e8-94b5-bd8e4c0d4dfc.png)
error not found mfplat.dll
![2027](https://user-images.githubusercontent.com/42143854/43717674-4b6b7638-9999-11e8-938e-5b0b721a5da0.png)
download mfplat.dll
![2028](https://user-images.githubusercontent.com/42143854/43717677-4eed7180-9999-11e8-8a3a-3e9694e566ca.png)

**Comment by filoe** [comment]
Windows XP is not supported any longer.
