### ISSUE TITLE
Append Equalizer on SampleSource

### ISSUE THREAD

**Issue by CGunna** [filoe/cscore#364]
Maybe I am doing something wrong, but I am trying to append an Equalizer to an ISampleRate object I created a few calls before. But for some reasons the equalizer does not affect my playback. 
This is strange because when I am doing it the same way as in the Equalizer Test example, it works. But in the test example the Equalizer is created in the same call as the ISampleRate - for UI reasons I would like to decouple this call.

In my case I implemented a function which creates a ISoundOut and returns an ISampleSource. 
In another function  I am calling:

            this.equalizer = this.sampleSource.AppendSource(Extensions.Create15BandEqualizer);

So the equalizer is created based on the exact same ISampleSource object. 
After this call I am initializing the ISoundOut and start playing: 

          _soundOut.Initialize(sampleSource.ToWaveSource());
           _soundOut.Play();

Is there a reason why this is not working?

**Comment by filoe** [comment]
You have to init the soundout with the Equalizer. 

Von meinem iPhone gesendet

**Comment by CGunna** [comment]
ok I see, thank you - works perfect!
