### ISSUE TITLE
SimpleMixerSample length and position solution

### ISSUE THREAD

**Issue by ghost** [filoe/cscore#365]
I need make changes in my IWaveSource Read function, so i used code from simplemixersample project. But as you know there are not implemented length and position vars. What can I do or use to fix it?

UPD: Or maybe there is another solution with editing Read function without overriding IWaveSource?

**Comment by filoe** [comment]
What do you mean by editing?

**Comment by impactfulloneliness** [comment]
Creating my own implementation of Read function I meant. I need to work with buffer to get gapless effect for audio playback, but with that I have not idea how to implement position changing possibility.

**Comment by impactfulloneliness** [comment]
I solved this by using original iwavesources. i realized that position value changes after using iwavesource's read function. nevertheless i still want to understand how can i implement position with help of reader or without it,
