### ISSUE TITLE
stopping the play back is not releasing the file

### ISSUE THREAD

**Issue by Tonyjxavier** [filoe/cscore#366]
I am trying to create an application which plays a wave file. I want to delete the wave file immediately after the playback stops but the file wont get released 
`
cleanUpPlayback();
			source = CodecFactory.Instance.GetCodec(filename)
			.ToSampleSource()
			.ToMono()
			.ToWaveSource();
			_soundOut = new WaveOut();
			_soundOut.Initialize(source);
	_soundOut.Play();
       Thread.sleep(5000);
       _soundOut.Stop();
cleanUpPlayback();
 private void cleanUpPlayback()
		{
			if(source!=null)
			{
				
				source.Dispose();
				source = null;
			}
			if (_soundOut != null)
			{
				_soundOut.Dispose();
				_soundOut = null;
			}
			
		}      

`

**Comment by filoe** [comment]
What kind of decoder does the codecfactory return? Is Dispose really being called on the source obj?
