### ISSUE TITLE
Question: apply LowShelfFilter

### ISSUE THREAD

**Issue by CGunna** [filoe/cscore#367]
I am trying to apply a LowShelf Filter to an existing "wav" File and pass it to a SoundOut object.
I googled quite a long time but I have found no way to pass or append this filter to the existing sample source or soundOut objects.

The workflow is the following:

1) I am recording something and save it as wav file
2) Then I want to apply the LowShelf Filter to it and either pass it to a SoundOut object or save it again to a file (which would be a compromise)

Is there an easy way to realize this (like with DMO.Effects or EqualizerFilters)?

Thanks for your help

**Comment by filoe** [comment]
Take a look at the BiQuadFilterSample sample. There is also a LowShelfFilter available.
