### ISSUE TITLE
How to use delay, LPF and reverb in X3DAudioCore?

### ISSUE THREAD

**Issue by lukasz-matylla** [filoe/cscore#37]
The X3DAudioCore.X3DAudioCalculate method can calculate not only channel mixing matrix, but also several other parameters. Unfortunately, neither the library source code nor the samples show any way of applying them to a voice - the X3DAudioSample only uses matrix.

Is there a chance of getting a sample of using more of X3DAudio functionality? Or is this functionality not yet implemented in CSCore?

**Comment by filoe** [comment]
Take a look at the following document: https://msdn.microsoft.com/en-us/library/windows/desktop/ee415798%28v=vs.85%29.aspx
CSCore provides most of the XAudio2 features.

**Comment by lukasz-matylla** [comment]
Thank you. This partially answers my question.

Does CSCore provide API for creating, attaching and configuring effects and effect chains (for example, a wrapper for XAudio2CreateReverb)? Or do I need to create them through C++ code?

**Comment by filoe** [comment]
I would recommend you to use the DmoWavesReverbEffect instead or why do you need exactly the XAudio2ReverbEffect?

**Comment by lukasz-matylla** [comment]
I am currently using DmoWavesReverbEffect. The problem is, it's something that acts on a source and as such, does not give the intended results in a 3d scene (with 5.1 or 7.1 speakers). 

What I need to get is sound sources being directional, but the reverbed sound being omnidirectional. The best way of implementing it that I've found for now is using a submix voice, with the reverberation applied to the submix only, not the sources (to keep the directional sound from the sources reverb-free). And that's the reason for using reverberation that I can put into a voice's effect chain.

Unless I missed something, CSCore has methods for setting up an effect chain for a source or submix voice, but not for creating the effects themselves.

**Comment by filoe** [comment]
Sorry for the late response. But you're right. There is currently no real support for xaudio2 effect chains. But if you wish me to add this to the feature list, I can do so.

**Comment by filoe** [comment]
I'll close it for now. But it is marked as "open feature request". Hopefully we'll come back to this.
