### ISSUE TITLE
Looking for a resampler to resample a 250kHz signal down to 192kHz.

### ISSUE THREAD

**Issue by tomb18** [filoe/cscore#372]
Hi I saw this library and it looks simple enough for my needs.  What I need to do is to resample a signal which is at 250kHz down to 192kHz.
I currently do the following downsampling in another part of my software for a different device.  In this case the original signal provide 2 channels of int16 data at a rate of 1.92MHz.  The data is collected and converted into 1 16384 double array per channel.  Each of these buffers are sent to a low pass FIR filter and then the output of the filter is again 16384 doubles per channel.  At that point I keep 1 out of 10 samples (the downsampling) until I get 16384 doubles in each channel and I send them out to an audio output class.  This works as expected.
Now this other device I have provides 250kHz sampled buffers.  Each is 16384 bytes of doubles.  Now to do the resampling like I did in the other case required upsampling by 96 and then downsampling by 125.  A real mess.
So looking at your library, I don't understand how the input and output buffers would be handled.  Can you give some pointers please?  The data will be delivered continuously until the application is closed.
Thanks, Tom

**Comment by filoe** [comment]
There is a resampler implementation using the windows os resampler. 
You can provide a stream to it and read data from it until no further data is returned.
You can take a look at this one on how to use it: https://github.com/filoe/cscore/blob/af1792ea680743c5172ece4727e2b331012e99de/CSCore.Test/DMO/ResamplerTests.cs#L26
You can resplace the source by a file, by a continues stream, etc. See the other samples on how to load files, ...
