### ISSUE TITLE
How to apply Equalizer to soundInSource created by WASAPICapture or WASAPILoopbackCapture?

### ISSUE THREAD

**Issue by JohnsonGao** [filoe/cscore#381]
Hi Florian, I can play the captured stream now, but failed to append an Equalizer for the SoundInSource, So where is the problem for this? How should I apply EQ to a captured stream? Codes here but it doesn't work. Thanks a lot!

var _soundInSource  = new SoundInSource(_soundIn)
{ FillWithZeros = true };

_soundInSource  
 .ToSampleSource()
 .AppendSource(Equalizer.Create10BandEqualizer, out _equalizer)
 .ToWaveSource();

var soundOut = new WasapiOut();
soundOut.Initialize(soundInSource);
soundOut.Play();

**Comment by filoe** [comment]
Hi @JohnsonGao,
you have to initialize the soundOut with the result of the whole chain. That means:
```
**IWaveSource source =** _soundInSource
.ToSampleSource()
.AppendSource(Equalizer.Create10BandEqualizer, out _equalizer)
.ToWaveSource();
...
soundOut.Initialize(**source**);
...
```
