### ISSUE TITLE
AacDecoder requires at least 3 frames to decode

### ISSUE THREAD

**Issue by Prazlin** [filoe/cscore#386]
I'm decoding AAC encoded audio data from an rtsp stream using AacDecoder. I copy the data into a Memory Stream, ms, and pass ms to the AacDecoder constructor. It works when ms contains at least 3 frames of data, but when it has less than this number I get the exception

CSCore.MediaFoundation.MediaFoundationException occurred
  HResult=0xC00D36C4
  Message=Interops::MFCreateSourceReaderFromByteStream caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported.".

I want to be able to decode the frames as fast as possible after they are received over the rtsp stream and not have to buffer at least 3 frames before decoding.

**Comment by filoe** [comment]
Try to use the Ffmpeg implementation. Can't do anything about what's going on inside of the mediafoundation.
