### ISSUE TITLE
Question: Real-time AAC encoding of data from SoundInSource?

### ISSUE THREAD

**Issue by jeremywho** [filoe/cscore#388]
I want to take the data coming in via microphone and encode it to AAC to be sent over the network. 

The samples make it easy to understand how to get pcm data via the mic, but I'm having trouble understanding if its possible to then encode those bytes to AAC. MFE or any other available framework would be fine.

Is this possible?

**Comment by Ambusy** [comment]
There is a MediaFoundationEncoder.CreateAACEncoder(stereoSource.WaveFormat, filename). You would have to modify the encoder not to write to a file but to the internet. But perhaps Filoe knows a better solution.

**Comment by filoe** [comment]
The MediaFoundationEncoder can store data to a stream. You can implement any stream which will handle the Write calls correctly to stream it to any network.
