### ISSUE TITLE
What's the resample format should to be set for FFmpeg resampling?

### ISSUE THREAD

**Issue by JohnsonGao** [filoe/cscore#389]
I'm using ffmpeg swr_convert to resample audio stream from cscore captured bytes array. Firstly I need to create the SwrContext* by calling the ffmpeg API swr_alloc_set_opts, you know, there are three params in this FFmpeg.AutoGen API is about samples_In:

            public static SwrContext* swr_alloc_set_opts(SwrContext* s, long out_ch_layout, 
            AVSampleFormat out_sample_fmt, int out_sample_rate, long in_ch_layout, AVSampleFormat 
            in_sample_fmt, int in_sample_rate, int log_offset, void* log_ctx); 

I need to know the AVSampleFormat param corresponding to CSCore WasapiLoopbackCapture :

            using (_soundIn = new WasapiLoopbackCapture(0))
            {
                _soundIn.Initialize();
                
                var soundInSource = new SoundInSource(_soundIn);
                ISampleSource sourceSample = soundInSource.ToSampleSource();
                IWaveSource _sourceWave16 = sourceSample.ToWaveSource(16).ToStereo();

                byte[] buffer = new byte[_sourceWave16.WaveFormat.BytesPerSecond];
                soundInSource.DataAvailable += (s, e) =>
                {
                            int read;
                            while ((read = _sourceWave16.Read(buffer, 0, buffer.Length)) > 0)
                                SendAudioSamplesToFFmpeg(buffer, read, DateTime.Now);
                };

                _In_Channels        = _sourceWave16.WaveFormat.Channels;
                _In_Sample_Rate     = _sourceWave16.WaveFormat.SampleRate;
                _In_BytesPerSample  = _sourceWave16.WaveFormat.BytesPerSample;
                _In_SampleFormat    = ?

            }

            _swrContext = ffmpeg.swr_alloc_set_opts(null,
                                                    ffmpeg.av_get_default_channel_layout(_audioCodecContext->channels), //AV_CH_LAYOUT_STEREO
                                                    _audioCodecContext->sample_fmt,
                                                    _audioCodecContext->sample_rate,
                                                    ffmpeg.av_get_default_channel_layout(_In_Channels), //AV_CH_LAYOUT_STEREO
                                                    _In_SampleFormat, //=AVSampleFormat.AV_SAMPLE_FMT_S16 ?
                                                    _In_Sample_Rate,
                                                    0,
                                                    null);
           ffmpeg.swr_init(_swrContext);

So how to set the _In_SampleFormat param value ? Can I set to AVSampleFormat.AV_SAMPLE_FMT_S16 in ffmpeg enum value? Would you please provide a mapping table between CSCore pcm and ffmpeg AVSampleFormat? Furthermore how about the place mode in bytes array: packed? or planar ?

Thank you very much in advance!

**Comment by filoe** [comment]
It corresponds to the WaveFormatTag of the WaveFormat.
As long as you are on windows, you also could use the built in resamplers of cscore.

**Comment by JohnsonGao** [comment]
throw new NotSupportedException("Audio Sample Format not supported."

**Comment by JohnsonGao** [comment]
According to WaveFormatTag, WasapiLoopback Capture got AudioEncoding Extensible enum value,
        /// <summary>Extensible</summary>
        Extensible = unchecked((short)0xFFFE), // Microsoft 
However in the GetSuggestedWaveFormat, reverse mapping will  throw out exceptions.
        default:
                    throw new NotSupportedException("Audio Sample Format not supported.");
So What's the mapping rules?

**Comment by filoe** [comment]
There are no rules, as I said you have to map it manually.
