### ISSUE TITLE
Specify Audio Device

### ISSUE THREAD

**Issue by UnleavenedEagle** [filoe/cscore#399]
Hello it might be a bit of a stupid question, but I can't seem to figure out how to specify an audio input/output device for a WaveCapture or WasapiCapture.

```
WasapiCapture input = new WasapiCapture();
input.Device = // This has to be an MMDevice
```

The problem is, I don't know where can I get an `MMDevice` from. I tried enumerating them, but I got to a dead end.

What I could achieve is enumerating all the `WaveInDevice`s and `WaveOutDevice`s.

Is there any way to convert a `WaveInDevice` to a `MMDevice` or somehow get a list of all input `MMDevice`s?

**Comment by InlineAsm** [comment]
Use
`MMDeviceEnumerator.TryGetDefaultAudioEndpoint(DataFlow.Capture, Role.Multimedia)`

Or pick one from:
`MMDeviceEnumerator.EnumerateDevices(DataFlow.Capture, DeviceState.Active)`
