### ISSUE TITLE
Question: Get info from SystemMediaTransportControls

### ISSUE THREAD

**Issue by steam3d** [filoe/cscore#405]
Does it possible to get info from SystemMediaTransportControls (see screenshoot) using cscore?
![image](https://user-images.githubusercontent.com/30986874/77517440-2ba68980-6e8d-11ea-8100-afc3987d0668.png)

**Comment by filoe** [comment]
I am sorry, but no. Also it is not planned for the future since outside of the samples, cscore does not interact with ui.
