### ISSUE TITLE
DirectSoundOut is not initialized.

### ISSUE THREAD

**Issue by lvjunlei** [filoe/cscore#42]
My code like this，but it‘s not work

public void Play(string fileName)
        {
            using (var ss = CodecFactory.Instance.GetCodec(fileName))
            {
                using (var so = new DirectSoundOut())
                {
                    so.Initialize(ss);
                    var time = ss.GetTime(ss.Length);
                    
                    so.Play();
                    Thread.Sleep((int)time.TotalSeconds * 1000);
                    so.Stop();
                }
            }
        }

thank you！

**Comment by filoe** [comment]
This is a very old bug. Please use the latest beta release from nuget: https://www.nuget.org/packages/CSCore/1.1.0-beta2
