### ISSUE TITLE
CSCore.Ffmpeg not available for NuGet package

### ISSUE THREAD

**Issue by zipswich** [filoe/cscore#424]
I installed CSCore NuGet, but CSCore.Ffmpeg does not seem to be available.

**Comment by filoe** [comment]
It is in beta. Make sure to enable preview versions in the nuget package explorer or install it from command line using `dotnet add package CSCore.Ffmpeg --version 1.2.0-beta1`

**Comment by zipswich** [comment]
Thank you.
