### ISSUE TITLE
WritableBufferingSource: Return value of Write(byte[],int,int)

### ISSUE THREAD

**Issue by LasterOfDesaster** [filoe/cscore#43]
What ist the Return Value of the Write Method in WritableBufferingSource used for?
Against all MSDN conventions, this Write Method has a return value of type Int32. In every .NET (Stream)Classes, I found, there was the signature "void Write(...)"
I assume, according to the Read method, this value indicates, how much bytes are written, but I'm not sure.
Thanks!

**Comment by Nippius** [comment]
Yes it indicates how much bytes were written to the internal buffer. The Write() method just call the FixedSizeBuffer.Write() method. 

The FixedSizeBuffer internally uses a array as the buffer an so it returns how many bytes were actually written to the array. If the returned value is less then the buffer size passed to the WriteableBufferingSource.Write() then not all bytes of the buffer were successfully written.

As a side note, Writeable is misspeled. should be Writable (like in this issue title)

**Comment by LasterOfDesaster** [comment]
Ok thanks for answering my question

PS: I didn't even noticed that it was misspelled ;D

**Comment by filoe** [comment]
@Nippius is absoluetely right. Thanks for answering!
