### ISSUE TITLE
"Unknown HRESULT" when try to get PropertyStore items

### ISSUE THREAD

**Issue by steam3d** [filoe/cscore#433]
This my code
```
using (var enumerator = new MMDeviceEnumerator())
{
	var audioEndpoints = enumerator.EnumAudioEndpoints(dataFlow, DeviceState.All);

	foreach (var audioEnd in audioEndpoints)
	{
		foreach (var property in audioEnd.PropertyStore)
		{
			Console.WriteLine(String.Format("{0} | {1} : {2} | {3}", property.Key, property.Key.GetType(), property.Value, property.Value.GetType()));
		}
	}
}
```
I got the error
> CSCore.Win32.Win32ComException: 'IPropertyStore::GetValue caused an error: 0xe000020b, "Unknown HRESULT".'

I found that audioEndpoints have **{CSCore.CoreAudioAPI.MMDevice}** when you try to get FrendlyName you get this error.

![image](https://user-images.githubusercontent.com/30986874/98129710-7e87fb00-1eca-11eb-9217-d3f94cfc33e9.png)

**Comment by barrien2** [comment]
Does changing DeviceState.All to DeviceState.Active fix it? I think there's an issue with disabled devices

**Comment by steam3d** [comment]
You are right, better way just skip device that rise error when using DeviceState.All
