### ISSUE TITLE
Split Audio

### ISSUE THREAD

**Issue by engmohamedsalah** [filoe/cscore#435]
How I can use this library to split audio into chunks
for example, I have an audio file with a size of 100 seconds 
I need to cut that into small files from as following
a file contains the audio from second 0 to second 4
a file contains the audio from second 23  to second 40
a file contains the audio from second 80 to second 90

**Comment by filoe** [comment]
1. Open the audio file using the `CodecFactory`
2. Convert e.g. 4 seconds to the number of bytes you have to read by calling the extension method `GetRawElements` using the created `IWaveSource` returned in step one
3. Read the number of bytes using the `Read` method of the `IWaveSource` object
4. Save the read data to a file. For example, you could use the `WaveWriter` and repeat step 3 and 4.
