### ISSUE TITLE
Play stereo mp3 as mono on specyfic channel in 7.1

### ISSUE THREAD

**Issue by dewelooper** [filoe/cscore#439]
Hello,
I need play concurently different mp3 files from my C# app on different playback zones in amplifier (regions in building). 
I have audio infrastructure which is terminated on 3 audio jacks 3,5mm connected to 3 available outputs in my usb 7.1 sound card.

Is this possible using CSCORE? Which way I can do that?

**Comment by filoe** [comment]
So you want to play mp3-1 on channel1, mp3-2 on channel2, etc.?
It would be possible. You would have to write a custom SampleSource which takes multiple sample sources as input and mix it manually. If I got you right, I can assist you.
