### ISSUE TITLE
waitHandle not returning

### ISSUE THREAD

**Issue by cmdrmcdonald** [filoe/cscore#44]
I have a piece of code that generates a wave file using Microsoft Speech Synthesizer and plays it:

            SpeechSynthesizer synth = new SpeechSynthesizer();
            using (MemoryStream stream = new MemoryStream())
            {
                synth.SetOutputToWaveStream(stream);
                synth.Speak("This is a test.");
                stream.Seek(0, SeekOrigin.Begin);
                IWaveSource source = new WaveFileReader(stream);
                EventWaitHandle waitHandle = new EventWaitHandle(false, EventResetMode.AutoReset);
                var soundOut = new WasapiOut();
                soundOut.Initialize(source);
                soundOut.Stopped += (s, e) => waitHandle.Set();
                soundOut.Play();
                waitHandle.WaitOne();
                soundOut.Dispose();
                source.Dispose();
            }

This works fine when I run it standalone, but when running it as part of a plugin for another program it hangs on `waitHandle.WaitOne()` and never returns.  Is there a bug here or am I missing something in the code to avoid this potential situation?

**Comment by filoe** [comment]
Well I don't really know the reason. You could download the source of the repo and debug the PlaybackProc of the WasapiOut class.
