### ISSUE TITLE
[MediaFoundationException] Decode Stream using MediaFoundationDecoder

### ISSUE THREAD

**Issue by steam3d** [filoe/cscore#447]
I can't figure out what i did wrong. Here is my code:

```
SpeechSynthesisStream synthesisStream = await synthesizer.SynthesizeTextToStreamAsync(text);
Stream stream = synthesisStream.AsStream();
var waveSource = new MediaFoundationDecoder(stream);
```
At line 3 i get `Exception thrown: 'CSCore.MediaFoundation.MediaFoundationException' in CSCore.dll` but program still works  i can then send `waveSource` to media player and it will play.

I tried to catch 

```
try{
    var waveSource = new MediaFoundationDecoder(stream);
}
catch{
***
}
```
but obviously it never happens 

Maybe is there way to get more more detailed error?

**Comment by filoe** [comment]
Does it really throw the exception or is it just in the logs?

**Comment by steam3d** [comment]
Just in the logs

**Comment by filoe** [comment]
So just ignore it. It gets handled by CSCore.
