### ISSUE TITLE
Pitch effect bug - after sometimes generate muted audio

### ISSUE THREAD

**Issue by victorvhpg** [filoe/cscore#455]
The audio stay "mute" after sometime using effect Pitch with differents sources many times.

https://github.com/filoe/cscore/blob/13bbebb4f0a8c3e12fc54a01c3485098bf13ba9c/CSCore/DSP/PitchShifterInternal.cs

**Comment by victorvhpg** [comment]
My application run in many threads, there are concurrent access to pitch effect, 
And that class (PitchShifterInternal) uses static Fields 

https://github.com/filoe/cscore/blob/13bbebb4f0a8c3e12fc54a01c3485098bf13ba9c/CSCore/DSP/PitchShifterInternal.cs

At sometime a thread change the value of a Field that is shared in ALL threads, then occurs the bug.

@filoe 
To solve this bug, dont use static fields in PitchShifterInternal
(field: _gRover)

**Comment by filoe** [comment]
Thanks for reporting! Can you submit a pull request?

**Comment by victorvhpg** [comment]
#457 
54e4008

**Comment by victorvhpg** [comment]
> Thanks for reporting! Can you submit a pull request?

ok,  [54e4008](https://github.com/victorvhpg/cscore/commit/54e40084cf1dd57ed3879adfec7e7bc23eb561a3)

**Comment by victorvhpg** [comment]
@filoe  
please merge theses changes too  #458 
https://github.com/filoe/cscore/pull/458
