### ISSUE TITLE
Play beyond the end of a WAV for effect

### ISSUE THREAD

**Issue by cmdrmcdonald** [filoe/cscore#46]
If I add an echo effect to a wav file it all works fine except for when the source reaches its end, at which point the echo is killed.  For example:

            SpeechSynthesizer synth = new SpeechSynthesizer();
            using (MemoryStream stream = new MemoryStream())
            {
                synth.SetOutputToWaveStream(stream);
                synth.Speak("This is a test.");
                stream.Seek(0, SeekOrigin.Begin);
                IWaveSource source = new WaveFileReader(stream);
                EventWaitHandle waitHandle = new EventWaitHandle(false, EventResetMode.AutoReset);
                var soundOut = new WasapiOut();
                DmoEchoEffect echoSource = new DmoEchoEffect(source);
                soundOut.Initialize(echoSource);
                soundOut.Stopped += (s, e) => waitHandle.Set();
                soundOut.Play();
                waitHandle.WaitOne();
                soundOut.Dispose();
                source.Dispose();
            }

The echo is cut off as soon as the end of the primary WAV is reached.  How can I tell CSCore to play for a given time beyond the end of the WAV file to allow the effects time to run out?

**Comment by filoe** [comment]
Well, you could append some silence for the duration of the echo effect. There is no other possiblity.

**Comment by cmdrmcdonald** [comment]
Is there a code sample that shows how I could do this?

**Comment by filoe** [comment]
No but it should be quite easy to implement.
Just some inspiration: 

`IWaveSource waveSource = ...
waveSource = waveSource
	.AppendSource(x => new ExtendDurationWaveSource(x, 2000))
	.AppendSource(x => new DmoEchoEffect(x){ LeftDelay = 2000, RightDelay = 2000 })

public class ExtendDurationWaveSource
	: WaveAggregatorBase
{
	private int bytesToExtend;

	public ExtendDurationWaveSource(IWaveSource waveSource, int milliSecondsToExtend)
		: base(waveSource)
	{
		bytesToExtend = waveSource.GetRawElements(milliSecondsToExtend);
	}
	
	public override int Read(byte[] buffer, int offset, int count)
	{
		int read = BaseSource.Read(buffer, offset, count);
		if(read < count)
		{
			int diff = count - read;
			
			diff = Math.Min(diff, bytesToExtend);
			
			if(diff > 0)
			{
				Array.Clear(buffer, offset, diff);
			}
			
			bytesToExtend -= diff;
			
			return diff;
		}
		return read;
	}
}`

**Comment by cmdrmcdonald** [comment]
Great, thanks for this.  I've used it to solve me problem.

Thanks again
