### ISSUE TITLE
ALSoundOut in NuGET package

### ISSUE THREAD

**Issue by refoscodoc** [filoe/cscore#463]
Hi everyone and sorry in advance if the question is redundant.

I'm a beginner anyways and I feel like I might just missing something basic, although this is giving me headaches.

I am using the CSCore  package from NuGET for a simple gRPC app and it seems to be all working fine, except that I'm on Linux and in the standard package I get from NuGET there's no ALSoundOut class, while I only see it in the openal branch.

What am I missing? Is there a different package I can download?

Thanks in advance and have mercy with the replies!

**Comment by filoe** [comment]
I am afraid that the nuget version is to okd and does not contain the AL implementation yet. Should update it …

**Comment by refoscodoc** [comment]
Oh, thank you very much for the prompt reply!

I see :/

Soooo no chances, let's say? It's not important, just a tiny personal project, but it'd be nice. Eh, anyways. Thanks a  lot

**Comment by filoe** [comment]
You can always build the project yourself. But maybe I am really gonna update it …

**Comment by refoscodoc** [comment]
No no don't bother! I'll build it myself. Thanks a lot for the feedback :D
