### ISSUE TITLE
Playing Samples

### ISSUE THREAD

**Issue by dwebb7** [filoe/cscore#47]
Is it possible to write samples to an output in a IWaveSource. I am pulling the audio through my application using a buffer so it will still work if there is no audio output available but I would like to allow the user to monitor if there ia an audio out. So, can I play audio from a IWaveSource. I hope this makes sense.

Thanks,
Dan

**Comment by filoe** [comment]
Of course that is possible. Check out the `WriteableBufferingSource` class.

**Comment by dwebb7** [comment]
Got it! That is what I needed. Thanks for pointing me in the right direction.

**Comment by dwebb7** [comment]
Can I ask another question about this. I am using the DataAvailable event
to call the Read method on a wavesource to pull data through my
application. How do I know what count to use on the read method?

On Wed, Feb 24, 2016 at 4:13 PM, Florian Rosmann <notifications@github.com>
wrote:

> Closed #47 <https://github.com/filoe/cscore/issues/47>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filoe/cscore/issues/47#event-564453228>.
>



-- 


 2 Corinthians 13:14

**Comment by filoe** [comment]
You can't really know that. The EventArgs object provides the number of bytes available but these won't fit to your modified source.

**Comment by dwebb7** [comment]
So what is a good way to pull data through? Is the DataAvailable event how
I use the WriteableBufferingSource?

On Fri, Feb 26, 2016 at 2:39 PM, Florian Rosmann <notifications@github.com>
wrote:

> You can't really know that. The EventArgs object provides the number of
> bytes available but these won't fit to your modified source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filoe/cscore/issues/47#issuecomment-189475100>.
>



-- 


 2 Corinthians 13:14

**Comment by dwebb7** [comment]
Sorry I didn't read all you last response before posting the last message. 
That is what I'm doing now and it makes my peak meters do weird things. When wasipiout was pulling the data they worked flawlessly. If I set the buffer size real low the meters freeze. If I set it real high it seems to work okay except the peak hold hovers above the meter a lot. It seems wasipiout does it just right. Any suggestions?

**Comment by filoe** [comment]
Could you please provide some sample code?

**Comment by dwebb7** [comment]
It appears that my problem is being caused by the PeakMeter class. If I set the interval to 100ms it can't keep up, or something, an doesn't fire at the proper interval. Which is what was causing my weird peak hold behavior in my custom peak meter control. See the attached code which prints the time in milliseconds since the last time the PeakMeter fired.

BTW, Can you stop the WaveIn thread from repeatably printing to the debug window?

`public partial class MainWindow : Window

    {

        private readonly IWaveSource _waveSource;
        private readonly byte[] _buffer;
        private readonly WriteableBufferingSource _writeableBufferingSource;
        private readonly WaveIn _waveIn;
        private readonly WasapiOut _wasapiOut;
        private DateTime _lastTime;

        public MainWindow()
        {
            InitializeComponent();
            _waveIn = new WaveIn();
            _waveIn.Initialize();
            _waveIn.Start();
            _waveIn.DataAvailable+=waveIn_DataAvailable;
            var soundInSource = new SoundInSource(_waveIn);
            var soundSource = soundInSource.ToSampleSource();
            var peakMeter = new PeakMeter(soundSource) {Interval = 100};
            peakMeter.PeakCalculated += peakMeter_PeakCalculated;
            _waveSource = peakMeter.ToWaveSource(16);
            _buffer = new byte[_waveSource.WaveFormat.BytesPerSecond];
            try
            {
                _wasapiOut = new WasapiOut();
                _writeableBufferingSource = new WriteableBufferingSource(_waveSource.WaveFormat);
                _wasapiOut.Initialize(_writeableBufferingSource);
                _wasapiOut.Play();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        void waveIn_DataAvailable(object sender, DataAvailableEventArgs e)
        {
            int read = _waveSource.Read(_buffer, 0, _buffer.Length);
            _writeableBufferingSource.Write(_buffer, 0, read);
        }

        void peakMeter_PeakCalculated(object sender, PeakEventArgs e)
        {
            Action peakAction = () =>
            {
                ProgBar.Value = e.PeakValue;
                Debug.Print("Time - " + (DateTime.Now - _lastTime).Milliseconds);
                _lastTime = DateTime.Now;
            };
            Dispatcher.InvokeAsync(peakAction);
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _waveIn.Stop();
            _waveIn.Dispose();
            _wasapiOut.Dispose();
        }       
    }`

Thanks,
Dan

**Comment by filoe** [comment]
I don't know why you wanna do that so complicated. Why are you using the `WriteableBufferingSource`?
As far as I can see, in your example, the code can be simplified to this working version:

```
    public partial class MainWindow : Window
    {
        private readonly ISoundIn _waveIn;
        private readonly WasapiOut _wasapiOut;
        private DateTime _lastTime;

        public MainWindow()
        {
            InitializeComponent();
            _waveIn = new WaveIn();
            _waveIn.Initialize();
            _waveIn.Start();
            var soundInSource = new SoundInSource(_waveIn){FillWithZeros = true};
            var soundSource = soundInSource.ToSampleSource();
            var peakMeter = new PeakMeter(soundSource) { Interval = 100 };
            peakMeter.PeakCalculated += peakMeter_PeakCalculated;
            var waveSource = peakMeter.ToWaveSource(16);
            try
            {
                _wasapiOut = new WasapiOut();
                _wasapiOut.Initialize(waveSource);
                _wasapiOut.Play();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        void peakMeter_PeakCalculated(object sender, PeakEventArgs e)
        {
            Debug.Print("Time - " + (DateTime.Now - _lastTime).Milliseconds);
            _lastTime = DateTime.Now;
            Action peakAction = () =>
            {
                ProgBar.Value = e.PeakValue;
            };
            Dispatcher.BeginInvoke(peakAction);
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _waveIn.Stop();
            _waveIn.Dispose();
            _wasapiOut.Dispose();
        }
    }
```

**Comment by dwebb7** [comment]
My application is a recording application. It has happened where the computer which is running it didn't have speakers or headphones plugged in so there were no outputs. This causes the app to not work at all. For my app 90% of the time the user will record and upload to the internet without listening at all. So, this will allow the application to work with no inputs. If needed, even in the middle of recording, the user can plug in headphones and then monitor. 

I changed the interval to 150 and it works fine for my application. So, if you don't think this is an issue with Cscore you can close this issue. 

Thank you for your help and for developing this API. It is a huge help.

Dan

**Comment by filoe** [comment]
Well, your solution is not the ideal way. Why is my snipped not working (compared to yours)?

**Comment by dwebb7** [comment]
If the computer you are on has no outputs the meter will no longer work. Disable your outputs and try it.

**Comment by filoe** [comment]
So why don't you use something in this direction?

```
    public partial class MainWindow : Window
    {
        private readonly ISoundIn _waveIn;
        private readonly WasapiOut _wasapiOut;
        private DateTime _lastTime;

        public MainWindow()
        {
            InitializeComponent();
            _waveIn = new WaveIn();
            _waveIn.Initialize();
            _waveIn.Start();
            var soundInSource = new SoundInSource(_waveIn){FillWithZeros = false};
            var soundSource = soundInSource.ToSampleSource();
            var peakMeter = new PeakMeter(soundSource) { Interval = 100 };
            peakMeter.PeakCalculated += peakMeter_PeakCalculated;
            var waveSource = peakMeter.ToWaveSource(16);
            try
            {
                Task.Factory.StartNew(() =>
                {
                    int read = 0;
                    byte[] buffer = new byte[waveSource.WaveFormat.BytesPerSecond / 2];
                    while (true) //add any condition 
                    {
                        read = waveSource.Read(buffer, 0, buffer.Length);
                        //process data

                        //add some delay?
                        Thread.Sleep(10);
                    }
                });

                //_wasapiOut = new WasapiOut();
                //_wasapiOut.Initialize(waveSource);
                //_wasapiOut.Play();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

        void peakMeter_PeakCalculated(object sender, PeakEventArgs e)
        {
            Debug.Print("Time - " + (DateTime.Now - _lastTime).Milliseconds);
            _lastTime = DateTime.Now;
            Action peakAction = () =>
            {
                ProgBar.Value = e.PeakValue;
            };
            Dispatcher.BeginInvoke(peakAction);
        }

        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            _waveIn.Stop();
            _waveIn.Dispose();
            //_wasapiOut.Dispose();
        }
    }
}
```

**Comment by dwebb7** [comment]
That one is still firing the PeakMeter event at an inconsistent interval. Below is the time inbetween event fires.
Time - 0
Time - 150
Time - 149
Time - 1
Time - 146
Time - 144
Time - 0
Time - 147
Time - 150
Time - 1
Time - 148
Time - 146
Time - 0
Time - 145
Time - 149
Time - 1
Time - 128
Time - 168
Time - 0
Time - 128
Time - 148
Time - 1
Time - 144

**Comment by filoe** [comment]
Please consider using WasapiCapture instead of WaveIn. Compared to WaveIn, WasapiCapture is state of the art and works with a much lower latency.

**Comment by dwebb7** [comment]
The reason I switched back to WaveIn is I can't get WasapiCapture to
respect my WaveFormat settings. It sets the bitdepth and sample rate based
on the input even if I specify. That doesn't work for me.

Thanks,
Dan

On Fri, Mar 4, 2016 at 4:35 PM, Florian Rosmann <notifications@github.com>
wrote:

> Please consider using WasapiCapture instead of WaveIn. Compared to WaveIn,
> WasapiCapture is state of the art and works with a much lower latency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filoe/cscore/issues/47#issuecomment-192503621>.
>



-- 


 2 Corinthians 13:14

**Comment by filoe** [comment]
Well but you also can't rely on whatever WaveIn APIs are doing. 
It is true that it is a bit more difficult to specify a WaveFormat for WasapiCapture. You can make some kind of suggestion. If the driver does not support that, CSCore chooses a format close to your suggestion. But CSCore provides all the tools for converting the format to whatever you need. 
For example:
`var waveSource = peakMeter.ToWaveSource(16).ChangeSampleRate(44100);`

**Comment by dwebb7** [comment]
What would that do if waveSource was already 16 bit 44100?

On Fri, Mar 4, 2016 at 4:43 PM, Florian Rosmann <notifications@github.com>
wrote:

> Well but you also can't rely on whatever WaveIn APIs are doing.
> It is true that it is a bit more difficult to specify a WaveFormat for
> WasapiCapture. You can make some kind of suggestion. If the driver does not
> support that, CSCore chooses a format close to your suggestion. But CSCore
> provides all the tools for converting the format to whatever you need.
> For example:
> var waveSource = peakMeter.ToWaveSource(16).ChangeSampleRate(44100);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filoe/cscore/issues/47#issuecomment-192505083>.
>



-- 


 2 Corinthians 13:14

**Comment by filoe** [comment]
Nothing. See https://github.com/filoe/cscore/blob/master/CSCore/FluentExtensions.cs#L59
