### ISSUE TITLE
[Question] peak sound

### ISSUE THREAD

**Issue by LiorBanai** [filoe/cscore#477]
Hi,
Is there  a way to get the peak sound value of the currently played sounds in the system?
let say there is youtube video in the background.  Can I get peak value when I sample it (for example via timer each 1 second)

**Comment by LiorBanai** [comment]
found it.

**Comment by mvkalsbeek** [comment]
@LiorBanai maybe disclose your solutions for future reference by others with a similar issue?

**Comment by LiorBanai** [comment]
@mvkalsbeek sure. something like this:
```cs
var devEnum = new MMDeviceEnumerator(Guid.NewGuid());
defaultVUDevice = devEnum.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);
// Read the current volume peak levels of the stereo speakers...  
var dAvg = ((double)defaultVUDevice.AudioMeterInformation.PeakValues[0] + 
            (double)defaultVUDevice.AudioMeterInformation.PeakValues[1]) / 2.0;
```
