### ISSUE TITLE
WasapiCapture's ReadData method might fail although recording is still running

### ISSUE THREAD

**Issue by DanielGilbert** [filoe/cscore#48]
Hi,

sometimes, an odd error occurs when recording using loopback capture: The recording only contains the header - without any data in it, and the header being in the state it was when it was written.

This error occurs randomly, on different devices, on different occasions - but never on my dev machine. Of course.

So I started digging around, and I might have found the reason for the error. It's in line 314 in WasapiCapture.cs:

```C#
IntPtr nativeBuffer = captureClient.GetBuffer(out framesAvailable, out flags);
```

This call is kinda wrong - which on the other is related to the underlying implementation of this call. Every return value unequal zero will trigger an exception. According to [IAudioCaptureClient::GetBuffer method (Windows)](https://msdn.microsoft.com/de-de/library/windows/desktop/dd370859(v=vs.85).aspx), it is perfectly fine for the function to return `AUDCLNT_S_BUFFER_EMPTY` (which translates to `0x08890001`, clearly not being 0).

The caller should check again a few times if data is available. If that's not the case, or another error occurs, it should leave the routine.

The same applies to `int nextPacketSize = captureClient.GetNextPacketSize();` - a commenter points that out in the corresponding MSDN article ([IAudioCaptureClient::GetNextPacketSize method (Windows)](https://msdn.microsoft.com/de-de/library/windows/desktop/dd370860(v=vs.85).aspx)):

> can return 0
> 
> If it sets pNumFramesInNextPacket to 0, this means "nothing new ready to capture quite yet" [even if something is really playing and capture is occurring normally] so you should (possibly sleep then) try to capture again.

I'd like to solve that - but I'm not sure if adding exception handling might slow down the method significantly ( [others](http://stackoverflow.com/questions/1308432/do-try-catch-blocks-hurt-performance-when-exceptions-are-not-thrown) [don't](http://stackoverflow.com/questions/1350264/try-catch-performance) [know](http://stackoverflow.com/questions/3480124/performance-cost-of-a-try-catch-block) [either](http://stackoverflow.com/questions/867017/performance-cost-of-try-in-c-sharp) ) - any idea on that?

I think it might make sense to add some kind of threshold when to exit the function.

**Comment by filoe** [comment]
Thanks for reporting. Please check whether the problem got fixed.

**Comment by DanielGilbert** [comment]
Thanks for the quick fix - I'll see if the error will occur again. However, I'm afraid this won't fix the potential issue with `GetNextPacketSize()`.

I added some more logging to my app, to check if it is affected by this issue.

**Comment by DanielGilbert** [comment]
Hi - that doesn't fix the problem. It now creates audio files that contain silence. That's a weird error.
