### ISSUE TITLE
Capture input from two Microphones save to Wav

### ISSUE THREAD

**Issue by djsharman** [filoe/cscore#49]
Hi,

I am trying to capture the input from two Microphone inputs and save the resulting mixed audio to disk as a wav file.

To this end I started playing around with the Recorder demo application, first just adding one sound to the mixer and trying to save it to disk. I quickly realized that the mixer doesn't have a "Data Available" event so I tried the following code using the soundInSource as the trigger. It didn't work so I guess I need to approach this in a different way. Does anyone have any suggestions about the best way to go about this? 
        
```
private void StartCapture()
  {
            

                if (SelectedDevice == null)
                    return;

                if(CaptureMode == CaptureMode.Capture)
                    _soundIn = new WasapiCapture();
                else
                    _soundIn = new WasapiLoopbackCapture();

                _soundIn.Device = SelectedDevice;
                _soundIn.Initialize();


                const int mixerSampleRate = 8000; //44.1kHz

                var mixer = new SimpleMixer(2, mixerSampleRate) //output: stereo, 44,1kHz
                {
                    FillWithZeros = false,
                    DivideResult = true //you may play around with this
                };

                var soundInSource = new SoundInSource(_soundIn);


                mixer.AddSource(
                    soundInSource
                    .ChangeSampleRate(mixerSampleRate)
                    .ToStereo()
                    .ToSampleSource());


                var singleBlockNotificationStream = new SingleBlockNotificationStream(mixer);
                _finalSource = singleBlockNotificationStream.ToWaveSource();
                _writer = new WaveWriter("D:\\a\\Mix.wav", _finalSource.WaveFormat);

                byte[] buffer = new byte[_finalSource.WaveFormat.BytesPerSecond / 2];

               
                soundInSource.DataAvailable += (s, e) =>
                {
                    int read;
                    while((read = _finalSource.Read(buffer, 0, buffer.Length)) > 0) {
                        _writer.Write(buffer, 0, read);
                    }

                };

                singleBlockNotificationStream.SingleBlockRead += SingleBlockNotificationStreamOnSingleBlockRead;
                 _soundIn.Start();
            
        }

```
Regards,

Darren

**Comment by filoe** [comment]
Ok, you've got two major problems here: 

The first is that you're setting `FillWithZeros` to true (in addition I would recommend to set `DivideResult` to false). This causes the mixer to serve infinite data. The result is endless loop in the  `DataAvailable` handler. Set is to false. The second problem is that the SimpleMixer class does not perfectly fit for this scenario. The handler reads data until zero bytes got read. The mixer will remove the soundInSource from the source if its Read-Method returns zero. The result is, that the mixer will remove the soundInSource. 

Apply the following modifications:
Set the FillWithZeros and the DivideResult to false. 
Go to the SimpleMixer class and comment the following line:
https://github.com/filoe/cscore/blob/master/Samples/SimpleMixerSample/SimpleMixer.cs#L91

**Comment by djsharman** [comment]
Hi Florian,

Thank you for your help. I gave this a go and it does work but there is some noise being injected into the signal somewhere (possibly zeros from the buffer). I will investigate this further, and see if I can get to the bottom of it.

Regards,

Darren

**Comment by postacik** [comment]
I'm also using the SimpleMixer class from the samples and I confirm that tick like sounds can be heard in the final audio (noise being injected as explained above). I applied the proposed modifications (Set the FillWithZeros and the DivideResult to false etc.)

Do you have any suggestions on how to correct this problem?

**Comment by filoe** [comment]
So you may try to set `DivideResult` back to true. As the name already indicates, it is just a "simple" mixer, demonstrating the prinziple. The clipping problem is not really solved. It is possible that a sample exceeds its valid range (-1 to 1). This can cause a "tick" noise. Settings `DivideResult` to true will prevent that case. But if you've got a weak signal, it will become even weaker.

**Comment by postacik** [comment]
Setting DivideResult to true solved the problem. Thanks.
