### ISSUE TITLE
CSCore still uses .NET 3.5

### ISSUE THREAD

**Issue by NeoLegends** [filoe/cscore#52]
I wonder whether supporting .NET 3.5 is still necessary? Even Vista supports .NET 4.6. :)

**Comment by filoe** [comment]
CSCore does not use/need any features of > .NET 3.5. So there is no reason for using any other .NET version. Further, there are still applications using .NET 3.5. If I would change the required .NET version, CSCore would not be compatible with some of the already existing applications. I would say supporting a quite low .NET version is a feature ;).

**Comment by NeoLegends** [comment]
Alright. I was just wondering because I needed to install .NET 3.5 before being able to edit the sources in VS.
