### ISSUE TITLE
Is it possible to change the tempo and pitch of a track?

### ISSUE THREAD

**Issue by Digot** [filoe/cscore#53]

**Comment by NeoLegends** [comment]
Well, pitch changing is a little complicated but can be done. See this article: https://sites.google.com/site/mikescoderama/pitch-shifting.

**Comment by postacik** [comment]
Please have a look at my CodeProject article:

http://www.codeproject.com/Tips/1082074/Audio-Pitch-Shifter

**Comment by Digot** [comment]
Thanks!
