### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by NeoLegends** [filoe/cscore#56]
Since this library is approaching a major release with breaking changes, I suggest this project switch to [semver](http://semver.org/). It provides a clean and concise versioning scheme, which clearly states when an update to a library is backward compatible or not. This would mean the next release be 2.0.0, since lots of classes and interfaces have been renamed or have different properties.

Semver is seeing increased use throughout the open source community - the entire `npm` ecosystem uses it - because it makes consuming libraries so simple and convenient for developers.

**Comment by filoe** [comment]
You're absolutely right. The versioning has been a problem since this project started. There would have to be a better concept and a clear cut.

**Comment by NeoLegends** [comment]
Yes, versioning is pretty hard to get right.
