### ISSUE TITLE
WaveForm display in WPF and streaming 

### ISSUE THREAD

**Issue by Digot** [filoe/cscore#58]
Hi!

How is it possible to display the WaveForm of an IWaveSource?

Also I'd like to know, how to stream music to a streaming service like Shoutcast?

Thanks in advance!

**Comment by filoe** [comment]
There is currently no support for streaming to any service like shoutcast. But you can implement it yourself and use cscore to provide the audio data. 

For creating waveforms take a look at the CSCoreWaveform- and the WinformsVisualization-Sample.

**Comment by postacik** [comment]
Is there a sample for a "peak meter" like the one in Audacity?

**Comment by filoe** [comment]
You can use the `PeakMeter` class for calculating the peak meter values. But no, there is no sample.

**Comment by postacik** [comment]
Thanks, I hadn't noticed that class. I'll have a look and write back if I can't succeed.

**Comment by postacik** [comment]
I used it as in the following sample code.

```c#
            mSoundSource = CodecFactory.Instance.GetCodec(fileName).ToSampleSource().ToMono();
            PeakMeter peakMeter = new PeakMeter(mSoundSource) { Interval = 50 };
            peakMeter.PeakCalculated += PeakMeter_PeakCalculated;
            mWaveSource = peakMeter.ToWaveSource(16);
            mMusicPlayer.Open(mWaveSource, device);
```

**Comment by filoe** [comment]
So it's working as expected?

**Comment by postacik** [comment]
Yes, thank you.

**Comment by filoe** [comment]
I would guess, this can be closed.
