### ISSUE TITLE
Loading file in unsupported format causes exception in Finalizer

### ISSUE THREAD

**Issue by albanur** [filoe/cscore#59]
When file in unsupported format is loaded with 'CodecFactory.Instance.GetCodec(filePath)', then MediaFoundationException is thrown with message: "Interops::MFCreateSourceReaderFromURL caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported.". Thet error is expected and can be handled properly.

When after some time (after couple of seconds) the ArgumentNullException is thrown in Finalizer with message: 'Value cannot be null.' As it is thrown in Finalizer, it cannot be handled and causes the process to terminate. The problem occurs only in Release build and I was not able to replicate it in Debug build.

**Comment by filoe** [comment]
Thanks for reporting the bug. Do you have some kind of stacktrace?

**Comment by dexit2k** [comment]
I also got this Problem. If you wonna fix it, search for CSCore.Win32.ComObject.BasePtr and replace the getter:

`        /// <summary>
        /// Native pointer to the COM object.
        /// </summary>
        public IntPtr BasePtr
        {
            get
            {
                try
                {
                    return new IntPtr(UnsafeBasePtr); 
                }
                catch
                {
                    return IntPtr.Zero;
                }
            }
            protected set { UnsafeBasePtr = value.ToPointer(); }
        }`

**Comment by albanur** [comment]
@filoe 
I would like to provide you as many information related to this bug, but for now I cannot retrieve any more. In release build I got only following details:
"System.ArgumentNullException was unhandled
Message: An unhandled exception of type 'System.ArgumentNullException' occurred in CSCore.dll
Additional information: Value cannot be null."

I also tried get Release build with pdb by playing with '/debug' ilasm parameter: with '/debug=OPT' problem occurs while with '/debug=IMPL' again I was not able to reproduce problem.

@dexit2k 
Thanks for hint. I tried your solution, but it does not solve my problem. Have you add any other changes to code?

**Comment by postacik** [comment]
Try using VS2013 to compile CSCore if you are having your problem with VS2015.

This offer may seem awkward but I have a similar problem when I use VS2015 and the problem disappears with VS2013.

**Comment by filoe** [comment]
I really tried to reproduce the bug based on the details I have: 
I've created a dummy file(just a text file) and tried to open it. I am getting the same exception as you(as expected). But I can't see the System.ArgumentNullException in output window. Do you have access to intellitrace? If yes, try to find the exception in the intellitrace log. 
Do you have a few more details(I know debugging these things is a painful) or could you provide a sample that reproduces the bug?

**Comment by speige** [comment]
I believe this has been fixed in GitHub, but not on NuGet. I was having the same issue & removed NuGet & replaced it with the .dll compiled from latest github sourcecode & the problem was resolved for me.
