### ISSUE TITLE
FLAC Decoder can't handle files encoded with bit depth 24 and compression level >= 3

### ISSUE THREAD

**Issue by opcon** [filoe/cscore#6]
As in title, the FLAC decoder spits out various errors when attempting to decode 24 bit files encoded with a compression level >= 3. A summary of various combinations and exceptions is shown below.

Compression Level / Bit Depth | Result
----------------------------------------- | ----------
0/24 | Works
1/24 | Works
2/24 | Works
3/24 | "Quantized linear predictor coefficient shift needed." was negative.
5/24 | RICE not supported (Invalid2)
6/24 | "Quantized linear predictor coefficient shift needed." was negative.
7/24 | RICE not supported (Invalid3)
8/24 | "Quantized linear predictor coefficient shift needed." was negative.

Looking at the varied exceptions and the difference between various [compression levels](https://xiph.org/flac/documentation_tools_flac.html#flac_options_level_0), I believe that that the cause of this bug lies in the different [block sizes](https://xiph.org/flac/documentation_tools_flac.html#flac_options_blocksize) used.

Compression levels 0-2 use a block size of 1152 while compression levels 3-8 use a block size of 4096.

**Comment by filoe** [comment]
Thanks for your detailed issue. I encoded audio files with compression level 3 and above. I can't reproduce your results. Could you please provide the file you tested with?

**Comment by opcon** [comment]
Confirming that commit b7a927eb5cd723f81e6807458ff50299e1ed6e3f seems to have fixed this issue with the files I was using, thank you.

**Comment by filoe** [comment]
Glad to hear that :).
