### ISSUE TITLE
How to use EqualizerFilter in real-time ?

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#61]
I need to apply a high-pass filter on input AudioEndPoint devices (microphones ).

Please tell me should I write a custom DSP filter? or can I use EqualizerFilter for it?

Thanks in advance.

and special thanks to autors of cscore.
(sorry for my english)

**Comment by filoe** [comment]
The Equalizer you are talking about is not a high-pass filter. But internally it uses the `BiQuad` filter which can be used to create a high-pass filter. We can add the high-pass filter as feature request if you want to.

**Comment by Mitra-M** [comment]
aha ,Thank you so much.
 it is very good if you add High/Mid/Low filters to cscore. and add a sample to apply them on audio of input / output devices.
thanks again.

**Comment by filoe** [comment]
Gonna implement it in the next few days. Should not be a big deal.

**Comment by filoe** [comment]
I've the requested filters and a little playback example. Apply it to input devices as every other audio-filter. For example, take a look at the "Recorder"-sample.
