### ISSUE TITLE
How to get device-AudioEndpointVolume ?

### ISSUE THREAD

**Issue by Mitra-M** [filoe/cscore#62]
please tell me how to get 

> device-AudioEndpointVolume.MasterVolumeLevelScalar

   using cscore.CoreAudioAPI?

**Comment by filoe** [comment]
Take a look at these unit-tests: https://github.com/filoe/cscore/blob/master/CSCore.Test/CoreAudioAPI/EndpointTests.cs#L31

If there are still any questions, feel free to ask me :).

**Comment by Mitra-M** [comment]
Thank you very much for your quick response and hope to always be active .
