### ISSUE TITLE
RawDataReader bug

### ISSUE THREAD

**Issue by postacik** [filoe/cscore#65]
Hi,
I'm using the RawDataReader class and I think it has a bug.

When WaveFormat.BlockAlign = 4 (ieeefloat) and I want to read 4 bytes into a buffer array, the Read function reads 0 bytes because 4 - (4 & 4) = 0.

What about using the % operator instead of &?

Buggy code:
```c#
        public int Read(byte[] buffer, int offset, int count)
        {
            CheckForDisposed();
            count -= (count & WaveFormat.BlockAlign);
            return _stream.Read(buffer, offset, count);
        }
```

My replacement:
```c#
        public int Read(byte[] buffer, int offset, int count)
        {
            CheckForDisposed();
            count -= (count % WaveFormat.BlockAlign);
            return _stream.Read(buffer, offset, count);
        }
```

**Comment by filoe** [comment]
Of course this is a sloppy mistake. It makes absolutely no sense to use the `and` operator. Thanks for reporting.
