### ISSUE TITLE
Potential memory leak in StreamingSourceVoice.Create

### ISSUE THREAD

**Issue by skwasiborski** [filoe/cscore#66]
It seems that application we are working on suffers from a memory leak that is related to usage of CSCore. After calling StreamingSourceVoice.Create an instance of VoiceCallback is created. From the VoiceCallback instance a COM callable wrapper is created but it seems that this wrapper is never released even after StreamingSourceVoice is disposed.

Live reference to VoiceCallback can be expensive because through VoiceCallback.StreamEnd handler VoiceCallback references StreamingSourceVoice which keeps instance of IWaveSource alive.

**Comment by filoe** [comment]
I've made an attempt to fix the issue. Please test it, and give me some feedback whether it fixes your issue.

**Comment by filoe** [comment]
I would guess, you've fixed it with #72 :+1:
