### ISSUE TITLE
Applying changes to ChannelMatrix in real time

### ISSUE THREAD

**Issue by FedorSulaev** [filoe/cscore#67]
I update ChannelMatrix in DmoChannelResampler and call DmoChannelResampler.CommitChannelMatrixChanges(), but it works only before I start playing my audio file. Is there a way to update channel matrix in real time while ISoundOut is playing?

**Comment by FedorSulaev** [comment]
Code to reproduce the issue:
(I used the first file from this page: [https://www2.iis.fraunhofer.de/AAC/multichannel.html](url))
```C#
static void Main(string[] args)
{
	ChannelMatrix FiveOneToStereo = new ChannelMatrix(
	ChannelMask.SpeakerFrontLeft | ChannelMask.SpeakerFrontRight |
	ChannelMask.SpeakerFrontCenter | ChannelMask.SpeakerLowFrequency |
	ChannelMask.SpeakerBackLeft | ChannelMask.SpeakerBackRight,
	ChannelMask.SpeakerFrontLeft | ChannelMask.SpeakerFrontRight);
	FiveOneToStereo.SetMatrix(
	new[,]
	{
		{ 1f, 0f },
		{ 0, 1f },
		{ 0, 0f },
		{ 0f, 0f },
		{ 0f, 0f },
		{ 0f, 0f }
	});
	ISoundOut soundOut = new WasapiOut();
	DmoChannelResampler channelResampler;
	IWaveSource waveSource = CodecFactory.Instance.GetCodec("ChID-BLITS-EBU-Narration.mp4")
				.AppendSource(s => new CachedSoundSource(s))
				.ChangeSampleRate(22000)
				.AppendSource(s => new DmoChannelResampler(s, FiveOneToStereo), out channelResampler);
	soundOut.Initialize(waveSource);
	soundOut.Play();
	Console.ReadLine();
	channelResampler.ChannelMatrix[0, 0].Value = 0f;
	channelResampler.ChannelMatrix[1, 1].Value = 0f;
	channelResampler.ChannelMatrix[4, 0].Value = 1f;
	channelResampler.ChannelMatrix[5, 1].Value = 1f;
	channelResampler.CommitChannelMatrixChanges();
	Console.WriteLine("Updated ChannelMatrix");
	Console.ReadLine();
	soundOut.Stop();
}
```

**Comment by filoe** [comment]
I'm not happy with the solution but it should work. I had to re-set the OutputType on the MediaObject. I've found no other possibility to tell the Resampler that things have changed.

**Comment by FedorSulaev** [comment]
Thanks for the fix, it works for me. I was thinking about other options, and maybe a different approach would be to keep the ChannelMatrix static and adjust level of input channels with custom SampleSource or WaveSource, would that be a viable option?

**Comment by filoe** [comment]
Glad to hear, it works. I'm closing this issue. If there are any further questions, just reopen the issue or create a new one.
