### ISSUE TITLE
CreateMasteringVoice on selected device (XAudio2.8) fails

### ISSUE THREAD

**Issue by wgebczyk** [filoe/cscore#69]
On Win10, from WPF app on NetFx 4.6, for following code sequence it fails with Exception:
```
_xAudio2 = XAudio2.CreateXAudio2();
MMDeviceCollection wasapiDevices;
using (MMDeviceEnumerator enumerator = new MMDeviceEnumerator())
{
    wasapiDevices = enumerator.EnumAudioEndpoints(DataFlow.Render, DeviceState.Active);
}
foreach (var wasapiDevice in wasapiDevices)
{
    _allDevices.Add(wasapiDevice);
}

[...] in _selectedDevice there is instance from _allDevices - doesn't matter which one.

_xAudio2MasteringVoice = _xAudio2.CreateMasteringVoice(
    XAudio2.DefaultChannels,
    XAudio2.DefaultSampleRate,
    _selectedDevice.DevicePath
);
```
the Exception's message is `IXAudio2::CreateMasteringVoice caused an error: 0x80004005, "Unspecified error".`

On "default" device rest of code works and I can play sound samples.

Could you hint me if I'm doing something wrong or it simply doesn't work on `id="CSCore" version="1.1-beta2"`?

Thanks!

**Comment by filoe** [comment]
Please check the version of the _xAudio2 object. If its version is 2.7 you have to pass an integer, if its 2.8 you have to pass the devicepath. See https://github.com/filoe/cscore/blob/master/CSCore.Test/XAudio2/XAudio2Tests.cs#L212

**Comment by wgebczyk** [comment]
Thanks for quick answer. I was not completely clear. Its XAudio 2.8. I haven't been installing prev DX version on Win10.

If I pass invalid type it throws exception if it is no a string.

Testes on 2 different computers and even downloading source code and running Unit Test responsible for using specific device fails on test that is using 2.8.

**Comment by wgebczyk** [comment]
OK - tested on Win 10 without any older DX version installed.
The stack trace shows what I was calling.

Any idea what can be wrong? Any additional information might be valuable?

```
$exception
{"IXAudio2::CreateMasteringVoice caused an error: 0x80004005, \"Unspecified error\"."}
    Data: {System.Collections.ListDictionaryInternal}
    ErrorCode: 0x80004005
    HResult: 0x80004005
    HelpLink: null
    InnerException: null
    InterfaceName: "IXAudio2"
    Member: "CreateMasteringVoice"
    Message: "IXAudio2::CreateMasteringVoice caused an error: 0x80004005, \"Unspecified error\"."
    Source: "CSCore"
    StackTrace: "   at CSCore.XAudio2.XAudio2Exception.Try(Int32 result, String interfaceName, String member) in C:\\myWork\\github\\filoe\\cscore\\CSCore\\XAudio2\\XAudio2Exception.cs:line 52
   at CSCore.XAudio2.XAudio2.CreateMasteringVoicePtr(Int32 inputChannels, Int32 inputSampleRate, Int32 flags, Object device, Nullable`1 effectChain, AudioStreamCategory streamCategory) in C:\\myWork\\github\\filoe\\cscore\\CSCore\\XAudio2\\XAudio2.cs:line 673
   at CSCore.XAudio2.XAudio2.CreateMasteringVoice(Int32 inputChannels, Int32 inputSampleRate, Object device) in C:\\myWork\\github\\filoe\\cscore\\CSCore\\XAudio2\\XAudio2.cs:line 747
   at CSCore.Test.XAudio2.XAudio2Tests.CanSelectXAudioDevice() in C:\\myWork\\github\\filoe\\cscore\\CSCore.Test\\XAudio2\\XAudio2Tests.cs:line 240"
    TargetSite: {Void Try(Int32, System.String, System.String)}
```

**Comment by filoe** [comment]
I'll have a look at it. CSCore does not support XAudio2.9. But according to microsoft 

> XAudio2 version 2.9 ships as part of Windows 10, XAUDIO2_9.DLL, alongside XAudio2.8 to support older applications, and does not require redistribution.

XAudio2.8 should be still supported.

**Comment by filoe** [comment]
Should be fixed. Thanks again for your contribution.
