### ISSUE TITLE
WinForms example with Wav form?

### ISSUE THREAD

**Issue by bulltorious** [filoe/cscore#7]
Hey,

This is not a bug or an issue, but I wasn't quite sure where to post this question, so please delete if it doesn't meet critieria.

Any chance you could post a wav form example with seek ?  Basically, load the mp3 and get an entire graphical representation of it.  Then click around on different parts of the mp3 for it to start at different locations?

I see that you already have a basic example for moving around in a file, but a graphical representation would be great !

Thanks for your great work either way.  This looks much more useable than naudio.

**Comment by filoe** [comment]
I am going to have a look at it.

**Comment by filoe** [comment]
It is no winforms example, but I've added a wpf example with be6dc4eac141d7da9b05874965281e301aa3159e
