### ISSUE TITLE
Is this project Crossplatform?

### ISSUE THREAD

**Issue by SirusDoma** [filoe/cscore#75]
Currently, I'm developing a game that heavily require Audio on gameplay.
The game only uses 2 audio format: OGG and WAV
I want to make this game compatible with OSX and some Linux distributions with Mono

So the question, is the CSCore compatible with Mono? will my game run on OSX and other platforms that depends on Mono instead .NET Framework? 
thanks in advance

**Comment by filoe** [comment]
WAV, OGG, AIFF and FLAC decoders are not platform dependend. Unfortunately, the SoundOut interfaces are. There is an openal pull request(see #16). But the author does not respond on any input. So its hard to merge it. If I would have some time, I would love to implement openal. So theoretically, you could use it in combination with mono. But it really depends on which components you would like to use. Things like DmoEffects,... won't work on linux or osx. 

To be honest I don't know whether there are mono compatible libraries. But if there are, I would recommend using these. I've got no expierence on using cscore in combination with mono.

**Comment by SirusDoma** [comment]
Well, actually I only need a simple playback for WAV and OGG (play, pause, resume stop)
But in my opinion, it shouldn't be a problem when some features only available on certain platforms, as long as the "core" functionality are available across platforms.

I haven't tried this library yet, is there any sample that I could try?
I will try to run the sample with Mono if any

**Comment by filoe** [comment]
Well as long as there is no openal, you won't be able to play any sound :(.

**Comment by SirusDoma** [comment]
That's too bad!
I tried OpenAL a bit long time ago, and I have no idea how to implement it by myself :laughing: 
Well, I guess i have no choice but to wait. Since I need free library to do this.

Thanks for your replies anyway!

**Comment by opcon** [comment]
@SirusDoma I don't know if you're still looking, but I have started a preliminary Linux implementation branch [here](https://github.com/opcon/cscore/tree/linux), which currently supports building CSCore with Mono and playing .wav files on Linux using OpenAL as the output - see the OpenAL Sample application for an idea of how it works.

**Comment by filoe** [comment]
So you've got OpenAL working?

**Comment by opcon** [comment]
Yes, I fixed up ThuCommix's code, the main fix is commit 7e00fcc

**Comment by filoe** [comment]
Very interesting, I've never had to the time to make an attempt to fix it. 
So you've already managed to get it working on linux?

**Comment by opcon** [comment]
Yeah, once I fixed the OpenAL playback on Windows, I was able to get a .wav file playing on Ubuntu 15.10 relatively easily, I just had to fix a few issues that were preventing the project from compiling with Mono.

**Comment by SirusDoma** [comment]
I'm still looking for this actually
I need to play Wav and OGG under multiple platforms
Unfortunately, I don't have much knowledge to contribute..

Well, looking forward to the progress! and thanks for your effort!

**Comment by VortexGator** [comment]
How is the Linux support right now?.

**Comment by filoe** [comment]
See #94.
