### ISSUE TITLE
CachedSoundSource Out of Memory

### ISSUE THREAD

**Issue by dwebb7** [filoe/cscore#78]
In your CSCoreWaveform sample is there a way to get it to open a larger file. If I open a 30 min file I get an OutOfMemoryException. Some of the files I am working with are a little over an hour. I'm wanting to open the file in a CachedSoundSource so i can show a waveform and allow trimming and cutting parts out.

Thanks,
Dan

**Comment by filoe** [comment]
You could use a `FileStream` on a temporary file instead of the `MemoryStream`.
