### ISSUE TITLE
NullReferenceException GetStatisticsNative

### ISSUE THREAD

**Issue by Flozi95** [filoe/cscore#79]
I randomly get the followiing error. I'm actually not able to reproduce or catch it. Anybody an idea how to handle this or get rid of it ;)
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei CSCore.MediaFoundation.MFSinkWriter.GetStatisticsNative(Int32 streamIndex, MFSinkWriterStatistics&amp; statistics)
   bei CSCore.MediaFoundation.MFSinkWriter.GetStatistics(Int32 streamIndex)
   bei CSCore.MediaFoundation.MediaFoundationEncoder.Dispose(Boolean disposing)
   bei CSCore.MediaFoundation.MediaFoundationEncoder.Finalize()
```

**Comment by filoe** [comment]
Could you please provide some sample code that reproduces the issue?

**Comment by Flozi95** [comment]
I'm not quite sure where's the error that causes the problem. .. :disappointed:

**Comment by filoe** [comment]
Seems like the MFSinkWriter instance got already disposed. So its internal pointer to the com object gets set to zero, which causes the NullReferenceException. In generall, call the Dispose method instead of letting the GC call the Finalize method. 
Maybe the fix I've just commited works. It's hard to reproduce it ...

**Comment by Flozi95** [comment]
I call the dispose manually. Don't think that there's a problem :-1: 
Try to build the sources and test it asap.

**Comment by Flozi95** [comment]
Could you maybe provide me a "nightly build" ;-)?

**Comment by filoe** [comment]
Does https://github.com/filoe/cscore/commit/c7f5e14f4e346d871a6146dbe821e9ef511e68ec work for you?
If I take a look at the StackTrace, the destructor gets called by the GC. If it would be disposed correctly, the destructor would not be called. But to be honest, it should not matter. Going to fix this. Please give me some feedback on commit https://github.com/filoe/cscore/commit/c7f5e14f4e346d871a6146dbe821e9ef511e68ec

**Comment by Flozi95** [comment]
Was not able to build until now. Not at my dev pc ;-) Thats why a "nightly build" would be great :wink:

**Comment by filoe** [comment]
You can try this one: https://www.dropbox.com/sh/uqhlngnoroknqvp/AAD41Zmfq3XsKCB_MQt7O975a?dl=0

**Comment by Flozi95** [comment]
Try it asap.

**Comment by Flozi95** [comment]
Seems to work better :+1: 
Hope the problem is solved now.

**Comment by Flozi95** [comment]
Until now no crashes anymore.
