### ISSUE TITLE
Sound output doesn't work if assembly name is different from assembly title

### ISSUE THREAD

**Issue by opcon** [filoe/cscore#8]
Finally tracked this bug down, putting this up now in case I forget, I'll add more detail to the bug report soon.

#### Issue:
Attempting to play an audio file would result in no sound being outputted. This only occurred when the output device used was a virtual audio cable [VAC](http://software.muzychenko.net/eng/vac.htm) device. Sound was shown being outputted in the windows volume mixer [http://software.muzychenko.net/eng/vac.htm](http://software.muzychenko.net/eng/vac.htm), but did not appear to make it to the ouput device - Line 3 in the attached screenshot.

This bug is caused by the assembly (executable) name being different from the assembly title (as shown in task manager) set in assembly information.

This bug does not occur when outputting directly to my speakers - only when going through the virtual audio cable.

**Comment by filoe** [comment]
So the bug occurs when the assembly name is not equal to the assembly title (of your own executable)?

**Comment by opcon** [comment]
I can't actually reproduce this issue anymore, I'm not sure what was going on.
