### ISSUE TITLE
Crossfading

### ISSUE THREAD

**Issue by liknes** [filoe/cscore#80]
Could you give me some tips on how I can achive crossfading between songs using CSCore. I want to make a player that crossfades between songs in a playlist. Rather than crossfading on set times I am looking to crossfade when the music level gets to a certain point (in the end of a sound file). This will ensure that both songs that end cold and songs that fade will be crossfaded in a way that the experience for the user listening to the playlist will be smooth and without "gaps"

**Comment by filoe** [comment]
Well you'll need several steps:
First of all, you have to make sure that both of your source, you want to fade, are of the same format(same samplerate and same number of channels). You can use the [ChangeSampleRate](http://filoe.github.io/cscore/sharpDox/1.1.0-beta/#type/FluentExtensions?ChangeSampleRate)- and the [ToStereo](http://filoe.github.io/cscore/sharpDox/1.1.0-beta/#type/FluentExtensions?ToStereo2)-(extension-)method. Of course you can also use the DmoChannelResampler, the ToMono-method and so on the convert the number of channels. It's just a suggestion.

The second step would be to write some kind of a mixer class(see the SimpleMixerSample sample-project). 

The third step is to use the FadeInOut-class fade your audio source(see the FadingSample sample-project).

Now you can build your setup: You need create two ISampleSource instances for both audio files. 
For example:
`FadeInOut source1 = CodecFactory.Instance.GetCodec("file1.mp3")
	.ChangeSampleRate(44100)
	.ToSampleSource()
	.ToStereo()
	.AppendSource(x => new FadeInOut(x));
	
FadeInOut source2 = CodecFactory.Instance.GetCodec("file2.mp3")
	.ChangeSampleRate(44100)
	.ToSampleSource()
	.ToStereo()
	.AppendSource(x => new FadeInOut(x));`

Now use your mixer class, add source1 as initial source and play:
```
//setup your mixer and source1 to it
AnyMixerClass mixer = new AnyMixerClass(2, 44100); //stereo, 44.1kHz
mixer.AddSource(source1);

//start fading in
source1.FadeStrategy.StartFading(0.0f, 1.0f, TimeSpan.FromSeconds(3));

//Start playback...
soundOut.Initialize(mixer);
soundOut.Play();
```

Now you need some of your logic when to start fading... to trigger fading... you can use something similar to this:
```
//source1 comes to its end, fade it out and fade in source2
source2.StartFading(0.0f, 1.0f, TimeSpan.FromSeconds(3));
mixer.AddSource(source2); //add source2 to the mixer

//remove source1 from the mixer as soon as it stopped fading
source1.FadingFinished += (s, e) => 
{
	mixer.RemoveSource(source1);
	source1.Dispose();
};
//fade out source1
source1.StartFading(1.0f, 0.0f, TimeSpan.FromSeconds(3));
```
This is just some kind of example code to show you the basic principle. It got not tested and was written in notepad. But as I said, it should demonstrate the princple.

To find the cue points, there are currently no "ready-to-use" components available. 
Of course you can use your audio source, seek to area of the end of the song, decode that area be calling the read method, iterating through the read samples, checking for a certain level and determine the cue point. I've got any further questions, feel free to task.

**Comment by liknes** [comment]
Thanks for the info! I will be trying out the code shortly!
