### ISSUE TITLE
WMADecoder Position

### ISSUE THREAD

**Issue by dwebb7** [filoe/cscore#81]
See the code below. When I do this same thing with a WaveFileReader or Mp3MediafoundationDecoder it reports the position I would expect but the WmaDecoder reports a position around a second before the position I set. What causes this?
Thanks for your help.

    public partial class MainWindow : Window
    {
        private ISampleSource playSampleSource;
        private bool click;
        public MainWindow()
        {
            InitializeComponent();
            var waveFileReader = new WmaDecoder(@"C:\Users\dwebb\Desktop\testwave.wma");

            //Setup Timer
            var dispatcherTimer = new DispatcherTimer {Interval = new TimeSpan(0, 0, 0, 0, 100)};
            dispatcherTimer.Tick += dispatcherTimer_Tick;
            dispatcherTimer.Start();

            playSampleSource = waveFileReader.ToSampleSource();
            var waveSource = playSampleSource.ToWaveSource();

            var playerOut = new WasapiOut();
            playerOut.Initialize(waveSource);
            playerOut.Play();
        }

        void dispatcherTimer_Tick(object sender, EventArgs e)
        {
            if (click)
            {
                MessageBox.Show(playSampleSource.Position.ToString());
                click = false;
            }
        }

        private void TestButton_Click(object sender, RoutedEventArgs e)
        {
            playSampleSource.Position = 300000;
            click = true;
        }
    }

**Comment by filoe** [comment]
Could you please provide the wma file. In wma files are getting decoded by microsoft's wma decoder. 
I've just tested it with a wma file and works as expected. But let me take a look at your file. 
Thanks.

**Comment by dwebb7** [comment]
Yes, here you go. This was recorded and encoded using MediaToundationEncoder in Cscore. I also ripped a song from a CD using windows media player and I get the same result. 
Thanks for your help.
Dan

https://dl.dropboxusercontent.com/u/16609856/TestMyRecorder.wma

**Comment by filoe** [comment]
I've made an attempt to fix it. Please test it and give me some feedback. The problem is that media foundation seeks to the next nearest keyframe. Now I am just skipping the delta between desired position and keyframe. Hopefully it helps.

**Comment by dwebb7** [comment]
Thank You! That did the trick.

**Comment by rgodart** [comment]
After this commit, the SoundOut.Stopped event is raised each time I call SoundOut.WaveSource.SetPosition on an mp3. This is the exception passed via PlaybackStoppedEventArgs:

"   at CSCore.MediaFoundation.MediaFoundationDecoder.SkipBytes(Int32 numberOfBytes)" & vbCrLf & "   at CSCore.MediaFoundation.MediaFoundationDecoder.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SingleBlockNotificationStream.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SampleConverter.SampleToPcm16.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.WaveAggregatorBase.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.VolumeSource.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SampleConverter.SampleToIeeeFloat32.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.SoundOut.WasapiOut.FeedBuffer(AudioRenderClient renderClient, Byte[] buffer, Int32 numFramesCount, Int32 frameSize)" & vbCrLf & "   at CSCore.SoundOut.WasapiOut.PlaybackProc(Object playbackStartedEventWaithandle)"

**Comment by rgodart** [comment]
After this commit, the SoundOut.Stopped event is raised each time I call SoundOut.WaveSource.SetPosition on an mp3. This is the exception passed via PlaybackStoppedEventArgs:

" at CSCore.MediaFoundation.MediaFoundationDecoder.SkipBytes(Int32 numberOfBytes)" & vbCrLf & " at CSCore.MediaFoundation.MediaFoundationDecoder.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SingleBlockNotificationStream.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.SampleToPcm16.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.WaveAggregatorBase.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.VolumeSource.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.SampleToIeeeFloat32.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SoundOut.WasapiOut.FeedBuffer(AudioRenderClient renderClient, Byte[] buffer, Int32 numFramesCount, Int32 frameSize)" & vbCrLf & " at CSCore.SoundOut.WasapiOut.PlaybackProc(Object playbackStartedEventWaithandle)"
