### ISSUE TITLE
Exception: Interops::MFCreateSourceReaderFromURL caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported."

### ISSUE THREAD

**Issue by rgodart** [filoe/cscore#82]
I've found an m4a file which causes CSCore to crash. The file can be found here: [](https://www.dropbox.com/sh/7tw35jff3sgx1sl/AACnzkNmYXh9cBnoXKrc4o3ea?dl=0)

This is the exception: 

```
Interops::MFCreateSourceReaderFromURL caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported.".. StackTrace:    at CSCore.MediaFoundation.MediaFoundationCore.CreateSourceReaderFromUrlNative(String url)
   at CSCore.MediaFoundation.MediaFoundationDecoder..ctor(String url)
   at CSCore.Codecs.CodecFactory.GetCodec(String filename)
```

**Comment by filoe** [comment]
Which platform are you running on? Could you upload the m4a file? Seems like it is just not supported by the MediaFoundationDecoder. Unfortunately there is not much I can do.

**Comment by rgodart** [comment]
Oops, the link didn't display. Here are the files: [File](https://www.dropbox.com/sh/7tw35jff3sgx1sl/AACnzkNmYXh9cBnoXKrc4o3ea?dl=0)

There are 2 files ("Working.m4a" and "Not working.m4a"), both coming from the same album. One works, the other doesn't. 

I'm running on Windows 10 64 bits.

**Comment by filoe** [comment]
Well, I wasn't able to play the file with any other audio player but ffmpeg. It seems to be a pretty messed up file. Even microsoft media player, their audio player app, spotify,... was not able to play the file. ffmpeg displays lots of errors on the console but was able to reconstruct the file(or a part of it). To be honest, I won't be able to fix this. CSCore uses the MediaFoundation decoder, not any custom(it would be extremely complicated and also expensive). But we could add support for ffmpeg decoders in the future. I'm sorry.

**Comment by rgodart** [comment]
No problem. To be honest, I forgot to test it with any other player, I usually do before sending you a file for analysis. So my bad :) Thanks for looking into it.

**Comment by filoe** [comment]
No problem :)
