### ISSUE TITLE
NullreferenceException during MMNotificationClient.Dispose()

### ISSUE THREAD

**Issue by rgodart** [filoe/cscore#84]
I'm using MMNotificationClient to detect a change in the default audio device.
When my class, which uses the MMNotificationClient  object, gets disposed when closing my application, MMNotificationClient.Dispose() is called. During MMNotificationClient.Dispose() , this nullReferenceException occurs in class "MMDeviceEnumerator" during the return in this function:

```
public unsafe int UnregisterEndpointNotificationCallbackNative(IMMNotificationClient notificationClient)
        {
            return InteropCalls.CallI(UnsafeBasePtr, notificationClient, ((void**) (*(void**) UnsafeBasePtr))[7]);
        }
```

I've created a sample application that illustrates it: [WpfApplication1](https://www.dropbox.com/sh/6f824qqyv3qo7qv/AACPtygByd_CaBDAJSL4ER12a?dl=0)

Steps to reproduce:

1. Compile and launch the sample app
2. Let the sample app start playing Test.mp3
3. Close the sample app by pressing the close button on the window

=> the nullreferenceexception occurs

**Comment by filoe** [comment]
The "error" occurs when you don't dispose the _client object correctly.

**Comment by rgodart** [comment]
Indeed, calling Dispose() on the NotificationClient resolves the issue. By the way, it seems the above fix doesn't prevent the NullReferenceException. _deviceEnumerator is not disposed when it happens, UnregisterEndpointNotificationCallbackNative still gets called and we get this:
![null pointer](https://cloud.githubusercontent.com/assets/11945339/14766267/2f86079e-0a03-11e6-8943-c77a1e30cf6f.png)

**Comment by filoe** [comment]
Do have https://github.com/filoe/cscore/commit/cc383cdb31b63289f3db3662e7d910946ae7ce57?

**Comment by rgodart** [comment]
No I missed that commit :( It's resolved now. As far as I'm concerned, this issue can be closed.
