### ISSUE TITLE
SoundOut.Stopped event is raised when calling SoundOut.WaveSource.SetPosition

### ISSUE THREAD

**Issue by rgodart** [filoe/cscore#85]
The SoundOut.Stopped event is raised each time I call SoundOut.WaveSource.SetPosition on an mp3. This is the exception passed via PlaybackStoppedEventArgs:

`" at CSCore.MediaFoundation.MediaFoundationDecoder.SkipBytes(Int32 numberOfBytes)" & vbCrLf & " at CSCore.MediaFoundation.MediaFoundationDecoder.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SingleBlockNotificationStream.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.SampleToPcm16.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.WaveAggregatorBase.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.Pcm16BitToSample.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SampleAggregatorBase.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.VolumeSource.Read(Single[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.Streams.SampleConverter.SampleToIeeeFloat32.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & " at CSCore.SoundOut.WasapiOut.FeedBuffer(AudioRenderClient renderClient, Byte[] buffer, Int32 numFramesCount, Int32 frameSize)" & vbCrLf & " at CSCore.SoundOut.WasapiOut.PlaybackProc(Object playbackStartedEventWaithandle)"
`

I suspect this is a result of fixing issue #81.

**Comment by filoe** [comment]
Could you please provide some details on the exception object?

**Comment by rgodart** [comment]
I tested this issue extensively today with the latest cscore-master and can't reproduce it anymore. After testing today, with the latest and also several previous versions of the cscore code, I suspect it was caused by some wrongdoing of myself in the first place. I'm closing the bug.

**Comment by rgodart** [comment]
Here is a file which causes the issue: [file](https://www.dropbox.com/sh/wr36rjx0u1u2aeo/AADnfLBQZ2oJXEIgWyRQHSOZa?dl=0)

The bug occurs when using MediaFoundationDecoder as mp3 decoder. This is some info about the exception object. Let me know if you need more info:

Message = "Array dimensions exceeded supported range."

StackTrace = "   at CSCore.MediaFoundation.MediaFoundationDecoder.SkipBytes(Int32 numberOfBytes)" & vbCrLf & "   at CSCore.MediaFoundation.MediaFoundationDecoder.Read(Byte[] buffer, Int32 offset, Int32 count)" & vbCrLf & "   at CSCore.Streams.SampleConverter.Pcm16BitToS...

TargetSite = {Void SkipBytes(Int32)}

**Comment by filoe** [comment]
Please review it and tell me whether it fixes your problem. I could reproduce and OverflowException.

**Comment by rgodart** [comment]
Thanks. I tested it, and the fix resolves the issue.
