### ISSUE TITLE
WASAPI Loopback Capture affected by system volume?

### ISSUE THREAD

**Issue by njbmartin** [filoe/cscore#86]
If there was a way to know whether the loopback is affected by the system volume?

On some systems I can mute the system audio or change the volume, and loopback capture won't be affected. However on others it is affected.

Is there a way to detect this or workaround this little problem?

**Comment by filoe** [comment]
To be honest, I've never noticed that. I could not find any information on your issue. What kind of OS, Soundcard,... are you using?

**Comment by njbmartin** [comment]
I'm using Windows 10. The devices I have that are affected by volume are:

- Nvidia High Definition Audio (Ultrawide Monitor with speakers connected via HDMI)
- Razer Kraken 7.1 Chroma (USB Headset)

If I use the built in `Speakers` (Realtek high definition Audio), it works as expected.

**Comment by filoe** [comment]
Strange, there should not be a difference... I'm sorry, I really can't help you. It's a problem of the windows api. I can't fix it.

**Comment by TheBauwssss** [comment]
Has a workaround for this problem been found yet? I am having the same issues. The volume of the WASAPI loopback capture is affected by my system volume.

**Comment by filoe** [comment]
Well, there is no workaround. It would guess it depends on the device and it's driver. 
Maybe https://github.com/residuum/JackSharp can help out.

**Comment by TheBauwssss** [comment]
I have noticed something weird, on my system the problem only seems to occur when playing audio on a Bluetooth device (with A2DP). All other non-Bluetooth audio devices (USB headset, TV through HDMI, monitor with DP and normal speakers through 3.5mm audio jack) are unaffected by changes in system volume.

@njbmartin Did the systems on which the issue occurred on your side also play their audio through a Bluetooth device?
