### ISSUE TITLE
Reverb Effect on existing wav file

### ISSUE THREAD

**Issue by grenadier89** [filoe/cscore#91]
I am trying to apply a reverb effect to an existing 5 second long wav file and am hoping you can provide some insight on how to accomplish this. After applying DmoWavesReverbEffect and saving the new source, it will only produce a output wav file of 1 second. 

This is the code of what I'm trying to accomplish

```
using (WaveFileReader r = new WaveFileReader(@"C:\...\input.wav"))
{
    using (WaveWriter w = new WaveWriter(@"C:\...\output.wav", r.WaveFormat))
    {

        var effect = new DmoWavesReverbEffect(r);
        var buffer = new byte[r.WaveFormat.BytesPerSecond];
        int read = 0;
        while ((read = effect.Read(buffer, 0, buffer.Length)) > 0) //read all available data from the source chain
        {
            w.Write(buffer, 0, read); //write the read data to the wave file
        }
    }
}
```

Stepping through the code and viewing the properties of `effect`shows that the length is the same length as `r`, though it only goes through the while loop a single time. The length of `effect` is 1146880, and the first pass through the while loop returns 96000, moves the position to 192000 (which is the bytesPerSecond of the input wav file), but on the second pass in the while loop, it will return 0. It's as if it doesn't know there is more data to read. Am I doing this correctly, or is there a different approach that needs to be taken?

Even trying 
`effect.WriteToFile("C:/.../output.wav");`

will result in a 1 second output

I am currently using CSCore 1.1.0-beta2. Any help is much appreciated!

**Comment by grenadier89** [comment]
Thanks for looking in to this! Is the source code ready to compile now with this new change? I tried downloading the project from GitHub and creating the dll, but when trying to call DmoWavesReverbEffect(), it breaks with 

> an exception of type 'System.NotImplementedException' occurred in CSCore.dll

Even adding the source code directly in the project fails with a few errors, such as in CSCore/Streams/AutoGain.cs, `IWaveStream` is referenced but the actual class doesn't seem to be available.

**Comment by filoe** [comment]
I would guess, the post build was not run by visual studio. Try to rebuild the whole solution. The postbuild of the main cscore project, replaces the notimplementedexceptions with some ilasm instructions.
