### ISSUE TITLE
Setting default audio endpoint devices

### ISSUE THREAD

**Issue by joelamos** [filoe/cscore#92]
I've looked through the CoreAudioAPI, and I couldn't find any way to set the roles of audio endpoint devices (only get them). Is there a way?

**Comment by filoe** [comment]
You're right. It is currently not supported.

**Comment by astutejoe** [comment]
@filoe I love the library but I need this feature, so I'll implement separately on my software, would it be beneficial if I make a pull request with this feature? Thanks for the work ;)

**Comment by filoe** [comment]
If it fits the library of course yes!
