### ISSUE TITLE
XAudio2Playback fails in VS Community 2015 on Windows 10

### ISSUE THREAD

**Issue by mikepelley** [filoe/cscore#95]
I'd like to build cscore from the repository to get a newer version than the one available in NuGet. I can build cscore including the samples using VS Community 2015 on Windows 10. I set the XAudio2Playback sample as the startup project and attempted to run, but it fails with an exception of "No supported XAudio2 version is installed." (line 188 of XAudio2.cs). I did a little digging and stepped through the code but I'm not really sure how to move forward. The DLLs for 2.7 and 2.8 are available, and an XAudio2 C++ demo I downloaded runs successfully. Please let me know if there's something I should check or if you need more information.

**Comment by filoe** [comment]
Could you may take a look at the exception object on line 188 and provide me some details.

**Comment by mikepelley** [comment]
The exception at XAudio2.cs:188 is thrown after CreateXAudio2() attempts to instantiate both XAudio2_8 and XAudio2_7 objects and fails. The initial attempt to create XAudio2_8 fails with a NotImplementedException thrown from InteropCalls.cs:21 in this function:

>     namespace CSCore.XAudio2
>     {
>         [CLSCompliant(false)]
>         [RemoveObj]
>         public class InteropCalls
>         {
>             [CSCalli]
>             internal static unsafe int CallI(void* _basePtr, void* ptr, void* p)
>             {
>                 throw new NotImplementedException();
>             }

Thanks for taking a look, and let me know if you need anything else.

**Comment by filoe** [comment]
Ok, try to rebuild the entire solution. If that happens, the post build was not successful. The postbuild replaces all CallI calls with ILAssembly instructions and removes the classes marked with the RemoveObj attribute.

**Comment by mikepelley** [comment]
Thanks - that got me there. The rebuild succeeded without fixing the problem, but I took a closer look at the output and saw that the call to the inline-il-compiler needed quotes (the calls for other tools already have quotes). I created a pull request for convenience, although it's a very simple edit.

Thanks very much for your help!

**Comment by filoe** [comment]
Glad to hear that. Thanks for pullrequest #96. I've already merged it. So it should be fixed.
