### ISSUE TITLE
WaveWriter.WriteToFile never closes resources

### ISSUE THREAD

**Issue by joelamos** [filoe/cscore#98]
I'm trying to follow what's happening in [WaveWriter.WriteToFile](https://github.com/filoe/cscore/blob/c4572d5b915d8b384a01a627b826076a35d1491c/CSCore/Codecs/WAV/WaveWriter.cs), and it looks like the resources are never getting closed.

**Comment by filoe** [comment]
You should not use the `WaveWriter.WriteToFile` method as it is marked as `Obsolete`.
Use the [WriteToFile](https://github.com/filoe/cscore/blob/master/CSCore/Extensions.cs#L199) extension method(or the [WriteToWaveStream](https://github.com/filoe/cscore/blob/master/CSCore/Extensions.cs#L220)). 
Anyway, if you are talking about resources, I would guess, you are talking about the filestream? 
The filestream gets closed within the `WaveWriter.Dispose` method. Could you may provide some details on "resources are never getting closed"?

**Comment by joelamos** [comment]
Ah didn't see/know what a "destructor" was  (coming from Java), so it didn't look as though dispose was being called. Thanks for pointing me in the right direction.

**Comment by filoe** [comment]
It's not the destructor. It's the `using` statement(see https://github.com/filoe/cscore/blob/master/CSCore/Extensions.cs#L229). After the using block ends, the Dispose method gets called automatically. Internal, it uses an try/finally block in order to guarantee that the Dispose method gets called.

**Comment by joelamos** [comment]
Oh, I was still talking about the WaveWriter class.

**Comment by filoe** [comment]
Well, its the same principle: https://github.com/filoe/cscore/blob/master/CSCore/Codecs/WAV/WaveWriter.cs#L116
But as I said before, its obsolete.

**Comment by joelamos** [comment]
Does that work because it extends the IDisposable class?

**Comment by filoe** [comment]
It extends the IDisposeable interface, yes.
